# Mathematische Grundlagen


## Rechenregeln basics

Nur um die Regeln noch mal zu wiederholen, auch wenn diese aus der Schule bekannt sein sollten. Dies sind einmal die Klammer vor Punkt vor Strich regeln

\begin{align*}
  1 + 3 \times 2 &= 7 \\
  7 + 12 / 4 &= 10 \\
  (3 + 7) / 5 + 1 &= 3
\end{align*}

Und das Distributivgesetz zum ausmultiplizieren bzw. zusammenfassen von Klammern.

\begin{align*}
  a \times (b + c) &= a\times b + a\times c \\
  2 \times (3 + 4) &= 2 \times 3 + 2 \times 4 \\
  10 a + a b &= a (10 + b) \\
  (a + b)^2 &= a^2 + 2ab + b^2 \\
  (a + b)\times (a - b) &= a^2 - b^2
\end{align*}

### Summenzeichen
\begin{align}
    \sum_{i=0}^{4} i &= 0 + 1 + 2 + 3 + 4\\
    \sum_{i=0}^{n} i &= 0 + 1 + 2 + 3 + \ldots + n\\
    \sum_{i=0}^{n}a_i+b_i &= \sum_{i=0}^{n}a_i + \sum_{i=0}^{n}b_i \\
    \sum_{i=0}^{n}a \times b_i &= a\sum_{i=0}^{n}b_i \label{eqn:asum} \\
    \sum_{i=1}^{3} (x_i + 3)^2 &= (x_1 + 3)^2 + (x_2 + 3)^2 + (x_3 + 3)^2 \\
    \sum_{k=1}^{n} \frac{a_k}{n} &= \frac{1}{n}\sum_{k=1}^{n} a_i = \frac{1}{n}(a_1 + a_2 + \ldots + a_n) \\
    \sum_{i=1}^{n} a &= a + a + \ldots + a = n \times a \label{eqn:consum}
\end{align}

## Gemischt

\begin{table}[!]
    \centering
    \begin{tabular}{ccc}
    \toprule
        $x_i$ & Werte & quadrierte Werte \\
        \midrule
        $x_1$  &  10 & 100\\
         $x_2$ &  5  & 25\\
         $x_3$ &  3 & 9\\
         \midrule
         $\sum$ & 18 & 134 \\
     \bottomrule
    \end{tabular}
    \caption{Beispieldaten}
    \label{tab:my_label}
\end{table}

Der Mittelwert wird im Rahmen der Statistik meistens mit einem Strich über der Variable angezeigt (z.B. $\bar{x}, \bar{z}, \bar{y}$). Dementsprechend wird der Mittelwert~$\bar{x}$ der Daten aus Tabelle~\ref{tab:my_label} wie folgt berechnet.
\begin{align}
    \bar{x} &= \frac{1}{n}\sum_{i=1}^{n}x_i \label{eqn:hat} \\
    &= \frac{1}{3}\sum_{i=1}^{3}x_i = \frac{1}{3}(10 + 5 + 3) = 6 \nonumber 
\end{align}

Beim Berechnen von Summenwerten die den Mittelwert beinhalten, kann Formel~\ref{eqn:hat} zum Vereinfachen der Berechnungen benutzt werden. Dies wird in der Statistik bei mehreren Berechnungen welche die sogenannten Abweichungsquadrate, d.h. die quadrierten Abweichungen vom Mittelwert, enthalten zu Nutze gemacht.
\begin{align}
    \sum_{i=1}^{n}(x_i - \bar{x})^2 &= \sum_{i=1}^{n}(x_i^2 - 2x_i\bar{x} + \bar{x}^2) \nonumber \\
     &= \sum_{i=1}^{n}x_i^2 - 2 \sum_{i=1}^{n}x_i\bar{x} + \sum_{i=1}^{n}\bar{x}^2 \nonumber 
\end{align}
Da der Mittelwert nicht mehr den Index enthält, kann er wie eine Konstante behandelt werden und aus der Summe rausgezogen werden (siehe Formel~\ref{eqn:asum}). Das Gleiche gilt für den letzten Term $\bar{x}^2$ der einfach n-mal genommen wird (Formel~\ref{eqn:consum}).

\begin{equation}
    \sum_{i=1}^{n}x_i^2 - 2 \sum_{i=1}^{n}x_i\bar{x} + \sum_{i=1}^{n}\bar{x}^2 = \sum_{i=1}^{n}x_i^2 - 2 \bar{x} \sum_{i=1}^{n}x_i + n \bar{x}^2 \nonumber 
\end{equation}

Mit der Identität $n\bar{x}=\sum_{i=1}^{n}x_i$, folgt daraus:

\begin{align}
    \sum_{i=1}^{n}x_i^2 - 2 \bar{x} \sum_{i=1}^{n}x_i + n \bar{x}^2 &= \sum_{i=1}^{n}x_i^2 - 2 \bar{x} n \bar{x} + n \bar{x}^2 \nonumber \\
    &= \sum_{i=1}^{n}x_i^2 - 2n\bar{x}^2 + n \bar{x}^2 \nonumber \\
    &= \sum_{i=1}^{n}x_i^2 - n\bar{x}^2 \nonumber 
\end{align}

Die Formel~\ref{eqn:hat} für den Mittelwert kann wieder benutzt werden und zurück eingesetzt werden um die Formel einfacher berechenbar zu machen:

\begin{align}
    \sum_{i=1}^{n}x_i^2 - n\bar{x}^2 &= \sum_{i=1}^{n}x_i^2 - n(\bar{x})^2 \nonumber \\
    &=  \sum_{i=1}^{n}x_i^2 - n\left(\frac{1}{n}\sum_{i=1}^nx_i\right)^2 \nonumber \\
    &=  \sum_{i=1}^{n}x_i^2 - n\left(\frac{1}{n}\right)^2\left(\sum_{i=1}^nx_i\right)^2 \nonumber \\
    &=  \sum_{i=1}^{n}x_i^2 - \frac{n}{n^2}\left(\sum_{i=1}^nx_i\right)^2 \nonumber \\
    &=  \sum_{i=1}^{n}x_i^2 - \frac{1}{n}\left(\sum_{i=1}^nx_i\right)^2 \nonumber 
\end{align}

Insgesamt folgt daher:
\begin{equation}
    \sum_{i=1}^{n}(x_i - \bar{x})^2 = \sum_{i=1}^{n}x_i^2 - \frac{1}{n}\left(\sum_{i=1}^nx_i\right)^2
    \label{eqn:rms}
\end{equation}

Die Formel~\ref{eqn:rms} bzw. Varianten dieser Formel tauchen in der Statistik immer wieder bei Berechnungen auf. Zum Beispiel bei der Berechnung der Varianz und der Korrelation. Die rechte Seite der Formel~\ref{eqn:rms} lässt auf einfache Art und Weise Abweichungsquadrate berechnen indem nur die Summen der Werte $\sum_{i=1}^{n}x_i$ und die Summe der quadrierten Werte $\sum_{i=1}^{n}x_i^2$ berechnet werden müssen (siehe Tabelle~\ref{tab:my_label}, siehe Arbeitsformeln in der Formelsammlung SQ3-Statistik).

Für das Beispiel folgt daher:
\begin{equation}
    \sum_{i=1}^{3}(x_i - \bar{x})^2 = 134 - \frac{1}{3} \times 18^2 = 26 \nonumber
\end{equation}

Beziehungsweise:
\begin{align}
    \bar{x} &= \frac{18}{3} = 6 \nonumber \\
    \sum_{i=1}^{3}(x_i - 6)^2 &= (10 - 6)^2 + (5 - 6)^2 + (3 - 6)^2 \nonumber \\
    &= 4^2 + 1^2 + 3^2 = 16 + 1 + 9 = 26 \nonumber
\end{align}
