<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Skriptum - Fortgeschrittene Statistik - 20&nbsp; Einführung</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ed_crd.html" rel="next">
<link href="./ed_title.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>
<script>
  MathJax = {
    tex: {
      tags: 'ams'  // should be 'ams', 'none', or 'all'
    }
  };
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ed_title.html">Experimentelles Design</a></li><li class="breadcrumb-item"><a href="./ed_basics.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Einführung</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skriptum - Fortgeschrittene Statistik</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./r_startup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eine Schnelleinführung in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Eine Übersicht über <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_kickoff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title"><code>R</code> Kickoff</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_flowcontrol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Ablaufkontrolle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Einfache Datenbearbeitung und Visualisierung in <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_literate_programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Literate programming in <code>R</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stats_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistik</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Eine kleine Welt der Unsicherheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistische Signifikanz, p-Wert und Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Parameterschätzung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Theoretische Verteilungen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_hypotheses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hypothesen testen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./slm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das einfache Regressionmodell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inferenz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_model_fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Modellfit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Vorhersage</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mlm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Interaktionseffekte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_dummy_coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Integration von nominalen Variablen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_hierarchies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Modellhierarchien</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./lm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das allgemeine lineare Modell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Synthese</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./ed_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_basics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Completely Randomized Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_linear_contrasts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Lineare Kontraste</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crfd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Completely Randomized Factorial Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crbd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Completely Randomized Block Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_irbd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Incomplete Randomized Block Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_split_plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Split-plot Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_cross_over.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Cross-over Design</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatur</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#zuteilung-der-stichprobengrößen-in-zwei-gruppen" id="toc-zuteilung-der-stichprobengrößen-in-zwei-gruppen" class="nav-link active" data-scroll-target="#zuteilung-der-stichprobengrößen-in-zwei-gruppen"><span class="header-section-number">20.1</span> Zuteilung der Stichprobengrößen in zwei Gruppen</a></li>
  <li><a href="#terminologie" id="toc-terminologie" class="nav-link" data-scroll-target="#terminologie"><span class="header-section-number">20.2</span> Terminologie</a></li>
  <li><a href="#übersicht-über-verschiedene-designs" id="toc-übersicht-über-verschiedene-designs" class="nav-link" data-scroll-target="#übersicht-über-verschiedene-designs"><span class="header-section-number">20.3</span> Übersicht über verschiedene Designs</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Einführung</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Im Folgenden beschäftigen wir uns mit experimentellen Design. D.h. wir untersuchen wie wir ein Experiment aus statistischer Sicht erstellen sollten um die Wahrscheinlichkeit einen bestimmten Effekt zu beobachten möglichst Effizient zu erhöhen. Eine zentrale Größe wird dabei immer wieder der Standardfehler <span class="math inline">\(\sigma_e\)</span> der jeweiligen Statistik spielen die wählen um einen bestimmten Effekt zu untersuchen. Daher fangen wir erst einmal mit einem einfachen Beispiel an.</p>
<section id="zuteilung-der-stichprobengrößen-in-zwei-gruppen" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="zuteilung-der-stichprobengrößen-in-zwei-gruppen"><span class="header-section-number">20.1</span> Zuteilung der Stichprobengrößen in zwei Gruppen</h2>
<p>Die folgenden Beispiel sind alle aus <span class="citation" data-cites="goos2011">Goos und Jones (<a href="references.html#ref-goos2011" role="doc-biblioref">2011</a>)</span> entnommen. Wir möchten den Unterschied bezüglich des Mittelwerts zwischen zwei Gruppen <span class="math inline">\(1\)</span> und <span class="math inline">\(2\)</span> untersuchen. In Gruppe <span class="math inline">\(1\)</span> haben wir eine Stichprobengröße von <span class="math inline">\(n_1\)</span> und entsprechend eine Stichprobegröße <span class="math inline">\(n_2\)</span> in Gruppe <span class="math inline">\(2\)</span>. Den Unterschied zwischen den beiden Mittelwerten aus den Gruppen berechnen wir wie bekannt nach.</p>
<p><span class="math display">\[\begin{equation}
D = \bar{X}_1 - \bar{X}_2
\end{equation}\]</span></p>
<p>Um die Wahrscheinlichkeit zu erhöhen einen relevanten Unterschied <span class="math inline">\(D\)</span> zwischen den Gruppen zu finden sollten wir das Design des Experiments so wählen, dass die Varianz <span class="math inline">\(\sigma^2(D)\)</span> bzw. der Standardfehler <span class="math inline">\(\sigma_e(D)\)</span> von <span class="math inline">\(D\)</span> möglichst klein wird. Umso kleiner der Standardfehler umso geringer sind die Streuungen in den Stichprobenverteilung und umso geringer ist die Unsicherheit. Die Varianz <span class="math inline">\(\sigma^2(D)\)</span> berechnet sich nach:</p>
<p><span class="math display">\[\begin{equation}
\sigma^2(D) = \frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}
\end{equation}\]</span></p>
<p>Der Standardfehler von <span class="math inline">\(D\)</span> ist dementsprechend die Wurzel der Varianz. Schauen wir uns an, was dies in einem konkreten Fall bedeutet. Wir gehen von einer Gesamtstichprobengröße von <span class="math inline">\(N = 12\)</span> und der Einfachheit halber von einer Standardabweichungen in beiden Population von <span class="math inline">\(\sigma^2_1 = \sigma^2_2 = \sigma^2 = 1\)</span> aus.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ed-basics-sample-01" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;20.1: Abhängigkeit der Varianz und des Standardfehler von <span class="math inline">\(D\)</span> mit der Stichprobenverteilung bei gleicher Varianz</caption>
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(n_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(n_2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\sigma^2(D)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\sigma_e(D)\)</span></th>
<th style="text-align: right;">Effizienz</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">0.31</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">0.56</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.75</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">0.89</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">0.89</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.75</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">0.56</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">0.31</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In <a href="#tbl-ed-basics-sample-01">Tabelle&nbsp;<span>20.1</span></a> sind die Varianz <span class="math inline">\(\sigma^2(D)\)</span> und der Standardfehler <span class="math inline">\(\sigma_e(D)\)</span> gegen die Stichprobenverteilung abgetragen. Wir können sehen, dass bei gleicher Stichprobenanzahl in beiden Gruppen die Varianz und somit auch der Standardfehler den kleinsten Wert annehmen. In der fünften Spalte von <a href="#tbl-ed-basics-sample-01">Tabelle&nbsp;<span>20.1</span></a> ist ein Wert Effizient eingetragen. Dieser Wert berechnet sich aus dem Verhältnis der kleinstmöglichen Varianz zur jeweiligen Varianz. Wir können an diesem Wert abschätzen, das ein Design bei dem in einer der Gruppen nur eine einzige Person ist, die Effizienz nur noch ein Drittel dessen ist, was bei einer gleichmäßigen Stichprobenverteilung zu errreichen ist. D.h. so weit ist die übliche Herangehensweise, beide Gruppen möglichst gleichgroß zu gestalten vollkommmen sinnvoll.</p>
<p>Schauen wir uns als Nächstes an, wie das aussieht wenn die Stichprobengröße <span class="math inline">\(N\)</span> anwächst. In <a href="#fig-ed-basics-sample-01">Abbildung&nbsp;<span>20.1</span></a> ist der Standardfehler <span class="math inline">\(\sigma_e(D)\)</span> gegen verschiedene Zuteilungen der Stichproben in die beiden Gruppen für verschiedene Stichprobengrößen abgebildet.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ed-basics-sample-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ed_basics_files/figure-html/fig-ed-basics-sample-01-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;20.1: Zusammenhang zwischen den Standardfehler und Verteilung der Stichproben in die Gruppen für verschiedene Stichprobengrößen</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-ed-basics-sample-01">Abbildung&nbsp;<span>20.1</span></a> ist zu sehen, das das bei gleichen Varianzen die gleichmäßige Verteilung der Stichprobe in die beiden Gruppen immer diejenige mit dem kleinsten Standardfehler ist. Der Standardfehler nimmt natürlich mit der Größe der Stichprobe ab. Allerdings nimmt auch die Größe der Verschlechterung bei ungleicher Verteilung mit der Größe der Stichprobe ab. Daher, wenn wir eine große Stichprobe haben, dann ist die gleichmäßige Verteilung der Stichproben weniger wichtig als bei kleinen Stichprobengrößen.</p>
<p>Schauen wir uns daher als nächsten Fall an, was passiert wenn die Varianzen in den beiden Gruppen nicht mehr gleich sind. Sei zum Beispiel <span class="math inline">\(\sigma^2 = 1\)</span> und <span class="math inline">\(\sigma^2 = 9\)</span>. Also ein recht extremer Unterschied zwischen den beiden Gruppen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ed-basics-sample-02" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;20.2: Abhängigkeit der Varianz und des Standardfehler von <span class="math inline">\(D\)</span> mit der Stichprobenverteilung bei ungleicher Varianz <span class="math inline">\(\sigma_1^2 = 1, \sigma_2^2=9\)</span></caption>
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(n_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(n_2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\sigma^2(D)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\sigma_e(D)\)</span></th>
<th style="text-align: right;">Effizienz</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">1.82</td>
<td style="text-align: right;">1.35</td>
<td style="text-align: right;">0.73</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">1.40</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">0.95</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">1.33</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1.38</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">1.49</td>
<td style="text-align: right;">1.22</td>
<td style="text-align: right;">0.90</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1.67</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">0.80</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.94</td>
<td style="text-align: right;">1.39</td>
<td style="text-align: right;">0.69</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2.38</td>
<td style="text-align: right;">1.54</td>
<td style="text-align: right;">0.56</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3.11</td>
<td style="text-align: right;">1.76</td>
<td style="text-align: right;">0.43</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4.60</td>
<td style="text-align: right;">2.14</td>
<td style="text-align: right;">0.29</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.09</td>
<td style="text-align: right;">3.02</td>
<td style="text-align: right;">0.15</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In <a href="#tbl-ed-basics-sample-02">Tabelle&nbsp;<span>20.2</span></a> sind wieder die verschiedenen Werte für <span class="math inline">\(\sigma^2(D)\)</span>, <span class="math inline">\(\sigma_e(D)\)</span> und die Effizienz berechnet worden. Wir können sehen, dass jetzt nicht mehr das Design mit gleichgroßen Stichproben optimal ist, sondern das Design mit <span class="math inline">\(n_1 = 3\)</span> und <span class="math inline">\(n_2 = 9\)</span>. D.h. die ungleiche Varianz in den beiden Gruppen hat dazu geführt, dass der minimale Standardfehler dann eingenommen wird, wenn wir einen größere Stichprobe aus Gruppe <span class="math inline">\(2\)</span> ziehen als aus Gruppe <span class="math inline">\(1\)</span>.</p>
<p>Wenn wir diese nicht gewusst hätten und in beiden Gruppen wieder mit <span class="math inline">\(n_i = 6\)</span> gearbeitet hätten, hätten wir somit <span class="math inline">\(20\%\)</span> Effizienz eingebüßt. Intuitiv macht diese ungleiche Verteilung auch Sinn. Da die Varianz in Gruppe <span class="math inline">\(2\)</span> größer ist, ist auch unserer Unsicherheit über den Mittelwert in dieser Gruppe größer. Um diese Unsicherheit auszugleichen erhöhen wir die Stichprobenanzahl im Verhältnis zu Gruppe <span class="math inline">\(1\)</span> um mehr Information über die diese Gruppe zu erhalten. Intuitiv macht diese ungleiche Verteilung auch Sinn. Da die Varianz in Gruppe <span class="math inline">\(2\)</span> größer ist, ist auch unserer Unsicherheit über den Mittelwert in dieser Gruppe größer. Um diese Unsicherheit auszugleichen erhöhen wir die Stichprobenanzahl im Verhältnis zu Gruppe <span class="math inline">\(1\)</span> um mehr Information über die diese Gruppe zu erhalten.</p>
<p>Schauen wir uns ein Beispiel an, bei dem die Unterschied in den Varianzen zwischen den beiden Gruppen nicht ganz so extrem sind (siehe <a href="#tbl-ed-basics-sample-03">Tabelle&nbsp;<span>20.3</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ed-basics-sample-03" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;20.3: Abhängigkeit der Varianz und des Standardfehler von <span class="math inline">\(D\)</span> mit der Stichprobenverteilung bei ungleicher Varianz <span class="math inline">\(\sigma_1^2 = 1, \sigma_2^2=2\)</span></caption>
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(n_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(n_2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\sigma^2(D)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\sigma_e(D)\)</span></th>
<th style="text-align: right;">Effizienz</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">0.41</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">0.69</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.87</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.54</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">0.89</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">0.78</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">0.62</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.10</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">0.44</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.09</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">0.23</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In <a href="#tbl-ed-basics-sample-03">Tabelle&nbsp;<span>20.3</span></a> sehen wir wieder, das das effizienteste Design nicht gleich große Stichproben in den beiden Gruppen hat, sondern hier würde das Design mit <span class="math inline">\(n_1 = 5\)</span> und <span class="math inline">\(n_2 = 7\)</span> den niedrigsten Standardfehler zeigen. Der Verlust an Effizienz bei gleich großen Gruppen wäre hier praktisch zu vernachlässigen. D.h. wenn wir keine genauen Information haben wie sich die Varianzen in den beiden Gruppen verhalten, aber wir keine großen Unterschiede erwarten, dann sind wir mit gleichgroßen Gruppen wahrscheinlich oft gut bedient.</p>
<p>Untersuchen wir die Effizienz noch einmal aus einer anderen Perspektive, nämlich des Budget das uns zur Verfügung steht. Nehmen wir an wir müssen die Untersuchung in einem Speziallabor durchführen und wir haben nur eine begrenzte Zeit zur Verfügung. Wir untersuchen wieder zwei Gruppen bei denen aber die Vorbereitung des Experiment doppelt solange für Gruppe <span class="math inline">\(2\)</span> dauert im Vergleich zu Gruppe <span class="math inline">\(1\)</span>. Zum Beispiel in Gruppe <span class="math inline">\(1\)</span> benötigen wir das Labor für eine Stunde während wir für Teilnehmerinnen und Teilnehmer aus Gruppe <span class="math inline">\(2\)</span> zwei Stunden benötigen. In Gruppe <span class="math inline">\(2\)</span> ist vielleicht eine spezielle Patientenpopulation bei der wir mehr Zeit einplanen müssen. Wir haben aber nur insgesamt <span class="math inline">\(24\)</span> Stunden das Labor zu Verfügung. Wir setzen wieder <span class="math inline">\(\sigma^2 = 1\)</span> an. Wie sollten wir die Gruppengrößen zuteilen?</p>
<p>Wir können jetzt nicht einfach die gleiche Tabelle wie in den obigen Fällen benutzen, da wir unser Zeitbudget beachten müssen. Mit etwas ausprobieren kommen wir zu folgendem Ergebnis.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ed-basics-sample-04" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;20.4: Abhängigkeit der Varianz und des Standardfehler von <span class="math inline">\(D\)</span> bei <span class="math inline">\(\sigma_i^2 = 1\)</span> und Budgetbeschränkungen von <span class="math inline">\(24\)</span> Stunden</caption>
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(n_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(n_2\)</span></th>
<th style="text-align: right;">Kosten</th>
<th style="text-align: right;"><span class="math inline">\(\sigma^2(D)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\sigma_e(D)\)</span></th>
<th style="text-align: right;">Effizienz</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">22</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">0.23</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">0.44</td>
</tr>
<tr class="odd">
<td style="text-align: right;">18</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.62</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">0.78</td>
</tr>
<tr class="odd">
<td style="text-align: right;">14</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">0.89</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">0.87</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.69</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: right;">0.41</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Wir sehen wieder in <a href="#tbl-ed-basics-sample-04">Tabelle&nbsp;<span>20.4</span></a>, dass eine ungleiche Verteilung in die Gruppen die höchste Effizienz hat. Der Effekt hier, ist dass wir hier eine Balance finden müssen zwischen den größten Anzahl einer Teilnehmerinnen und Teilnehmer und der Ungleichheit der Stichprobengrößen.</p>
<p>Zusammenfassend können wir sagen, dass bei Vergleichen zweier Gruppen das Design mit gleich großen Stichproben in beiden Gruppen die Beste Wahl ist. In Abhängigkeit wie sich die Varianzen zwischen den Gruppen verhalten und oder auch welche Randbedingungen wir für die Durchführung des Experiment haben können die Aussagen sehr unterschiedlich sein. Daher macht es Sinn sich für seinen speziellen Fall etwas Gedanken zu machen welches Design den bestmöglichen Output liefert und vielleicht nicht einfach nur ein Standarddesign aus der Schublade. Die Problematik eine informierte Entscheidung diesbezüglich zu treffen wird in den folgenden Kapitel immer wieder aufgegriffen.</p>
</section>
<section id="terminologie" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="terminologie"><span class="header-section-number">20.2</span> Terminologie</h2>
<p>Zunächst müssen einmal vier Grundbegriffe des experimentellen Designs definiert werden diese sind, die Experimentelle Einheit (engl. Experimental unit), die Beobachtungseinheit (engl. observational unit), der Replikationsfaktor (engl. replication) und der Wiederholungsfaktor (engl. repetition bzw. auch Pseudoreplication).</p>
<div id="def-experimental-unit" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 20.1 (Experimentelle Einheit (EU)) </strong></span>Die experimentelle Einheit bezeichnet das Objekt welches untersucht wird und dem eine bestimmte Intervention (engl. treatment) bzw. experimentelle Kondition zugewiesen wird. Diese Zuweisung muss zufällig (randomisiert) stattfinden. Die Intervention bzw. die Kondition muss unabhängig von anderen experimentellen Einheiten zugewiesen werden. Die Gesamtzahl der experimentellen Einheiten bestimmt die Stichprobengröße des Experiments.</p>
</div>
<div id="def-observation-unit" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 20.2 (Beobachtungseinheit (OU)) </strong></span>Die Beobachtungseinheit ist das Objekt, an der eine Messung vorgenommen wird. Die Beobachtungseinheit kann sich von der experimentellen Einheit unterscheiden.</p>
<p>Führen wir zum Beispiel ein fünf-tägiges Experiment mit <span class="math inline">\(10\)</span> Teilneherinnen durch. Wenn wir nur eine Messung auf jeder Person am Ende des Experiments durchführen. Dann sind insgesamt <span class="math inline">\(12\)</span> Beobachtungseinheiten vorhanden. Messen wir aber jede Person an jedem Tag erhalten wir <span class="math inline">\(5 \times 12 = 60\)</span> Beobachtungseinheiten. Im ersten Fall, sind die experimentellen Einheiten und die Beobachtungseinheiten identisch.</p>
</div>
<div id="def-replication" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 20.3 (Replikation) </strong></span>Eine Replikation ist die Wiederholung der Versuchssituation durch Replikation der Versuchseinheit. Replikationsläufe sind zwei oder mehr Versuche, die mit denselben Bedingungen der experimentellen Kondition bzw. unabhängigen Variablen mit <strong>unterschiedlichen</strong> experimentellen Einheiten durchgeführt werden. Der Wert der gemessene abhängigen Variable kann sich zwischen den Replikationsläufen aufgrund von Änderungen Störvariablen und inhärenten Unterschieden in den Versuchseinheiten unterscheiden.</p>
</div>
<div id="def-repetition" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 20.4 (Wiederholung/Pseudoreplikation) </strong></span>Wenn die experimentelle Einheit nach der Applikation des Treatments bzw. der Kondition aufgeteilt wird, spricht man von einer Untereinheit. Die Messungen an Untereinheiten derselben experimentellen Einheit sind in der Regel korreliert und sollten daher nicht als unabhängige Ergebnisse behandelt werden.</p>
</div>
<p>In <a href="#tbl-ed-basics-ex-01">Tabelle&nbsp;<span>20.5</span></a> ist ein Beispiel für eine einfaches experimentelle Design abgebildet. Es wurden insgesamt <span class="math inline">\(9\)</span> TeilnehmerInnen zufällig auf <span class="math inline">\(3\)</span> Konditionen <span class="math inline">\(A_1, A_2, A_3\)</span> verteilt und auf jeder Person wurde eine Messung unter der entsprechenden Kondition durchgeführt. Jede Person ist einzeln untersucht wurden.</p>
<div id="tbl-ed-basics-ex-01" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;20.5: Beispiel für ein experientelles Design (X = Messung)</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th rowspan="2">Teilnehmer</th>
<th colspan="3"><pre><code>    Faktor</code></pre></th>
</tr>
<tr class="odd">
<th><span class="math inline">\(A_1\)</span></th>
<th><span class="math inline">\(A_2\)</span></th>
<th><span class="math inline">\(A_3\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P1</td>
<td>X</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>P2</td>
<td></td>
<td>X</td>
<td></td>
</tr>
<tr class="odd">
<td>P3</td>
<td></td>
<td>X</td>
<td></td>
</tr>
<tr class="even">
<td>P4</td>
<td></td>
<td></td>
<td>X</td>
</tr>
<tr class="odd">
<td>P5</td>
<td>X</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>P6</td>
<td></td>
<td></td>
<td>X</td>
</tr>
<tr class="odd">
<td>P7</td>
<td></td>
<td>X</td>
<td></td>
</tr>
<tr class="even">
<td>P8</td>
<td>X</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>P9</td>
<td></td>
<td></td>
<td>X</td>
</tr>
</tbody>
</table>
</div>
<p>Was sind in diesem Fall die EU und OUs und was ist der Replikationsfaktor und der Wiederholungsfaktor? Die Personen sind randomisiert den verschiedenen Konditionen zugewiesen worden und das <em>treatment</em> erfolgt unabhängig von allen anderen Personen. Daher sind die Personen die EU und <span class="math inline">\(N = 9\)</span>. Da auf jeder Person nur eine Messung erfolgt, haben wir auch insgesamt <span class="math inline">\(9\)</span> OUs. D.h. die experimentellen Einheiten und die Beobachtungseinheiten sind in diesem Design identisch. Jede Kondition wurde dreimal durch unabhängige EUs repliziert, daher ist der Replikationsfaktor <span class="math inline">\(3\)</span>. Wir haben keine Wiederholungen auf den EUs, dadurch haben wir keine Pseudoreplikation.</p>
<p>In <a href="#tbl-ed-basics-ex-02">Tabelle&nbsp;<span>20.6</span></a> haben wir ein ähnliches Design. Im Unterschied zu <a href="#tbl-ed-basics-ex-01">Tabelle&nbsp;<span>20.5</span></a> sind auf jeder Person nun zwei Messungen durchgeüführt worden.</p>
<div id="tbl-ed-basics-ex-02" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;20.6: Beispiel für ein experientelles Design mit zwei Messungen (X = Messung)</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th rowspan="2">Teilnehmer</th>
<th colspan="3"><pre><code>    Faktor</code></pre></th>
</tr>
<tr class="odd">
<th><span class="math inline">\(A_1\)</span></th>
<th><span class="math inline">\(A_2\)</span></th>
<th><span class="math inline">\(A_3\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P1</td>
<td>X X</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>P2</td>
<td></td>
<td>X X</td>
<td></td>
</tr>
<tr class="odd">
<td>P3</td>
<td></td>
<td>X X</td>
<td></td>
</tr>
<tr class="even">
<td>P4</td>
<td></td>
<td></td>
<td>X X</td>
</tr>
<tr class="odd">
<td>P5</td>
<td>X X</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>P6</td>
<td></td>
<td></td>
<td>X X</td>
</tr>
<tr class="odd">
<td>P7</td>
<td></td>
<td>X X</td>
<td></td>
</tr>
<tr class="even">
<td>P8</td>
<td>X X</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>P9</td>
<td></td>
<td></td>
<td>X X</td>
</tr>
</tbody>
</table>
</div>
<p>Dadurch sind immernoch die <span class="math inline">\(EU = 9\)</span> und der Replikationsfaktor <span class="math inline">\(=2\)</span>. Die Beobachtungseinheiten sind jetzt verdoppelt <span class="math inline">\(OU = 18\)</span> und wir erhalten einen Pseudoreplikationsfaktor von <span class="math inline">\(2\)</span>.</p>
<p>Im nächsten Design wird es nun etwas komplizierter. Wir untersuchen drei verschiedene Treatments <span class="math inline">\(A_1, A_2\)</span> und <span class="math inline">\(A_3\)</span> mit insgesamt neun Studienteilnehmern. Die Teilnehmer wurden aus drei verschiedenen Vereinen akquiriert. Als Randbedingung können wir die Treatments immer nur einheitlich pro Verein anwenden. D.h. alle Teilnehmer aus einem Verein erhalten das gleiche Treatment. Die Zuordnung der Treatments auf die Vereine erfolgt jedoch randomisiert. Es ergibt sich die folgende Designstruktur <a href="#tbl-ed-basics-ex-03">Tabelle&nbsp;<span>20.7</span></a>.</p>
<div id="tbl-ed-basics-ex-03" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;20.7: Beispiel für ein experientelles Design mit einer Gruppierungstruktur (X = Messung)</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th rowspan="2"></th>
<th rowspan="2">Teilnehmer</th>
<th colspan="3"><pre><code>    Faktor</code></pre></th>
</tr>
<tr class="odd">
<th><span class="math inline">\(A_1\)</span></th>
<th><span class="math inline">\(A_2\)</span></th>
<th><span class="math inline">\(A_3\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="3">Verein I</td>
<td>P1</td>
<td></td>
<td>X</td>
<td></td>
</tr>
<tr class="even">
<td>P2</td>
<td></td>
<td>X</td>
<td></td>
</tr>
<tr class="odd">
<td>P3</td>
<td></td>
<td>X</td>
<td></td>
</tr>
<tr class="even">
<td rowspan="3">Verein II</td>
<td>P4</td>
<td>X</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>P5</td>
<td>X</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>P6</td>
<td>X</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td rowspan="3">Verein III</td>
<td>P7</td>
<td></td>
<td></td>
<td>X</td>
</tr>
<tr class="even">
<td>P8</td>
<td></td>
<td></td>
<td>X</td>
</tr>
<tr class="odd">
<td>P9</td>
<td></td>
<td></td>
<td>X</td>
</tr>
</tbody>
</table>
</div>
<p>In diesem Fall erfolgt die Zuweisung der Treatments also nicht auf dem Level der Teilnehmer, sondern auf dem Level der drei Vereine. Dies führt nun dazu, da die experimentellen Einheiten laut der Definition die Treatment randomisiert zugewiesen bekommen müssen, dazu, dass die Vereine zu den experimentellen Einheiten werden, nicht die einzelnen Teilnehmer. Folgerichtig ist <span class="math inline">\(N\)</span> is diesem Fall <span class="math inline">\(N = 3\)</span> und nicht <span class="math inline">\(N = 9\)</span> wie in den beiden vorhergehenden Fällen. Dies führt weiterhin dazu, dass wir keine Replikation der experimentellen Einheiten vorliegen haben, da jede Kondition nur einmal unter eine experimentellen Einheit beobachtet wurde. Darauf folgt sofort, dass es nicht möglich ist die Ergebnisse über die Studiegruppe hinaus zu generalisieren, da keine ausreichend große Stichprobe gezogen haben. Wir haben nur eine einzelne experimentelle Einheit beobachtet und können keine Aussagen über die Varianz zwischen experimentellen Einheiten aussagen. Die drei Teilnehmer innerhalb der jeweiligen Vereine werden als Pseudoreplikationen mit einem Faktor von <span class="math inline">\(3\)</span> interpretiert. Da wir insgesamt neun Messungen beobachten erhalten wir neun Beobachtungseinheiten.</p>
<p>Um aus den Teilneherm tatsächlich auch neun experimentelle Einheiten zu machen, müssen wir die Treatments unabhängig von den Vereinen randomisieren. Zusätzlich müssen wir auch noch sicherstellen, das das Treatment in isolation durchgeführt wird, da, wieder der Definition folgend, das Treatment unabhängig von den anderen experimentellen Einheiten durchgeführt werden muss. D.h. wir können auch keine Gruppen bilden die beispielsweise gemeinsam trainieren, da es dadurch auch wieder zu ungewollten Interaktioneffekten zwischen den experimentellen Einheiten kommen kann, welche die Unabhängigkeit der experimentellen Einheiten beeinflusst. Dadurch würde dann wieder jede Gruppe zu einer experimentellen Einheit zusammengeführt. Die Nichtbeachtung von Abhängigkeiten zwischen experimentellen Einheiten führt in der Analyse zu fehlerhaften Ergebnisse die insbesondere zu einer Vergrößerung des Type-I Fehler führen. D.h. Ergebnisse werden zu oft als statistisch signifikant deklariert (<span class="citation" data-cites="hurlbert1984">Hurlbert (<a href="references.html#ref-hurlbert1984" role="doc-biblioref">1984</a>)</span>, <span class="citation" data-cites="lazic2018">Lazic, Clarke-Williams, und Munafò (<a href="references.html#ref-lazic2018" role="doc-biblioref">2018</a>)</span>, <span class="citation" data-cites="silverman2004">Silverman (<a href="references.html#ref-silverman2004" role="doc-biblioref">2004</a>)</span>).</p>
</section>
<section id="übersicht-über-verschiedene-designs" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="übersicht-über-verschiedene-designs"><span class="header-section-number">20.3</span> Übersicht über verschiedene Designs</h2>
<table class="table">
<caption>Example for a Completely Randomized Design</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th colspan="3" style="text-align: center;">Factor A</th>
</tr>
<tr class="odd">
<th>EU</th>
<th style="text-align: center;">A1</th>
<th style="text-align: center;">A2</th>
<th style="text-align: center;">A3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>5</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>6</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
</tr>
</tbody>
</table>
<table class="table">
<caption>Example for a Completely Randomized Factorial Design with two factors</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th colspan="2" style="text-align: center;">A1</th>
<th colspan="2" style="text-align: center;">A2</th>
</tr>
<tr class="odd">
<th>EU</th>
<th style="text-align: center;">B1</th>
<th style="text-align: center;">B2</th>
<th style="text-align: center;">B1</th>
<th style="text-align: center;">B2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
</tr>
</tbody>
</table>
<table class="table">
<caption>Example for a Completely Randomized Block Design</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>B</th>
<th style="text-align: center;">A1</th>
<th style="text-align: center;">A2</th>
<th style="text-align: center;">A3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>I</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
</tr>
<tr class="even">
<td>II</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
</tr>
<tr class="odd">
<td>III</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
</tr>
<tr class="even">
<td>IV</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
</tr>
</tbody>
</table>
<table class="table">
<caption>Example for an Incomplete Block Design</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Block</th>
<th style="text-align: center;">A1</th>
<th style="text-align: center;">A2</th>
<th style="text-align: center;">A3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>I</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>II</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
</tr>
<tr class="odd">
<td>III</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
</tr>
<tr class="even">
<td>IV</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>V</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
</tr>
<tr class="even">
<td>VI</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
</tr>
</tbody>
</table>
<table class="table">
<caption>Example for a Split-plot Design</caption>
<colgroup>
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th colspan="3" style="text-align: center;">A1</th>
<th colspan="3" style="text-align: center;">A2</th>
</tr>
<tr class="odd">
<th>EU</th>
<th style="text-align: center;">B1</th>
<th style="text-align: center;">B2</th>
<th style="text-align: center;">B3</th>
<th style="text-align: center;">B1</th>
<th style="text-align: center;">B2</th>
<th style="text-align: center;">B3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">X</td>
</tr>
</tbody>
</table>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-goos2011" class="csl-entry" role="listitem">
Goos, Peter, und Bradley Jones. 2011. <em>Optimal design of experiments: a case study approach</em>. John Wiley &amp; Sons.
</div>
<div id="ref-hurlbert1984" class="csl-entry" role="listitem">
Hurlbert, S. H. 1984. <span>„Pseudoreplication and the Design of Ecological Field Experiments“</span>. <em>Ecological Monographs</em> 54 (2): 187–211. <a href="https://doi.org/10.2307/1942661">https://doi.org/10.2307/1942661</a>.
</div>
<div id="ref-lazic2018" class="csl-entry" role="listitem">
Lazic, Stanley E, Charlie J Clarke-Williams, und Marcus R Munafò. 2018. <span>„What exactly is ‘N’in cell culture and animal experiments?“</span> <em>PLoS biology</em> 16 (4): e2005282. <a href="https://doi.org/10.1371/journal.pbio.2005282">https://doi.org/10.1371/journal.pbio.2005282</a>.
</div>
<div id="ref-silverman2004" class="csl-entry" role="listitem">
Silverman, S. 2004. <span>„Analyzing data from field research: the unit of analysis issue“</span>. <em>Res Q Exerc Sport</em> 75 (2): iii–iv. <a href="https://doi.org/10.1080/02701367.2004.10609141">https://doi.org/10.1080/02701367.2004.10609141</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ed_title.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Experimentelles Design</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ed_crd.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Completely Randomized Design</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>