<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>21&nbsp; Polynome und Prädiktion – Skriptum - Fortgeschrittene Statistik</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./mlm_logistic.html" rel="next">
<link href="./mlm_hierarchies.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-364982630eef5352dd1537128a8ed5cb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>
<script>

  MathJax = {

    tex: {

      tags: 'ams'  // should be 'ams', 'none', or 'all'

    }

  };

</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./mlm_title.html">Multiple Regression</a></li><li class="breadcrumb-item"><a href="./mlm_prediction.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Polynome und Prädiktion</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skriptum - Fortgeschrittene Statistik</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./r_startup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eine Einführung in die Programmiersprache R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Eine Übersicht über <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_vars_types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Variablen und Datentypen in <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_flowcontrol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Ablaufkontrolle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Funktionen in <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Datenverarbeitung mit <code>tidyverse</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Datenvisualisierung mit <code>ggplot2</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_literate_programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Literate programming in <code>R</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stats_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistik - Die Grundlagen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Eine kleine Welt der Unsicherheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Statistische Signifikanz, p-Wert und Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Parameterschätzung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Theoretische Verteilungen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_hypotheses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Weitere Grundlagen der Statistik</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./slm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das einfache Regressionmodell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Inferenz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_model_fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Modellfit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vorhersage</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mlm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Interaktionseffekte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_dummy_coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Integration von nominalen Variablen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_hierarchies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Modellhierarchien</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_prediction.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Polynome und Prädiktion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./ed_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Reliabilität</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Completely Randomized Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_linear_contrasts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Lineare Kontraste</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crfd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Completely Randomized Factorial Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crbd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Block Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_irbd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Incomplete Randomized Block Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_split_plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Split-plot Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_cross_over.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Cross-over Design</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Mathematische Grundlagen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatur</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#multiple-regression-und-polynome" id="toc-multiple-regression-und-polynome" class="nav-link active" data-scroll-target="#multiple-regression-und-polynome"><span class="header-section-number">21.1</span> Multiple Regression und Polynome</a>
  <ul class="collapse">
  <li><a href="#polynomregression-in-r" id="toc-polynomregression-in-r" class="nav-link" data-scroll-target="#polynomregression-in-r"><span class="header-section-number">21.1.1</span> Polynomregression in <code>R</code></a></li>
  </ul></li>
  <li><a href="#vorhersage-versus-inferenz" id="toc-vorhersage-versus-inferenz" class="nav-link" data-scroll-target="#vorhersage-versus-inferenz"><span class="header-section-number">21.2</span> Vorhersage versus Inferenz</a></li>
  <li><a href="#modellbewertung" id="toc-modellbewertung" class="nav-link" data-scroll-target="#modellbewertung"><span class="header-section-number">21.3</span> Modellbewertung</a></li>
  <li><a href="#validierungsansatz" id="toc-validierungsansatz" class="nav-link" data-scroll-target="#validierungsansatz"><span class="header-section-number">21.4</span> Validierungsansatz</a>
  <ul class="collapse">
  <li><a href="#validierungsansatz-in-r" id="toc-validierungsansatz-in-r" class="nav-link" data-scroll-target="#validierungsansatz-in-r"><span class="header-section-number">21.4.1</span> Validierungsansatz in <code>R</code></a></li>
  <li><a href="#k-fache-kreuzvalidierung" id="toc-k-fache-kreuzvalidierung" class="nav-link" data-scroll-target="#k-fache-kreuzvalidierung"><span class="header-section-number">21.4.2</span> K-fache Kreuzvalidierung</a></li>
  <li><a href="#k-fache-kreuzvalidierung-in-r" id="toc-k-fache-kreuzvalidierung-in-r" class="nav-link" data-scroll-target="#k-fache-kreuzvalidierung-in-r"><span class="header-section-number">21.4.3</span> K-fache Kreuzvalidierung in <code>R</code></a></li>
  </ul></li>
  <li><a href="#bias-variance-trade-off" id="toc-bias-variance-trade-off" class="nav-link" data-scroll-target="#bias-variance-trade-off"><span class="header-section-number">21.5</span> Bias-Variance Trade-off</a></li>
  <li><a href="#zum-nach--und-weiterlesen" id="toc-zum-nach--und-weiterlesen" class="nav-link" data-scroll-target="#zum-nach--und-weiterlesen"><span class="header-section-number">21.6</span> Zum Nach- und Weiterlesen</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./mlm_title.html">Multiple Regression</a></li><li class="breadcrumb-item"><a href="./mlm_prediction.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Polynome und Prädiktion</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Polynome und Prädiktion</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Im folgenden wird das lineare Modell noch erweitert indem nun auch Zusammenhänge abgebildet werden können, die nicht nur linear sind, sondern die Zusammenhänge zwischen <span class="math inline">\(X\)</span> und <span class="math inline">\(Y\)</span> können auch kurvenförmig sein. Beispielsweise einer Parabel <span class="math inline">\(Y = X^2\)</span> folgen. Dies lässt sich auch problemlos in das <em>lineare</em> Modell integrieren, indem die Prädiktorvariablen in Potenzen in das Modell integriert werden. Anschließend wird noch einmal die Frage untersucht welche Prädiktorvariablen in das Modell integriert werden sollen und wie verschiedene Modell miteinander verglichen werden können.</p>
<section id="multiple-regression-und-polynome" class="level2" data-number="21.1">
<h2 data-number="21.1" class="anchored" data-anchor-id="multiple-regression-und-polynome"><span class="header-section-number">21.1</span> Multiple Regression und Polynome</h2>
<p>In der Praxis kann es durchaus vorkommen, dass der Zusammenhang zwischen den Prädiktorvariablen <span class="math inline">\(X\)</span> und der abhängigen Variable <span class="math inline">\(Y\)</span> nicht linear ist, sondern eher kurvenförmig. Beispielsweise ist in <span class="citation" data-cites="pickett2021">Pickett u.&nbsp;a. (<a href="references.html#ref-pickett2021" role="doc-biblioref">2021</a>)</span> der Zusammenhang zwischen der Ermüdung und der Wettkampfleistung untersucht worden und der folgende Zusammenhang zwischen den beiden Variablen wurde beobachtet (<a href="#fig-mlm-prediction-poly-1" class="quarto-xref">Abbildung&nbsp;<span>21.1</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-prediction-poly-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-prediction-poly-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_prediction_files/figure-html/fig-mlm-prediction-poly-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-prediction-poly-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;21.1: Zusammenhang zwischen Ermüdung (Fatigue Index) und Wettkampfzeit (s) (adaptiert nach Pickett et al.&nbsp;(2021))
</figcaption>
</figure>
</div>
</div>
</div>
<p>Aus physiologischen Überlegungen heraus, haben die Autoren den Zusammenhang zwischen den beiden Variablen nicht nur mittels einer einfachen linearen Regression modelliert, sondern es wurde auch ein Polynom 2. Grades an die Daten angepasst (siehe Mathematische Grundlagen zu Polynomen). Dies resultierte in dem folgenden Modell (siehe <a href="#fig-mlm-prediction-poly-2" class="quarto-xref">Abbildung&nbsp;<span>21.2</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-prediction-poly-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-prediction-poly-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_prediction_files/figure-html/fig-mlm-prediction-poly-2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-prediction-poly-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;21.2: Modellzusammenhang zwischen Ermüdung (Fatigue Index) und Wettkampfzeit (s) mittels eines Polynoms 2. Grades (adaptiert nach Pickett et al.&nbsp;(2021))
</figcaption>
</figure>
</div>
</div>
</div>
<p>Dies führte zu der folgenden Modellformulierung:</p>
<p><span class="math display">\[\begin{equation*}
y_i = 89.8 - 6.99 \cdot x_i + 0.23 \cdot x_i^2
\end{equation*}\]</span></p>
<p>Die Prädiktorvariable <code>fatigue</code> ist nicht nur als linearer Faktor in das Modell eingegangen, sondern auch die quadrierten Terme wurden in das Modell integriert. Dies erlaubt die Modellierung eines parabelförmigen Zusammenhangs zwischen der Prädiktorvariablen <code>fatigue</code> und der abhängigen Variablen Zeit. Dieser Ansatz, dass nicht nur die Variable sondern auch ihre Potenzen im Modell verwendet werden, kann dabei beliebig erweitert werden. Die Grenze ist abhängig von der Anzahl der vorhandenen Datenpunkten. Bei einem Datensatz mit <span class="math inline">\(N\)</span> Datenpunkten hat das höchst mögliche Polynom den Grad <span class="math inline">\(N-1\)</span>. Dies ist natürlich in den seltensten Fällen sinnvoll, da beispielsweise im Beispiel mit <span class="math inline">\(N = 19\)</span> Datenpunkten die Interpretation eines Polynoms vom Grade <span class="math inline">\(18\)</span> relativ schwierig wird. Dieser Umstand wird später im Skript noch einmal aufgegriffen. Wenn eine Prädiktorvariablen derart transformiert in das Modell eingeht, dann wird oft von einer sogenannten <strong>Polynomregression</strong> gesprochen, wobei diese Begrifflichkeit nicht universell verwendet wird.</p>
<p>Die Polynomregression stellt somit eine Erweiterung der einfachen linearen Regression dar. Während die lineare Regression versucht, eine gerade Linie bzw. eine flache Ebene an die Daten anzupassen, erlaubt die Polynomregression gebogene Kurven bzw. Oberflächen an die Daten anzupassen. D.h. der Effekt ist ähnlich dessen der schon bei den Interaktionseffekten beobachtet wurde. Dies erlaubt wieder komplexere Zusammenhänge zwischen den Prädiktorvariablen <span class="math inline">\(X\)</span> und einer Kriteriumsvariable <span class="math inline">\(Y\)</span> zu modellieren. Entsprechend nutzt die Polynomregression anstatt nur <span class="math inline">\(Y = \beta_0 + \beta_1 X\)</span> , Modelle in Form von:</p>
<p><span class="math display">\[\begin{equation}
Y = \beta_0 + \beta_1 X + \beta_2 X^2 + \beta_3 X^3 + \dots + \beta_d X^d + \epsilon
\end{equation}\]</span></p>
<p>Die Variable <span class="math inline">\(d\)</span> bestimmt den <strong>Polynomgrad</strong> des Modells. Je höher der Grad, desto flexibler ist das Modell. Üblicherweise werden die niedrigeren Grade bis zum höchsten Polynomgrad im Modell beibehalten auch wenn diese nicht statistisch signifikant sind <span class="citation" data-cites="peixoto1987 peixoto1990">(<a href="references.html#ref-peixoto1987" role="doc-biblioref">Peixoto 1987</a>, <a href="references.html#ref-peixoto1990" role="doc-biblioref">1990</a>)</span>. Nur in begründeten Ausnahmefällen, beispielsweise aus theoretischen Überlegungen, sollten niedrigere Grade ausgeschlossen werden. Ein einfaches Beispiel wäre ein rein parabelförmiger Zusammenhang. Formal:</p>
<p><span class="math display">\[\begin{equation*}
y_i = \beta_0 + \beta_1 x_i + \beta_2 x_i^2 + \epsilon_i
\end{equation*}\]</span></p>
<p>Hier könnte beispielsweise auch das folgende Modell an die Daten angepasst werden.</p>
<p><span class="math display">\[\begin{equation*}
y_i = \beta_2 x_i^2 + \epsilon_i
\end{equation*}\]</span></p>
<p>Inhaltlich würde dies bedeuten, dass aus theoretischen Überlegungen davon auszugehen ist, dass die Parabel durch den Koordinatenpunkt <span class="math inline">\((0,0)\)</span> geht und dass in diesem Fall die <em>Steigung</em> im Punkte <span class="math inline">\((0,0), \beta_1 = 0\)</span> ist. Dies kann in bestimmten Fällen tatsächlich plausibel sein, wird aber in den meisten Fällen nur sehr schwer inhaltlich zu begründen sein. Daher ist praktisch immer die Anpassung des vollständigen Modell sinnvoller. Weiterhin ist es meistens auch sinnvoll ein einfacheres Modell gegenüber einen Modell mit hohem Polynomgrad zu bevorzugen. Aus numerischen Gründen ist es oft auch sinnvoll die Prädiktorvariablen zu zentrieren <span class="citation" data-cites="shacham1997 bradley1979">(<a href="references.html#ref-shacham1997" role="doc-biblioref">Shacham und Brauner 1997</a>; <a href="references.html#ref-bradley1979" role="doc-biblioref">Bradley und Srivastava 1979</a>)</span>.</p>
<p>Insgesamt ergibt sich durch die Erweiterungen die im Rahmen des multiplen Regression besprochen wurden dementsprechend ein extrem flexibler Ansatz um Zusammenhänge von Prädiktorvariablen mit einer abhängigen Kriteriumsvariable zu modellieren. Durch Interaktionseffekte, nominale Variablen und Polynome kann ein große Klasse von Zusammenhängen innerhalb des gleichen Ansatzes einheitlich behandelt werden. Damit kommen auch die bereits kennengelernten Methoden zum Einsatz um den Modellfit zu bewerten.</p>
<section id="polynomregression-in-r" class="level3" data-number="21.1.1">
<h3 data-number="21.1.1" class="anchored" data-anchor-id="polynomregression-in-r"><span class="header-section-number">21.1.1</span> Polynomregression in <code>R</code></h3>
<p>In <code>R</code> gibt es verschiedene Methoden eine Polynomregression durchzuführen, die aber alle mittels <code>lm()</code> durchgeführt werden. Im einfachsten Falle werden die höheren Polynome von <span class="math inline">\(X\)</span> direkt im <code>tibble</code> generiert. Seien zum Beispiel die folgenden Daten gegeben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">runif</span>(<span class="dv">10</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="dv">4</span> <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fl">0.5</span><span class="sc">*</span>x<span class="sc">**</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dann wäre eine mögliche Lösung zunächst die Polynome von <span class="math inline">\(X\)</span> direkt im Datensatz zu generieren und anschließend entsprechend in <code>lm()</code> in der Formel zu verwenden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df_add <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">x2 =</span> x<span class="sc">**</span><span class="dv">2</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mod_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> x2, df_add)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_1)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x + x2, data = df_add)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7030 -0.4729 -0.1269  0.7497  1.3360 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.3648     0.5182   6.493 0.000336 ***
x             1.9716     0.5585   3.530 0.009600 ** 
x2            2.4626     1.1188   2.201 0.063635 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.028 on 7 degrees of freedom
Multiple R-squared:  0.7601,    Adjusted R-squared:  0.6916 
F-statistic: 11.09 on 2 and 7 DF,  p-value: 0.006758</code></pre>
</div>
</div>
<p>Eine andere Möglichkeit ist ohne die Variablen vorher zu generieren, sondern direkt in <code>lm()</code> mittels der <code>I()</code>-Funktion. Somit wird das Polynom direkt beim Funktionsaufruf generiert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mod_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">**</span><span class="dv">2</span>), df)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_2)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x + I(x^2), data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7030 -0.4729 -0.1269  0.7497  1.3360 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.3648     0.5182   6.493 0.000336 ***
x             1.9716     0.5585   3.530 0.009600 ** 
I(x^2)        2.4626     1.1188   2.201 0.063635 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.028 on 7 degrees of freedom
Multiple R-squared:  0.7601,    Adjusted R-squared:  0.6916 
F-statistic: 11.09 on 2 and 7 DF,  p-value: 0.006758</code></pre>
</div>
</div>
<p>Eine weitere Möglichkeit besteht mittels der Funktion <code>poly()</code> im Formelaufruf von <code>lm()</code>. Für die Funktion <code>poly()</code> muss dann der Parameter <code>degree</code> angegeben werden um den Grad des Polynoms zu bestimmen. Dazu noch der Parameter <code>raw = TRUE</code> wenn <strong>keine</strong> orthogonalen Polynome erstellt werden sollen. Orthogonale Polynome haben den Vorteil, dass die Polynome voneinander unabhängig sind und keine Multikollinearitäten entstehen. Eine weitere Besprechung führt allerdings hier etwas zu weit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mod_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="at">degree=</span><span class="dv">2</span>, <span class="at">raw =</span> <span class="cn">TRUE</span>), df)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_3)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ poly(x, degree = 2, raw = TRUE), data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7030 -0.4729 -0.1269  0.7497  1.3360 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                        3.3648     0.5182   6.493 0.000336 ***
poly(x, degree = 2, raw = TRUE)1   1.9716     0.5585   3.530 0.009600 ** 
poly(x, degree = 2, raw = TRUE)2   2.4626     1.1188   2.201 0.063635 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.028 on 7 degrees of freedom
Multiple R-squared:  0.7601,    Adjusted R-squared:  0.6916 
F-statistic: 11.09 on 2 and 7 DF,  p-value: 0.006758</code></pre>
</div>
</div>
<p>Ein Vergleich der verschiedenen Outputs zeigt, dass alle drei Wege zum gleichen Ergebnis führen.</p>
</section>
</section>
<section id="vorhersage-versus-inferenz" class="level2" data-number="21.2">
<h2 data-number="21.2" class="anchored" data-anchor-id="vorhersage-versus-inferenz"><span class="header-section-number">21.2</span> Vorhersage versus Inferenz</h2>
<p>Regressionsmodelle können je nach Zielsetzung sehr unterschiedliche Zwecke erfüllen. Insbesondere muss zwischen Modellen um eine <em>Vorhersage</em> zu treffen und Modellen zur <em>Inferenz</em> unterschieden werden. D.h. es kommt darauf an, was mit dem Modell erreicht werden soll. Bei der Vorhersage ist von primären Interesse, wie gut das Modell neue, unbekannte Werte der Zielvariable prognostizieren kann. Ob die einzelnen Einflussgrößen (Prädiktoren) statistisch signifikant sind oder wie genau ihr Zusammenhang zur Zielgröße aussieht, ist dabei eher zweitrangig. Dagegen steht bei der Inferenz die <em>Erklärung</em> im Vordergrund. Welche Variablen haben einen Effekt, wie stark ist dieser und ist der Zusammenhang statistisch belegbar ist sind Fragestellung die hier das Hauptinteresse bilden <span class="citation" data-cites="breiman2001">(<a href="references.html#ref-breiman2001" role="doc-biblioref">Breiman 2001</a>)</span>.</p>
<p>In einem medizinischen Zusammenhang könnte beispielsweise ein Regressionsmodell verwendet werden, um vorherzusagen, wie hoch das Risiko eines Patienten für eine bestimmte Krankheit ist. Dazu wird ein Modell basierend auf den Prädiktorvariablen Alter, Gewicht, Blutdruck und möglichen weiteren Faktoren erstellt. Ein Modell zur Vorhersage würde hier möglicherweise viele Prädiktoren einbeziehen um die Risikoabschätzung möglichst genau vorherzusagen. Ein inferenzorientiertes Modell hingegen würde gezielt untersuchen, ob z.B. der Blutdruck statistisch signifikant mit dem Krankheitsrisiko zusammenhängt, mit dem Ziel, möglichst eine kausale Interpretation zu finden und beispielsweise klinischer Empfehlungen abzuleiten. D.h. bei der Inferenz ist die Interpretierbarkeit der Prädiktorvariablen von Bedeutung. Somit spielen auch Effekt wie Kollinearitäten eine bedeutsamere Rolle. Bei der Vorhersage ist dieses Problem dagegen möglicherweise von geringerer Bedeutung so lange die Vorhersagequalität nicht beeinträchtigt wird. In beiden Fällen ist dabei die Herleitung eines <em>wahren</em> Modells nicht eineindeutig. Ist das Modell <em>wahr</em>, dass zu besseren Vorhersagen führt, oder dasjenige, dass vor dem theoretischen Hintergrund eine Interpretation zulässt. Es wird hier auch von der Multiplizität der Modelle gesprochen <span class="citation" data-cites="breiman2001 carlin2023">(<a href="references.html#ref-breiman2001" role="doc-biblioref">Breiman 2001</a>; <a href="references.html#ref-carlin2023" role="doc-biblioref">Carlin und Moreno-Betancur 2023</a>)</span>.</p>
</section>
<section id="modellbewertung" class="level2" data-number="21.3">
<h2 data-number="21.3" class="anchored" data-anchor-id="modellbewertung"><span class="header-section-number">21.3</span> Modellbewertung</h2>
<p>Im weiteren, sei ein Vorhersagefokus gewählt. Eine zentrale Aufgabe bei der Erstellung eines Modells um Vorhersagen zu treffen ist die <strong>Modellbewertung</strong>. Die zentrale Frage ist dabei: “Wie gut ist das Modell in der Lage Daten vorherzusagen?” Insbesondere die Frage wie gut die Vorhersage des Modells ist, für Datenpunkte die es bisher <em>noch nicht gesehen</em> hat. In diesem Zusammenhang bedeutet <em>gesehen</em>, Datenpunkte die für die Erstellung des Modell verwendet wurden. D.h. die Aufgabe besteht darin, die Modellgüte zu bewerten, für Datenpunkte die eigentlich noch gar nicht vorhanden sind. Wenn ein Prädiktion für einen solchen <em>potential beobachtbaren</em> Wert getätigt wird, wie groß ist der zu erwartenden Fehler. Ein Stück weit ähnlich der Interpretation des Standardschätzfehlers. Im Rahmen der einfachen linearen Regression wurden bereits die beiden Parameter der Root-Mean-Square Fehler (<span class="math inline">\(RMSE\)</span>) <span class="math inline">\(\hat{sigma}^2\)</span>, der Standardschätzfehler, und der Determinationskoeffizienten <span class="math inline">\(R^2\)</span> behandelt. Im Weiteren wird zunächst <span class="math inline">\(RMSE\)</span> bzw. ohne Wurzel also der <span class="math inline">\(MSE\)</span> verwendet. Formal handelt es sich dabei um die gemittelte Summe der quadrierten Residuen.</p>
<p><span class="math display">\[\begin{equation*}
MSE = \frac{1}{N}\sum_{i=1}^N (\hat{y}_i - y_i)^2
\end{equation*}\]</span></p>
<p>Allgemein, umso kleiner der <span class="math inline">\(MSE\)</span> wird, umso besser kann das Modell die Daten vorhersagen. Daher erscheint es zunächst sinnvoll, dass Modell so zu wählen, dass die Daten möglichst perfekt abgebildet werden können. Allerdings ist zu bedenken, dass die Daten sich normalerweise aus zwei Komponenten zusammensetzen. Dem <em>tatsächlichen</em> Zusammenhang zwischen <span class="math inline">\(X\)</span> und <span class="math inline">\(Y\)</span> und noch einem zusätzlichen <strong>Rauschanteil</strong>. In den bisherigen Betrachtungen wurde dieser Rauschanteil bzw. zufällige Fehler immer mit Hilfe von <span class="math inline">\(\sigma_i\)</span> formalisiert. Allgemein, kann der Zusammenhang zwischen <span class="math inline">\(X\)</span> und <span class="math inline">\(Y\)</span> daher wie folgt dargestellt werden.</p>
<p><span class="math display">\[\begin{equation*}
Y = f(X) + \epsilon
\end{equation*}\]</span></p>
<p>Diese Schreibweise soll noch einmal betonten, dass ein funktionaler Zusammenhang zwischen <span class="math inline">\(Y\)</span> und <span class="math inline">\(X\)</span> besteht, formal <span class="math inline">\(f(X)\)</span> und dass der beobachtete Wert aber noch eine zusätzliche zufällige Komponente <span class="math inline">\(\epsilon\)</span> beinhaltet.</p>
<p>Was nun passieren kann, ist dass ein Modell gewählt wird, das die <strong>beobachteten</strong> Daten perfekt abbildet. D.h. für jeden <span class="math inline">\(X\)</span> wird genau der beobachtete <span class="math inline">\(Y\)</span>-Wert <em>vorhergesagt</em>, formal <span class="math inline">\(\hat{y}_i = y_i\)</span>. Die Daten sind aber mit Rauschen bzw. zufälligen Fehlern behaftet. Wenn das Modell nun die Daten perfekt nachbildet, dann wird ebenfalls der Rauschanteil abgebildet der aber eigentlich nicht berücksichtigt werden sollte. Dies führt dann dazu, das das Modell wenn es einen neuen Datenpunkt vorhersagen soll fehlerhafte Vorhersagewerten produziert. Dass Modell ist nicht in der Lage, zwischen dem systematischen Teil und dem Rauschteil zu unterschieden. Der Fachbegriff dafür nennt sich <strong>Überanpasung</strong> oder geläufiger englisch <strong>overfitting</strong>. Andersherum kann auch der gegenteilige Effekt auftreten, dass Modell kann unterkomplex sein, was ebenfalls dazu führt, das das Modell nicht in der Lage ist <em>gute</em> Vorhersage zu treffen. Hier wird von einer <strong>Unteranpassung</strong> bzw. <strong>underfitting</strong> gesprochen. Das folgende Beispiel stellt diese beiden Effekte da.</p>
<p>Angenommen der folgende DPG liegt den beobachteten Daten zugrunde.</p>
<p><span class="math display">\[\begin{equation*}
Y = 3 + 1.5 \cdot X^3 + \epsilon
\end{equation*}\]</span></p>
<p>Dabei soll der Rauschanteil <span class="math inline">\(\epsilon\)</span> einer Standardnormalverteilung <span class="math inline">\(\Phi\)</span> folgen. Es wurden die folgenden <span class="math inline">\(N = 7\)</span> Datenpunkte generiert (siehe <a href="#fig-mlm-prediction-over-1" class="quarto-xref">Abbildung&nbsp;<span>21.3</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-prediction-over-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-prediction-over-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_prediction_files/figure-html/fig-mlm-prediction-over-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-prediction-over-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;21.3: Beispieldaten mit Rauschen (Punkte) und der tatsächliche DPG
</figcaption>
</figure>
</div>
</div>
</div>
<p>Nun werden drei verschiedene Modelle an die Daten gefittet.</p>
<p><span class="math display">\[\begin{align*}
m_u: Y &amp;= \beta_0 + \beta_1 X \\
m_f: Y &amp;= \beta_0 + \beta_1 X^3 \\
m_o: Y &amp;= \beta_0 + \beta_1 X + \beta_2 X^2 + \ldots + \beta_6 X^6
\end{align*}\]</span></p>
<p>Das Modell <span class="math inline">\(m_u\)</span> ist ein einfaches lineares Regressionsmodell, während <span class="math inline">\(m_f\)</span> und <span class="math inline">\(m_o\)</span> Polynome sind. <span class="math inline">\(m_f\)</span> ist dabei ein Polynom dritten Grades, dass dem tatsächlichen DPG entspricht während <span class="math inline">\(m_o\)</span> ein Polynom <span class="math inline">\(6.\)</span> Grades ist, dass deutlich komplexer als der DPG ist. Wenn nun diese drei Modelle an die Daten angepasst werden, resultieren daraus die folgenden Graphen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-prediction-over-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-prediction-over-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_prediction_files/figure-html/fig-mlm-prediction-over-2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-prediction-over-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;21.4: Anpassung der drei Modell an die Beispieldaten.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Es ist zu sehen, das das Modell <span class="math inline">\(m_u\)</span> nur sehr schlecht in der Lage ist, den beobachteten Datenpunkten <span class="math inline">\(y_i\)</span> bzw. dem tatsächlichen DPG zu folgen. Das Modell kann nur eine Gerade generieren und diese ist nicht ausreichend um den DGP nachzubilden. Wie erwartet ist das Modell <span class="math inline">\(m_f\)</span> dagegen sehr gut in der Lage den tatsächlichen DPG anhand der Daten zu reproduzieren. Dabei ist ist zu beobachten, das das Modell nicht perfekt durch die beobachteten Datenpunkte geht. D.h. das Modell ist in der Lage den systematischen und den Fehlerteil in den Daten voneinander zu trennen. Insbesondere wenn die Kurven rechts außerhalb des Bereichs der Daten verglichen werden, ist klar zu erkennen, dass nur das Modell <span class="math inline">\(m_f\)</span> dem tatsächlichen DPG nachbildet. Dabei ist hier auch ein leichter Unterschied zu erkennen, der daraus folgt, dass eben keine perfekten Information anhand der Datenpunkt zur Verfügung standen. Das Modell <span class="math inline">\(m_o\)</span> dagegen ist zwar in der Lage die beobachteten Daten perfekt abzubilden. Die Kurve geht genau durch alle Punkte hindurch aber weicht dadurch auch vom DGP ab. Dies ist wieder besonders stark im rechten Teil, außerhalb der Datenpunkte, zu beobachten. Zusammengefasst ist es also wichtig ein Modell zu verwenden, das der Komplexität des DGPs entspricht damit es weder zu einer Über- noch zu einer Unteranpassung kommt.</p>
<p>Aus diesen Betrachtungen ergeben sich die folgenden Definitionen.</p>
<div id="def-overfitting" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 21.1 (Überanpassung (over-fitting) )</strong></span> Eine Überanpassung liegt vor, wenn ein Modell die Details und das Rauschen in den Trainingsdaten in einem Maße erlernt, das seine Fähigkeit zur Generalisierung auf neue, ungesehene Daten beeinträchtigt. Das Modell wird zu komplex und passt sich zu sehr an die Trainingsdaten an, statt an den zugrunde liegenden datenerzeugenden Prozess.</p>
</div>
<div id="def-underfitting" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 21.2 (Unteranpassung (under-ftting) )</strong></span> Eine Unteranpassung liegt vor, wenn ein Modell zu eine zu geringe Komplexität aufweise, um den zugrunde liegende datengeneriereden Prozess zu erlernen. Das Modell lernt nicht effektiv aus den Trainingsdaten, was zu einer schlechten Leistung führt.</p>
</div>
<p>Prinzipiell ist es schwierig zu entscheiden ob eine Über- oder Unteranpassung vorliegt. Wie bereits im vorhergehenden Kapitel zu Modellhierarchien wird der Standardschätzfehler immer kleiner umso mehr Prädiktorvariablen in das Modell integriert werden. D.h. wenn das Modell immer komplexer wird. Dazu kommen noch die vorgestellten Möglichkeiten von Interaktionseffekten und Polynomen dazu. Im Falle des Beispiels, mit <span class="math inline">\(m_u\)</span>, wo ein Polynom 6. Grades gefittet wurde, sind die beobachteten Daten perfekt abgebildet worden und die Interpretation von overfitting war nur möglich weil der DGP bekannt war. Um dennoch eine Abschätzung treffen zu können wie gut das Modell <strong>generalisiert</strong>, also für Datenpunkte funktioniert die noch nicht bekannt ist wird in der Praxis ein Validierungsansatz verwendet, die im folgenden vorgestellt wird.</p>
</section>
<section id="validierungsansatz" class="level2" data-number="21.4">
<h2 data-number="21.4" class="anchored" data-anchor-id="validierungsansatz"><span class="header-section-number">21.4</span> Validierungsansatz</h2>
<p>Wenn ein Modell zur Prädiktion erstellt werden soll, dann ist das primäre Ziel die Zielvariable mit Hilfe der Prädiktoren möglichst präzise vorherzusagen. Dazu ist es notwendig die Generalisierbarkeit des Modells abschätzen zu können. Es reicht nicht zu wissen wie gut das Modell die zur Modellanpassung verwendeten Daten vorhersagt, sondern es sollte ein Einschätzung gemacht werden wie gut <em>neue</em> Daten vorhergesagt werden können. Ein Ansatz dieses Problem zu lösen besteht darin eine Partitionierung, eine Unterteilung, der verfügbaren Daten in verschiedene Teilmengen vorzunehmen.</p>
<p>Unter der Partitionierung wird der Datensatz in einen <strong>Trainings-</strong> und einen <strong>Testdatensatz</strong> unterteilt. Das Modell wird dann zunächst mit Hilfe der Trainingsdaten erstellt. Die Testdaten spielen bei der Erstellung des Modells hingegen keine Rolle und werden <strong>zurückgehalten</strong>. Nachdem das Modell erstellt wurde, werden dann die Trainingsdaten verwendet, um zu überprüfen, wie gut das Modell neue, unbekannte Daten abbildet. Dadurch kann beurteilt werden, ob das Modell gut generalisiert. Die Aufteilung der Daten hilft daher zu entscheiden bzw. zu bewerten wir gut das Modell den DGP in der Lage ist abzubilden. Entsprechend der Unterteilungen kann ein <strong>Testfehler</strong> und ein <strong>Trainingsfehler</strong> für das Modell bestimmt werden. Der Trainingsfehler unterscheidet sich häufig deutlich von Testfehler indem er deutlich kleiner ist.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-pred-valid-01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-pred-valid-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_prediction_files/figure-html/fig-mlm-pred-valid-01-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-pred-valid-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;21.5: Validierungsansatz anhand eines einfachen Beispiels mit <span class="math inline">\(N=30\)</span> Datenpunkten.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-mlm-pred-valid-01" class="quarto-xref">Abbildung&nbsp;<span>21.5</span></a> ist der Validierungsansatz schematisch anhand eines Beispiels mit <span class="math inline">\(N = 30\)</span> Datenpunkten dargestellt. Die Datenpunkte werden zufällig nach einem bestimmten Verhältnis in Test- und Trainingsdatensatz unterteilt. Ein typisches Verhältnis ist <span class="math inline">\(80/20\)</span>, mit <span class="math inline">\(80\)</span>% im Trainingsdatensatz.</p>
<div id="def-traininerror" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 21.3 (Trainingsfehler )</strong></span> Der Trainingsfehler ist der durchschnittliche Fehler, der entsteht, wenn eine statistische Lernmethode auf genau die Beobachtungen angewendet wird, die auch zum Trainieren des Modells genutzt wurden.</p>
</div>
<div id="def-testerror" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 21.4 (Testfehler )</strong></span> Der Testfehler ist der durchschnittliche Fehler, der entsteht, wenn eine statistische Lernmethode verwendet wird, um die Kriteriumsvariable für eine neue Beobachtung vorherzusagen. Eine <em>neue Beobachtung</em> ist ein Datenpunkt, der <strong>nicht</strong> zum Training des Modells verwendet wurde.</p>
</div>
<p>In der Terminologie der beiden Definition wird von statistischen Lernmethoden gesprochen. Dies ist ein Folge davon, dass dieser Validierungsansatz vor allem in der Informatik entwickelt wurde und dort generell verwendet geht, wenn es darum geht Methoden des maschinellen Lernens (engl. machine learning) zu bewerten. Das lineare Modell ist fällt dabei ebenfalls in die Klasse der machine learning Modelle ähnlich wie dies für Neuronale Netze und weitere Verfahren der Fall ist.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-prediction-testtrain" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-prediction-testtrain-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_prediction_files/figure-html/fig-mlm-prediction-testtrain-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-prediction-testtrain-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;21.6: Trainings- und Testfehler in Abhängigkeit vom Modellkomplexität
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-mlm-prediction-testtrain" class="quarto-xref">Abbildung&nbsp;<span>21.6</span></a> ist ein stilisierter Zusammenhang zwischen dem Test- und dem Trainingsfehler in Abhängigkeit von der Modellkomplexität abgetragen. Es ist zu erkennen, dass der Trainingsfehler immer niedriger als der Testfehler ist und mit zunehmender Modellkomplexität immer weiter abnimmt. Das beruht auf dem Effekt der schon im Zusammenhang mit Modellhierarchien besprochen wurde, dass die Hinzunahme von zusätzlichen Variablen, selbst wenn diese keinen Zusammenhang mit <span class="math inline">\(Y\)</span> besitzen, die Modellanpassung mindestens gleich gut bleibt. Die wichtige Einsicht ist allerdings der Zusammenhang des Testfehlers mit der Modellkomplexität. Hier ist ebenfalls zunächst eine Abnahme des Fehler zu beobachten bis zum erreichen eines Minimums. Danach nimmt ab einer bestimmten Modellkomplexität der Testfehler wieder zu. Dieser verlauf beruht darauf, das das Modell zunächst zu wenig Komplexität besitzt und entsprechend eine Unteranpassung stattfindet. Mit der Erhöhung der Modellkomplexität erreicht das Modell einen Punkt, an dem die Komplexität derjenigen des DGPs entspricht. Nimmt nun die Komplexität noch weiter zu, kommt es dann allerdings zu einer Überanpassung. D.h. das Modell wird immer spezifischer auf die Trainingsdaten trainiert bzw. das Modell fängt an auch das Rauschen in den Daten aufzunehmen. Dadurch verliert das Modell zunehmend die Fähigkeit zur Generalisierbarkeit. Mit dem Validierungsansatz ist es somit möglich den Bereich der <em>optimalen</em> Modellkomplexität abzuschätzen. Ehrlicherweise sollte allerdings erwähnt werden, dass in der Praxis die Kurven nicht immer diesen Verlauf zeigen, sondern dies sehr stark von den Modell, den Daten und dem Rauschen in den Daten abhängt.</p>
<p>Die Aufteilung der Daten in Trainings- und Test- bzw. Validierungsdatensatz bringt einen inhärenten Kompromiss mit sich. Eine größere Menge an Trainingsdaten könnte potenziell die Genauigkeit des Modells auf diesen Daten verbessern. Gleichzeitig kann eine kleinere Validierungsmenge zu einer weniger zuverlässigen Einschätzung der Generalisierungsfähigkeit führen. Es ist daher ein grundlegendes Dilemma, dass die Menge an Daten, die zum Trainieren des Modells verwendet wird, dessen Fähigkeit beeinflusst, komplexe Muster zu erlernen und auf neue Daten anzuwenden. Ist der Validierungsdatensatz zu klein, sind die darauf berechneten Leistungsmetriken möglicherweise zu verrauscht oder nicht repräsentativ für die tatsächliche Fähigkeit des Modells, auf völlig neue Daten zu generalisieren. Dieses Problem sollte bei der Anwendung des Validierungsdatensatzansatzes berücksichtigt werden und kann letztendlich auch nur wieder durch Domänenexpertise abgewägt werden.</p>
<p>Ein weiteres Problem ergibt sich, wenn der Validierungsdatensatz <em>schlecht</em> gewählt wurde. Dies bedeutet, dass der Trainingsdatensatz möglicherweise nicht genau die Verteilung zukünftiger, unbekannter Daten widerspiegelt. Dies kann in der Folge zu irreführenden, meist zu optimischen, Leistungsschätzungen des Modells führen. Enthält der Validierungsdatensatz beispielsweise Datenpunkte, die sich erheblich von den Daten unterscheiden, auf die das Modell in realen Anwendungen angewendet wird, so ist die Leistung des Modells auf dem Validierungsdatensatz möglicherweise kein guter Indikator für die tatsächliche Leistungsfähigkeit. Wenn beispielsweise die Trainingsdaten hauptsächlich Daten einer bestimmten demografischen Gruppe enthalten und der Validierungsdatensatz hauptsächlich Daten einer anderen Gruppe enthält, könnte die Bewertung verzerrt sein.</p>
<p>Der Validierungsdatensatzansatz bietet somit sowohl Vorteile als auch Nachteile, die bei der Anwendung berücksichtigt werden müssen. Die Vorteile liegen zunächst in der konzeptionellen Einfachheit des Ansatzes und in seiner einfache Implementierung. Der Hauptnachteil liegt in der Sensitivität gegenüber der Datenaufteilung. Insbesondere bei kleinen Datensätzen können die Datensätze leicht zu fehlerhaften Einschätzungen kommen, und Variationen in der Aufteilung können zu stark unterschiedlichen Leistungsschätzungen führen. Die Reduktion der Trainingsdaten kann dazu führen, dass die Gesamtleistung des Modells beeinträchtigt wird, insbesondere wenn der Datensatz begrenzt ist. Bei sehr großen Datensätzen ist die Reduzierung der Trainingsdaten durch einen angemessen großen Validierungsdatensatz möglicherweise vernachlässigbar. Mit der zunehmenden Größe der zu untersuchenden Datensätzen in den Sportwissenschaften, findet der Validierungsansatz in den letzten Jahren zunehmend mehr Anwendung.</p>
<section id="validierungsansatz-in-r" class="level3" data-number="21.4.1">
<h3 data-number="21.4.1" class="anchored" data-anchor-id="validierungsansatz-in-r"><span class="header-section-number">21.4.1</span> Validierungsansatz in <code>R</code></h3>
<p>Der Validierungsansatz kann relativ einfach direkt in <code>R</code> programmiert werden. Beispielhaft wird dazu ein Datensatz aus <span class="citation" data-cites="ponce2025">Ponce-Garcı́a u.&nbsp;a. (<a href="references.html#ref-ponce2025" role="doc-biblioref">2025</a>)</span> verwendet. Es soll die peak power (PP, in Watt) beim Wingate-Test mittels der PP beim Repeated jump test (<code>RJP</code>), PP beim Anaerobic squat test (<code>AST</code>), des Geschlechts, dem Alter und der Muskelmasse (<code>MM</code>, in Kg) bei <span class="math inline">\(N = 48\)</span> CrossFit Athletinnen und Athleten vorhergesagt werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ponce <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_xlsx</span>(<span class="st">'data/ponce_data_edited.xlsx'</span>, <span class="at">sheet=</span><span class="st">'data'</span>) <span class="sc">|&gt;</span> tidyr<span class="sc">::</span><span class="fu">drop_na</span>()</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ponce)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  IDENTIFIER1   AGE SEX   MM_kg WG_PP_W RJT_PP_W AST_PP_W
  &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 CFT22-101      29 male   46      938.    1086.    1415.
2 CFT22-102      31 male   45.2   1035     1259.    1209.
3 CFT22-103      30 male   33.6    703.    1209.     963.
4 CFT22-104      29 male   45.2    951.    1289.    1787.
5 CFT22-105      28 male   39.3    905.    1070.    1384.
6 CFT22-106      45 male   38      883.    1059.    1247.</code></pre>
</div>
</div>
<p>Zunächst wird der Datensatz in Test- und Traindatensatz unterteilt. Es wird ein zufälliger <span class="math inline">\(80/20\)</span> Split vorgenommen. D.h. <span class="math inline">\(80\)</span>% der Daten werden zum trainieren verwendet und <span class="math inline">\(20\)</span>% zum testen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>no_cases <span class="ot">&lt;-</span> <span class="fu">dim</span>(ponce)[<span class="dv">1</span>]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>train_id <span class="ot">&lt;-</span> <span class="fu">sample</span>(no_cases, <span class="fu">ceiling</span>(no_cases <span class="sc">*</span> <span class="fl">0.8</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>test_id <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="dv">1</span><span class="sc">:</span>no_cases, train_id)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>ponce_train <span class="ot">&lt;-</span> ponce[train_id,]</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>ponce_test <span class="ot">&lt;-</span> ponce[test_id,]</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Als nächstes wird das Modell auf dem Trainingsdatensatz angepasst (trainiert).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mod_train <span class="ot">&lt;-</span> <span class="fu">lm</span>(WG_PP_W <span class="sc">~</span> SEX <span class="sc">+</span> AGE <span class="sc">+</span> MM_kg <span class="sc">+</span> RJT_PP_W <span class="sc">+</span> AST_PP_W, ponce_train)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_train)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = WG_PP_W ~ SEX + AGE + MM_kg + RJT_PP_W + AST_PP_W, 
    data = ponce_train)

Residuals:
     Min       1Q   Median       3Q      Max 
-129.113  -33.766    3.074   27.885  122.640 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -196.30833  138.29099  -1.420  0.16512   
SEXmale       22.76171   58.47823   0.389  0.69960   
AGE            1.33300    1.82700   0.730  0.47078   
MM_kg         13.66546    4.42912   3.085  0.00410 **
RJT_PP_W       0.16393    0.09942   1.649  0.10868   
AST_PP_W       0.18241    0.06005   3.038  0.00463 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 66.85 on 33 degrees of freedom
Multiple R-squared:  0.9242,    Adjusted R-squared:  0.9127 
F-statistic: 80.48 on 5 and 33 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Im nächsten Schritt werden der Vorhersagefehler <span class="math inline">\(MSE\)</span> bestimmt. Da die Zahlen relativ groß und somit unhandlich sind, wird nun dochh wieder der <span class="math inline">\(RMSE\)</span> verwendet, also die Wurzel aus <span class="math inline">\(MSE\)</span>. Für den Trainingsfehler können dazu direkt die Residuen <span class="math inline">\(\epsilon_i\)</span> über die Funktion <code>resid()</code> verwendet werden. Für den Testfehler, müssen zunächst die Werte <span class="math inline">\(\hat{y}_i\)</span> mittels des Modells vorhergesagt werden und anschließend die Abweichungen von den beobachteten Werten <span class="math inline">\(y_i\)</span> berechnet werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>RMSE_train <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(<span class="fu">sum</span>(<span class="fu">resid</span>(mod_train)<span class="sc">**</span><span class="dv">2</span>)))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>RMSE_test <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(<span class="fu">sum</span>((ponce_test<span class="sc">$</span>WG_PP_W <span class="sc">-</span> <span class="fu">predict</span>(mod_train, <span class="at">newdata=</span>ponce_test))<span class="sc">**</span><span class="dv">2</span>)))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">c</span>(RMSE_train, RMSE_test))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19.59641 20.22469</code></pre>
</div>
</div>
<p>Im Vergleich ist zu beobachten, dass der Testfehler wie erwartet über dem des Trainingsfehlers liegt. Allerdings ist in diesem Beispiel der Unterschied nicht allzu groß.</p>
</section>
<section id="k-fache-kreuzvalidierung" class="level3" data-number="21.4.2">
<h3 data-number="21.4.2" class="anchored" data-anchor-id="k-fache-kreuzvalidierung"><span class="header-section-number">21.4.2</span> K-fache Kreuzvalidierung</h3>
<p>Um die Einschränkungen des einzelnen Validierungsdatensatzansatzes, insbesondere die Sensitivität gegenüber der Datenaufteilung, zu adressieren, wird in der Praxis häufig eine Variante, die Kreuzvalidierung, eingesetzt. Bei der k-fachen Kreuzvalidierung wird der Datensatz in <span class="math inline">\(k\)</span> gleich große Teile (sogenannte Folds) aufgeteilt. Das Modell wird dann <span class="math inline">\(k\)</span>-mal trainiert und bewertet. In jeder Iteration wird ein anderer Fold als Validierungsdatensatz verwendet, während die übrigen <span class="math inline">\(k-1\)</span> Folds als Trainingsdatensatz dienen. Die endgültige Leistungsschätzung wird durch Mittelung der Ergebnisse über alle <span class="math inline">\(k\)</span> Validierungsdurchläufe hinweg ermittelt. Die Kreuzvalidierung bietet daher eine robustere Schätzung der Modellleistung, da sie die Ergebnisse über mehrere verschiedene Datenaufteilungen hinweg berücksichtigt. Insbesondere bei begrenzten Datenmengen ist die Kreuzvalidierung hilfreich und findet oft verwendet.</p>
<p>Ein Kochbuchansatz zur Kreuzvalidierung hat die folgenden <em>Zutaten</em></p>
<ul>
<li>Seien die <span class="math inline">\(K\)</span> folds <span class="math inline">\(C_1, C_2, \ldots, C_K\)</span> mit jeweils <span class="math inline">\(n_k = n/K\)</span> Beobachtungen in jedem Fold</li>
<li>Für jeden Fold wird <span class="math inline">\(CV_{(K)} = \sum_{i=1}^K \frac{n_k}{n}MSE_k\)</span> berechnet</li>
</ul>
<p>In <a href="#fig-mlm-pred-crossvalid-01" class="quarto-xref">Abbildung&nbsp;<span>21.7</span></a> ist beispielhaft die Kreuzvalidierung wieder mit <span class="math inline">\(N = 30\)</span> Datenpunkten und <span class="math inline">\(k = 5\)</span> folds dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-pred-crossvalid-01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-pred-crossvalid-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_prediction_files/figure-html/fig-mlm-pred-crossvalid-01-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-pred-crossvalid-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;21.7: Schematische Darstellung der Kreuzvalidierung mit <span class="math inline">\(N=30\)</span> Datenpunkten und <span class="math inline">\(k=5\)</span> folds.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Die Datenpunkte werden werden so unterteilt, dass jeder Datenpunkt in einem fold im Testdatensatz enthalten ist.</p>
<p>Im Spezialfall dass <span class="math inline">\(K = n\)</span> gilt, dann wird aus der Kreuzvalidierung eine sogenannte <strong>leave-one out cross-validation (LOOCV)</strong>. Konzeptionell ist dieser Ansatz ähnlich den Einflussmetriken, die im Rahmen der Bewertungs des Modellsfits bei der einfachen linearen Regression eingeführt wurden.</p>
<p>Die Kreuzvalidierung ist daher in der Durchführung ebenfalls relativ einfach umzusetzen. Bei großen Datensätzen mit sehr komplizierten Modellen kann es lediglich zum Problem kommen, dass die Rechenzeiten zu lang werden. Dies ist im Rahmen der hier besprochenen Probleme allerdings eher nicht zu erwarten. In manchen Fällen wird auch eine Kombination aus Validierung und Kreuzvalidierung verwendet. Dazu wird zunächst ein Teil des Datensatzes zur Validierung beseite gelegt. Anschließend wird das Modell mittels der Kreuzvalidierung auf den Trainingsdatensatz bestimmt. Die Kreuzvalidierung wird dabei vor allem zur Modellselektion verwendet. D.h. es wird der Fehler für verschiedene Modelle verglichen um ein <em>bestes</em> Modell zu bestimmen. Anschließend wird die Modellleistung dann auf dem Validierungsdatensatz abgeschätzt.</p>
<p>Eine wichtige Frage, für die es leider keine <em>golden bullet</em> Antwort gibt, ist die Anzahl <span class="math inline">\(k\)</span> der folds. Tatsächlich gibt es dazu keine genauen Regeln sondern in der Praxis werden je nach der Größe des Datensatzes meist <span class="math inline">\(5\)</span> bzw. <span class="math inline">\(10\)</span> Fold gebildet.</p>
</section>
<section id="k-fache-kreuzvalidierung-in-r" class="level3" data-number="21.4.3">
<h3 data-number="21.4.3" class="anchored" data-anchor-id="k-fache-kreuzvalidierung-in-r"><span class="header-section-number">21.4.3</span> K-fache Kreuzvalidierung in <code>R</code></h3>
<p>In <code>R</code> wird die Kreuzvalidierung am einfachsten mittels Hilfsfunktionen aus dem Package <code>caret</code> durchgeführt. Die Analyse setzt sich aus mehreren aufeinanderfolgenden Schritten zusammen. Zunächst wird mittels der Funktion <code>trainControl()</code> ein Objekt erstellt, welches die Kreuzvalidierung steuert. Mittels des Parameters <code>number</code> wird die Anzahl der folds bestimmt. Im Beispiel werden <span class="math inline">\(5\)</span> folds verwendet, da der Datensatz nicht übermäßig groß ist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>five_fold_cv <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">5</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Die Funktion <code>trainControl()</code> erstellt im Grunde genommen nur eine Liste mit den nötigen Information um eine $5-fache Kreuzvalidierung durchzuführen. Anschließend erfolgt die eigentlich Anpassung des Modells an die Daten, bzw. das Modell wird <em>trainiert</em>. Dazu wird die Funktion <code>train()</code> verwendet. Als erster Parameter wird die Modellformulierung an <code>train()</code> übergeben, wie das schon bei <code>lm()</code> der Fall ist. Damit auch tatsächlich ein lineares Modell verwendet wird, muss der Parameter <code>method</code> verwendet werden. <code>method</code> bestimmt welche Art von Modell an die Daten angepasst werden soll. Im vorliegenden Fall wird dementsprechend der Wert <code>"lm"</code> übergeben. Damit die Kreuzvalidierung durchgeführt wird, muss dass zuvor <code>trainControl()</code> erstellte Objekt an <code>train()</code> über den Parameter <code>trControl</code> übergeben werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mod_cv <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">train</span>(WG_PP_W <span class="sc">~</span> SEX <span class="sc">+</span> AGE <span class="sc">+</span> MM_kg <span class="sc">+</span> RJT_PP_W <span class="sc">+</span> AST_PP_W,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> ponce,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">method =</span> <span class="st">"lm"</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">trControl =</span> five_fold_cv)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>train()</code> führt nun die Anpassung der Modelle an die Daten durch. Die <code>summary()</code>-Funktion gibt nun wieder das Modell, zurück bei dem alle Daten benutzt wurden um das Modell anzupassen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_cv)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = .outcome ~ ., data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-126.884  -59.745   -4.335   33.722  285.735 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  48.44525  149.12628   0.325   0.7469  
SEXmale     124.33644   59.51229   2.089   0.0428 *
AGE          -1.59072    1.98223  -0.802   0.4268  
MM_kg        11.51097    4.80976   2.393   0.0212 *
RJT_PP_W      0.08184    0.11517   0.711   0.4813  
AST_PP_W      0.14399    0.06882   2.092   0.0425 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 82.36 on 42 degrees of freedom
Multiple R-squared:  0.8822,    Adjusted R-squared:  0.8682 
F-statistic: 62.89 on 5 and 42 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Die Ergebnisse der Kreuzvalidierung können über Teilelemente extrahiert werden. Über den Eintrag <code>results</code> werden die deskriptiven Werte herausgegeben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mod_cv<span class="sc">$</span>results</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  intercept     RMSE  Rsquared      MAE   RMSESD RsquaredSD    MAESD
1      TRUE 98.18535 0.8634339 71.97096 27.88672 0.09883944 12.16068</code></pre>
</div>
</div>
<p>Mit dem Eintrag <code>resample</code> werden die Ergebnisse der einzelnen Durchgänge ausgegeben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mod_cv<span class="sc">$</span>resample</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       RMSE  Rsquared      MAE Resample
1  68.39094 0.9127275 54.76668    Fold1
2 121.21414 0.8423183 79.90121    Fold2
3  89.87863 0.9714951 76.14900    Fold3
4 133.19928 0.7080119 84.57411    Fold4
5  78.24377 0.8826169 64.46380    Fold5</code></pre>
</div>
</div>
<p>Anhand der Ergebnisse ist der mittlere Fehler <span class="math inline">\(98.2\)</span> Watt mit einem Standardfehler von <span class="math inline">\(27.9\)</span> Watt zu beobachten.</p>
</section>
</section>
<section id="bias-variance-trade-off" class="level2" data-number="21.5">
<h2 data-number="21.5" class="anchored" data-anchor-id="bias-variance-trade-off"><span class="header-section-number">21.5</span> Bias-Variance Trade-off</h2>
<p>Das grundsätzliche Problem der Modellselektion, d.h. für einen gegebenen Datensatz ein <em>passendes</em> Modell zu finden geht zurück auf den sogenannten <strong>Bias-Variance Trade-off</strong>. Der Bias-Variance Trade-off beschreibt das Verhältnis zwischen der Komplexität eines Modells und seiner Vorhersagegenauigkeit sowohl auf den Trainingsdaten als auch auf neuen, ungesehenen Daten. Formal folgt der Bias-Variance Trade-off aus der folgenden Gleichung.</p>
<p><span class="math display">\[\begin{equation}
E(y_0 - \hat{f}(x_0))^2 = \text{Var}(\hat{f}{x_0}) + [\text{Bias}(\hat{f}(x_0))]^2 + \text{Var}(\epsilon)
\label{eq-bias-variance-trade}
\end{equation}\]</span></p>
<p>Hierbei ist <span class="math inline">\(E((y_0 - \hat{f}(x_0))^2\)</span> der zu erwartete MSE, d.h. der mittlere Fehler auf den <strong>Testdaten</strong> wenn die Funktion <span class="math inline">\(f\)</span> wiederholt auf großen Trainingsdatensätzen abgeschätzt werden würde und jedes Mal der Fehler für den Datenpunkt <span class="math inline">\(x_0\)</span> bestimmt worden wäre. Dieser mittlere Fehler setzt sich zusammen aus drei Komponenten. <span class="math inline">\(\text{Var}(\hat{f}{x_0})\)</span> ist die Varianz der geschätzten <span class="math inline">\(\hat{f}\)</span>, also der unterschiedlichen Modelle, wenn unterschiedliche Testdatensätze verwendet werden würde. Jedes Mal, wenn ein Modell an Daten angepasst wird und sich die Daten verändern, dann ändert sich auch das angepasste Modell. Im Fall der einfachen linearen Regression würde es zu einer Streuung der <span class="math inline">\(\beta_0\)</span>s und <span class="math inline">\(\beta_1\)</span>s kommen. Diese <em>Streuung</em> der Modelle ist mit Varianz gemeint. Im Idealfall sollten die Modelle nicht allzu stark schwanken und diese Komponente wäre entsprechend klein. Die zweite Komponente <span class="math inline">\([\text{Bias}(\hat{f}(x_0))]^2\)</span> beschreibt den sogenannten <strong>Bias</strong>. Der Bias entsteht dadurch, dass ein Prozess aus der <em>realen</em> Welt mit Hilfe eines Modell abgeschätzt werden soll, welches in den allermeisten Fällen auf Grund von vereinfachenden Annahmen bestimmt wird. Diese Unteranpassung führt ebenfalls zu einem Fehler. Die wenigsten Prozesse in der Natur werden <em>perfekt</em> einem linearem Modell entsprechen, dies führt zu einem <em>systematischen</em> Fehler der mittels des Bias bestimmt wird. Mathematisch lässt sich der Bias als die Differenz zwischen der durchschnittlichen Vorhersage <span class="math inline">\(\bar{\hat{y}}_i\)</span> des Modells und dem wahren Wert bestimmen <span class="math inline">\(y_i\)</span>. Die letzte Komponente <span class="math inline">\(\text{Var}(\epsilon)\)</span> stellt die unbekannte, zufällige Komponente des Modells, das Rauschen in den Daten, dar. Da alle drei Komponenten positiv sind, daraus folgt, dass die Vorhersagegenauigkeit niemals unterhalb der Rauschkomponente liegen kann.</p>
<p>Die <em>Kunst</em> besteht nun darin ein Modell zu finden, dass die beiden Komponenten Varianz und Bias gegeneinander optimiert. Üblicherweise führt eine Erhöhung der Modellkomplexität zu einer Verringerung des Bias aber zu einer Erhöhung der Varianz. Andersherum führt eine Erniedrigung der Modellkomplexität zu einer Verringerung der Varianz gepaart mit einer Erhöhung des Bias. Daher kommt es zu einem Trade-off zwischen diesen beiden Tendenzen. Dies muss aber nicht immer so sein und hängt sehr stark von dem jeweiligen Prozess und den Daten ab.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-pred-varbias-trade" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-pred-varbias-trade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_prediction_files/figure-html/fig-mlm-pred-varbias-trade-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-pred-varbias-trade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;21.8: Stilisierter Zusammenhang zwischen MSE, Bias, Varianz und <span class="math inline">\(\sigma^2\)</span> (schwarze, unterbrochene Linie)
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-mlm-pred-varbias-trade" class="quarto-xref">Abbildung&nbsp;<span>21.8</span></a> ist ein hypothetischer Zusammenhang zwischen MSE, der Varianz, dem Bias und <span class="math inline">\(\sigma^2\)</span> abgebildet. Hier ist zu erkennen, dass der resultierende Fehler MSE niemals unterhalb der Rauschgrenze liegen kann. Weiterhin setzt sich der Gesamtfehler über den angegebenen Modellkomplexitätsbereich jeweils aus verschieden starken Anteil der Varianz und dem Bias zusammen. Die genaue Ausprägung zwischen den Komponenten hängt aber stark von dem jeweiligen Problem ab. So ist es durchaus möglich, dass der Bias über den gesamten Bereich eher niedrig ist und somit der Gesamtfehler von der Varianz dominiert wird. Der Validierungsansatz bietet hier die Möglichkeit eine Abschätzung über diese Zusammenhänge zu erhalten und somit ein möglichst gutes Modell zu erhalten.</p>
</section>
<section id="zum-nach--und-weiterlesen" class="level2" data-number="21.6">
<h2 data-number="21.6" class="anchored" data-anchor-id="zum-nach--und-weiterlesen"><span class="header-section-number">21.6</span> Zum Nach- und Weiterlesen</h2>
<p>Ein extrem gutes Buch ist <span class="citation" data-cites="james2023">James u.&nbsp;a. (<a href="references.html#ref-james2023" role="doc-biblioref">2023</a>)</span> das mit dem Vorwissen aus diesem Skript direkt gelesen werden kann. Das Buch gibt es als <code>R</code> und <code>Python</code>-Versionen. Ein wichtige Hintergrundartikel ist <span class="citation" data-cites="breiman2001">Breiman (<a href="references.html#ref-breiman2001" role="doc-biblioref">2001</a>)</span> der die beiden Traditionen Statistik und Informatik gegenüberstellt. Ein guter Artikel zum Problem der Idee eines <em>optimalen</em> Modells ist <span class="citation" data-cites="westreich2013">Westreich und Greenland (<a href="references.html#ref-westreich2013" role="doc-biblioref">2013</a>)</span>.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-bradley1979" class="csl-entry" role="listitem">
Bradley, Ralph A., und Sushil S. and Srivastava. 1979. <span>„Correlation in Polynomial Regression“</span>. <em>The American Statistician</em> 33 (1): 11–14. <a href="https://doi.org/10.1080/00031305.1979.10482644">https://doi.org/10.1080/00031305.1979.10482644</a>.
</div>
<div id="ref-breiman2001" class="csl-entry" role="listitem">
Breiman, Leo. 2001. <span>„Statistical modeling: The two cultures“</span>. Journal Article. <em>Statistical Science</em> 16 (3): 199–231. <a href="https://D:/sciebo/database/720.pdf">D:/sciebo/database/720.pdf</a>.
</div>
<div id="ref-carlin2023" class="csl-entry" role="listitem">
Carlin, John B, und Margarita Moreno-Betancur. 2023. <span>„On the uses and abuses of regression models: a call for reform of statistical practice and teaching“</span>. <em>arXiv preprint arXiv:2309.06668</em>.
</div>
<div id="ref-james2023" class="csl-entry" role="listitem">
James, Gareth, Daniela Witten, Trevor Hastie, Robert Tibshirani, und Jonathan Taylor. 2023. <em>An introduction to statistical learning: With applications in Python</em>. Springer.
</div>
<div id="ref-peixoto1987" class="csl-entry" role="listitem">
Peixoto, Julio L. 1987. <span>„Hierarchical variable selection in polynomial regression models“</span>. <em>The American Statistician</em> 41 (4): 311–13.
</div>
<div id="ref-peixoto1990" class="csl-entry" role="listitem">
———. 1990. <span>„A property of well-formulated polynomial regression models“</span>. <em>The American Statistician</em> 44 (1): 26–30.
</div>
<div id="ref-pickett2021" class="csl-entry" role="listitem">
Pickett, Craig W, Chris Abbiss, James Zois, und Anthony J Blazevich. 2021. <span>„Pacing and stroke kinematics in 200-m kayak racing“</span>. <em>Journal of Sports Sciences</em> 39 (10): 1096–1104.
</div>
<div id="ref-ponce2025" class="csl-entry" role="listitem">
Ponce-Garcı́a, Tomás, Jerónimo Garcı́a-Romero, Laura Carrasco-Fernández, Alejandro Castillo-Domı́nguez, und Javier Benı́tez-Porres. 2025. <span>„Sex differences in anaerobic performance in CrossFit<span></span> athletes: a comparison of three different all-out tests“</span>. <em>PeerJ</em> 13: e18930.
</div>
<div id="ref-shacham1997" class="csl-entry" role="listitem">
Shacham, Modechai, und Neima Brauner. 1997. <span>„Minimizing the Effects of Collinearity in Polynomial Regression“</span>. <em>Industrial &amp; Engineering Chemistry Research</em> 36 (10): 4405–12. <a href="https://doi.org/10.1021/ie970236k">https://doi.org/10.1021/ie970236k</a>.
</div>
<div id="ref-westreich2013" class="csl-entry" role="listitem">
Westreich, Daniel, und Sander Greenland. 2013. <span>„The Table&nbsp;2 Fallacy: Presenting and Interpreting Confounder and Modifier Coefficients“</span>. <em>American Journal of Epidemiology</em> 177 (4): 292–98. <a href="https://doi.org/10.1093/aje/kws412">https://doi.org/10.1093/aje/kws412</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./mlm_hierarchies.html" class="pagination-link" aria-label="Modellhierarchien">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Modellhierarchien</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./mlm_logistic.html" class="pagination-link" aria-label="Logistische Regression">
        <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>