<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Skriptum - Fortgeschrittene Statistik - 17&nbsp; Integration von nominalen Variablen</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./mlm_hierarchies.html" rel="next">
<link href="./mlm_interactions.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>
<script>
  MathJax = {
    tex: {
      tags: 'ams'  // should be 'ams', 'none', or 'all'
    }
  };
</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./mlm_title.html">Multiple Regression</a></li><li class="breadcrumb-item"><a href="./mlm_dummy_coding.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Integration von nominalen Variablen</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skriptum - Fortgeschrittene Statistik</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./r_startup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eine Schnelleinführung in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Eine Übersicht über <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_kickoff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title"><code>R</code> Kickoff</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_flowcontrol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Ablaufkontrolle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Einfache Datenbearbeitung und Visualisierung in <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_literate_programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Literate programming in <code>R</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stats_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistik</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Eine kleine Welt der Unsicherheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistische Signifikanz, p-Wert und Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Parameterschätzung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Theoretische Verteilungen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_hypotheses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hypothesen testen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./slm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das einfache Regressionmodell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inferenz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_model_fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Modellfit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Vorhersage</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mlm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Interaktionseffekte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_dummy_coding.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Integration von nominalen Variablen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_hierarchies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Modellhierarchien</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./lm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das allgemeine lineare Modell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Synthese</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./ed_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Completely Randomized Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_linear_contrasts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Lineare Kontraste</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crfd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Completely Randomized Factorial Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crbd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Completely Randomized Block Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_irbd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Incomplete Randomized Block Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_split_plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Split-plot Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_cross_over.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Cross-over Design</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatur</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#vergleich-von-zwei-gruppen" id="toc-vergleich-von-zwei-gruppen" class="nav-link active" data-scroll-target="#vergleich-von-zwei-gruppen"><span class="header-section-number">17.1</span> Vergleich von zwei Gruppen</a></li>
  <li><a href="#nominale-variablen-in-r-detour" id="toc-nominale-variablen-in-r-detour" class="nav-link" data-scroll-target="#nominale-variablen-in-r-detour"><span class="header-section-number">17.2</span> Nominale Variablen in <code>R</code> (detour)</a></li>
  <li><a href="#vergleich-von-zwei-gruppen-continued" id="toc-vergleich-von-zwei-gruppen-continued" class="nav-link" data-scroll-target="#vergleich-von-zwei-gruppen-continued"><span class="header-section-number">17.3</span> Vergleich von zwei Gruppen (continued)</a></li>
  <li><a href="#kann-ich-aus-dem-t-test-ein-lineares-modell-machen" id="toc-kann-ich-aus-dem-t-test-ein-lineares-modell-machen" class="nav-link" data-scroll-target="#kann-ich-aus-dem-t-test-ein-lineares-modell-machen"><span class="header-section-number">17.4</span> Kann ich aus dem t-Test ein lineares Modell machen?</a></li>
  <li><a href="#dummyvariablen-bei-mehr-als-zwei-faktorstufen" id="toc-dummyvariablen-bei-mehr-als-zwei-faktorstufen" class="nav-link" data-scroll-target="#dummyvariablen-bei-mehr-als-zwei-faktorstufen"><span class="header-section-number">17.5</span> Dummyvariablen bei mehr als zwei Faktorstufen</a></li>
  <li><a href="#kombination-von-kontinuierlichen-und-nominalen-prädiktorvariablen" id="toc-kombination-von-kontinuierlichen-und-nominalen-prädiktorvariablen" class="nav-link" data-scroll-target="#kombination-von-kontinuierlichen-und-nominalen-prädiktorvariablen"><span class="header-section-number">17.6</span> Kombination von kontinuierlichen und nominalen Prädiktorvariablen</a></li>
  <li><a href="#zusammenfassung" id="toc-zusammenfassung" class="nav-link" data-scroll-target="#zusammenfassung"><span class="header-section-number">17.7</span> Zusammenfassung</a></li>
  <li><a href="#herleitung-der-identität-von-t-test-und-linearen-modell-advanced" id="toc-herleitung-der-identität-von-t-test-und-linearen-modell-advanced" class="nav-link" data-scroll-target="#herleitung-der-identität-von-t-test-und-linearen-modell-advanced"><span class="header-section-number">17.8</span> Herleitung der Identität von t-Test und linearen Modell (advanced)</a></li>
  <li><a href="#zum-nach--und-weiterlesen" id="toc-zum-nach--und-weiterlesen" class="nav-link" data-scroll-target="#zum-nach--und-weiterlesen"><span class="header-section-number">17.9</span> Zum Nach- und Weiterlesen</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Integration von nominalen Variablen</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Bisher haben wir nur kontinuierliche, beziehungsweise metrische, Variablen in unsere lineares Modell aufgenommen. Im Folgenden werden wir sehen, dass wir mit einem kleinem Trick genause nominale Variablen in das Modell integrieren können, ohne dass wir fundamental etwas neues lernen müssen.</p>
<section id="vergleich-von-zwei-gruppen" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="vergleich-von-zwei-gruppen"><span class="header-section-number">17.1</span> Vergleich von zwei Gruppen</h2>
<p>Beginnen wir mit einem einfachen Beispiel. Wir wollen die Unterschiede zwischen Männern und Frauen in Bezug auf die Körpergröße untersuchen. In <a href="#fig-mlm-dummy-gender">Abbildung&nbsp;<span>17.1</span></a> ist ein hypothetischer Datensatz von Körpergrößen von Frauen und Männern abgebildet. Wenig überraschen, da der Datensatz so erstellt wurde, sind Männer im Mittel größer als Frauen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-gender" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mlm_dummy_coding_files/figure-html/fig-mlm-dummy-gender-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.1: Simulierte Daten: Verteilung von Körpergrößen nach Geschlecht für Männer (m) und Frauen (f)</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#tbl-mlm-dummy-gender">Tabelle&nbsp;<span>17.1</span></a> ist ein Ausschnit aus den Daten tabellarisch dargestellt. Wenig überraschend, haben wir zwei Datenspalten. In der ersten Spalte stehen die Körpergrößen, während in der zweiten Spalte eine Indikatorvariable steht die entweder den Wert <span class="math inline">\(m\)</span> für Männer oder <span class="math inline">\(f\)</span> für Frauen annimmt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-mlm-dummy-gender" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;17.1: Ausschnitt aus den Daten.</caption>
<thead>
<tr class="header">
<th style="text-align: right;">cm</th>
<th style="text-align: left;">gender</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">174.4</td>
<td style="text-align: left;">m</td>
</tr>
<tr class="even">
<td style="text-align: right;">177.7</td>
<td style="text-align: left;">m</td>
</tr>
<tr class="odd">
<td style="text-align: right;">195.6</td>
<td style="text-align: left;">m</td>
</tr>
<tr class="even">
<td style="text-align: right;">171.3</td>
<td style="text-align: left;">f</td>
</tr>
<tr class="odd">
<td style="text-align: right;">164.0</td>
<td style="text-align: left;">f</td>
</tr>
<tr class="even">
<td style="text-align: right;">176.0</td>
<td style="text-align: left;">f</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In <a href="#tbl-mlm-dummy-gender-desc">Tabelle&nbsp;<span>17.2</span></a> sind dann auch noch einmal die deskriptiven Statistiken der Körpergrößendaten abgebildet die auch noch einmal den Eindruck aus <a href="#fig-mlm-dummy-gender">Abbildung&nbsp;<span>17.1</span></a> bestätigen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-mlm-dummy-gender-desc" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;17.2: Deskriptive Statistiken der Körpergrößendaten.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">gender</th>
<th style="text-align: right;">m</th>
<th style="text-align: right;">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">f</td>
<td style="text-align: right;">168.8</td>
<td style="text-align: right;">8.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">m</td>
<td style="text-align: right;">179.5</td>
<td style="text-align: right;">9.8</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Wir müssen jetzt allerdings erst einmal eine kurze Detour nehmen und verstehen, wie nominale Werte in <code>R</code> repräsentiert werden.</p>
</section>
<section id="nominale-variablen-in-r-detour" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="nominale-variablen-in-r-detour"><span class="header-section-number">17.2</span> Nominale Variablen in <code>R</code> (detour)</h2>
<p>Nominale Variablen werden in <code>R</code> mit einen speziellen Typ repräsentiert dem sogenannten <code>factor</code>. Erstellt werden kann ein Faktor mit der <code>factor()</code>-Funktion. Die Funktion hat drei wichtige Parameter. Der erste Parameter bezeichnet die Werte, der zweite die möglichen Faktorstufen (<code>levels</code>) und der dritte Parameter die dazugehörigen Bezeichnungen (<code>labels</code>). Ein einfaches Beispiel sieht dann so aus:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'m'</span>,<span class="st">'f'</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>gender</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] m m f f
Levels: m f</code></pre>
</div>
</div>
<p>D.h. wir haben einen Datenvektor mit den Elemente <span class="math inline">\((0,0,1,1)\)</span>. Wir spezifizieren die <code>levels</code> dementsprechend mit <span class="math inline">\(0\)</span> und <span class="math inline">\(1\)</span> und definieren die dazugehörigen <code>labels</code> mit <span class="math inline">\(m\)</span> und <span class="math inline">\(f\)</span>. Dabei sind jeweils Vektoren übergeben worden (siehe <code>c()</code>). Wenn wir die neue Variable <code>gender</code> aufrufen erhalten wird der Datenvektor mit den entsprechenden <code>labels</code> ausgegeben und zusätzlich gibt <code>R</code> die möglichen <code>labels</code> an.</p>
<p>Wenn wir den Parameter <code>levels</code> nicht angegeben hätten, dann extrahiert <code>factor()</code> die eineindeutigen Werte selbst und führt die Abbidlung auf die <code>labels</code> entsprechend der Sortierung aus.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'m'</span>,<span class="st">'f'</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>gender</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] m m f f
Levels: m f</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(gender)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "m","f": 1 1 2 2</code></pre>
</div>
</div>
<p>Dabei muss darauf geachtet werden, dass die Abbildung auch tatsächlich diejenige ist, die gewünscht ist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'f'</span>,<span class="st">'m'</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>gender</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] f f m m
Levels: f m</code></pre>
</div>
</div>
<p>Daher ist es fast immer sinnvoll <code>labels</code> und <code>levels</code> immer zusammen zu nehmen. Wenn die Parameter nicht angegeben werden, dann führt <code>factor</code> die Abbildung wiederum automatisch durch und für die <code>labels</code> werden die Datenwerte übernommen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>gender</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0 0 1 1
Levels: 0 1</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warnung
</div>
</div>
<div class="callout-body-container callout-body">
<p>Achtung, die Variable <code>gender</code> sieht zwar aus wie ein numerischer Vektor, sie ist es aber nicht.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.numeric</span>(gender)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>Intern wird eine Faktorvariable von <code>R</code> zwar als ein numerischer Vektor abgelegt. Aber die “sichtbaren” Werte sind nun die Zeichenketten der <code>labels</code>, die daher auch angezeigt werden. Die interne numerische Repräsentation muss auch nicht mehr den ursprünglichen Datenwerten entsprechen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>(gender)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 1 2 2</code></pre>
</div>
</div>
<p>Die Datenwerte waren ursprünglich <span class="math inline">\((0,1)\)</span> und sind jetzt auf <span class="math inline">\((1,2)\)</span> abgebildet worden. Erinnert euch an die Eigenschaft von nominalen Variablen. Nominale Variablen sind einfach voneinander unterscheidbare Werte die jedoch in keiner Ordnung stehen.</p>
</div>
</div>
<p>Die automatische Konvertierung von <code>factor()</code> funktioniert am intuitivsten mit Zeichenkettenvektoren.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">'m'</span>,<span class="st">'f'</span>,<span class="st">'m'</span>,<span class="st">'f'</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>gender</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] m f m f
Levels: f m</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(gender)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "f","m": 2 1 2 1</code></pre>
</div>
</div>
<p><code>factor()</code> ermittelt zunächst die eineindeutigen Werte und sortiert diese dann entsprechend des Typen. In diesem Fall wird die Zeichenkette alphabetisch sortiert. Dann erfolgt die Abbildung der Werte auf die <code>labels</code>. Dies führt in diesem Fall dazu, dass die Werte <code>m</code> intern den Wert <span class="math inline">\(2\)</span> zugeordnet bekommen, obwohl der erste Wert in den Daten <code>m</code> ist. Diese Sortierung der Daten wird später noch einmal von Bedeutung werden.</p>
<p>Die Abfolge der <code>levels</code> kann durch eine explizite Angabe der Reihenfolge selbst bestimmt werden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">'m'</span>,<span class="st">'f'</span>,<span class="st">'m'</span>,<span class="st">'f'</span>),</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'m'</span>,<span class="st">'f'</span>))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>gender</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] m f m f
Levels: m f</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(gender)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "m","f": 1 2 1 2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">'m'</span>,<span class="st">'f'</span>,<span class="st">'m'</span>,<span class="st">'f'</span>),</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'f'</span>,<span class="st">'m'</span>))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>gender</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] m f m f
Levels: f m</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(gender)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "f","m": 2 1 2 1</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p>Im package <code>forcats</code> sind eine Reihe von Funktionen hinterlegt, mit denen die Eigenschaften von <code>factor</code>-Variablen einfach manipuliert werden können. Zum Beispiel, wenn die Reihenfolge von Faktorstufen geändert werden soll kann die Funktion <code>fct_relevel()</code> verwendet.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] m f m f
Levels: f m</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] m f m f
Levels: m f</code></pre>
</div>
</div>
<p>Schaut euch die ausführliche Dokumentation der Funktionen und die Beispiel an, wenn ihr auf Probleme mit <code>factor</code>-Variablen stoßt.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p>Viele Funktionen in <code>R</code>, wie z.B. <code>lm()</code>, transformieren Vektoren mit Zeichenketten automatisch in einen <code>factor()</code> um. Wird in <code>lm()</code> in der Formel beispielsweise <code>y ~ gender</code> benutzt und <code>gender</code> ist eine Datenspalte die aus den Zeichenketten <code>c('m','m','f','f')</code> besteht, dann ruft <code>lm()</code> intern die Funktion <code>factor()</code> für diese Daten auf und führt dann die Berechnung mit dem Faktor durch.</p>
<p>Dies erleichtert natürlich oft den Umgang mit den Daten, hat aber den Nachteil das immer klar sein muss, dass die automatische Konvertierung auch tatsächlich diejenige ist, dich auch gewünscht ist.</p>
</div>
</div>
</section>
<section id="vergleich-von-zwei-gruppen-continued" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="vergleich-von-zwei-gruppen-continued"><span class="header-section-number">17.3</span> Vergleich von zwei Gruppen (continued)</h2>
<p>Kommen wir zurück zum Körpergrößenvergleich. Normalerweise würden wir die Unterschiede zwischen den beiden Gruppen mit einem t-Test für unabhängige Stichproben untersuchen. In <code>R</code> können wird dies mit der <code>t.test()</code>-Funktion durchführen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(cm <span class="sc">~</span> gender, <span class="at">data=</span>height, <span class="at">var.equal=</span>T)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  cm by gender
t = -4.5683, df = 58, p-value = 2.617e-05
alternative hypothesis: true difference in means between group f and group m is not equal to 0
95 percent confidence interval:
 -15.45403  -6.03713
sample estimates:
mean in group f mean in group m 
       168.7834        179.5290 </code></pre>
</div>
</div>
<p>Wir beobachten ein statistisch signifikantes Ergebnis.</p>
<p>Erinnern wir uns noch einmal an die Modellformulierung beim t-Test bei gleich großen Gruppen <span class="math inline">\((n_w = n_m)\)</span>.</p>
<p><span class="math display">\[\begin{equation}
\begin{aligned}
Y_{if} &amp;= \mu_{f} + \epsilon_{if}, \quad \epsilon_{if} \sim \mathcal{N}(0,\sigma^2) \\
Y_{im} &amp;= \mu_{m} + \epsilon_{im}, \quad \epsilon_{im} \sim \mathcal{N}(0,\sigma^2)
\end{aligned}
\label{eq-mlm-dummy-tTest-model}
\end{equation}\]</span></p>
<p>Beide Gruppen sollten normalverteilt sein mit gleicher Varianz <span class="math inline">\(\sigma^2\)</span> und Erwartungswert <span class="math inline">\(\mu_f\)</span> für die weiblichen Teilnehmerinnen und <span class="math inline">\(\mu_m\)</span> für die männlichen Teilnehmer. Die Hypothesen beim t-Test sind</p>
<p><span class="math display">\[\begin{align*}
H_0&amp;: \delta = 0 \\
H_1&amp;: \delta \neq 0
\end{align*}\]</span></p>
<p>D.h. wir gehen unter der <span class="math inline">\(H_0\)</span> Hypothese davon aus, dass kein Unterschied im Mittelwert zwischen den beiden Gruppen besteht. Die dazugehörige Teststatistik ist: <span class="math display">\[\begin{equation}
t = \frac{\bar{y}_m - \bar{y}_w}{\sqrt{\frac{s_m^2 + s_w^2}{2}}\sqrt{\frac{2}{n}}}
\label{eq-tTest}
\end{equation}\]</span></p>
<p>Unter der <span class="math inline">\(H_0\)</span> folgt die Referenz- bzw. Stichprobenverteilung einer t-Verteilung mit <span class="math inline">\(N - 2\)</span> Freiheitsgraden.</p>
<p><span class="math display">\[\begin{equation*}
t \sim t_{df=2n-2}
\end{equation*}\]</span></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-tDist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mlm_dummy_coding_files/figure-html/fig-mlm-dummy-tDist-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.2: Dichtefunktion der t-Verteilung mit <span class="math inline">\(df=58\)</span></figcaption>
</figure>
</div>
</div>
</div>
<p>Soweit nicht Neues. Wir wollen aber alles mit dem linearen Modell machen. Daher…</p>
</section>
<section id="kann-ich-aus-dem-t-test-ein-lineares-modell-machen" class="level2" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="kann-ich-aus-dem-t-test-ein-lineares-modell-machen"><span class="header-section-number">17.4</span> Kann ich aus dem t-Test ein lineares Modell machen?</h2>
<p>Unsere bekanntes lineares Modell hat die folgende Form:</p>
<p><span class="math display">\[\begin{equation}
Y_i = \beta_0 + \beta_1 \cdot x_i + \epsilon_i
\label{eq-mlm-dummy-lm}
\end{equation}\]</span></p>
<p>Können wir diese Modell irgendwie auf die Formeln <span class="math inline">\(\eqref{eq-mlm-dummy-tTest-model}\)</span> und <span class="math inline">\(\eqref{eq-tTest}\)</span> abbilden? Tatsächlich gibt es eine relativ einfache Möglichkeit mittels sogenannter Dummy- oder Indikatorvariablen. Wenn <span class="math inline">\(x_i\)</span> in Formel <span class="math inline">\(\eqref{eq-mlm-dummy-lm}\)</span> als Indikatorvariable verwendet wird, dann nimmt <span class="math inline">\(x_i\)</span> nur zwei verschiedene Werte an. Entweder den Wert <span class="math inline">\(0\)</span> oder den Wert <span class="math inline">\(1\)</span>. Mit diesem Trick können wir die Gruppenzugehörigkeit, im Beispiel männlich oder weiblich, abbilden. Dazu legen wir eine Referenzgruppe fest, beispielsweise weiblich. Wenn nun ein Wert <span class="math inline">\(y_i\)</span> aus der Gruppe weiblich kommt, dann wird <span class="math inline">\(x_i = 0\)</span> gesetzt, während wenn ein Wert <span class="math inline">\(y_i\)</span> aus der Gruppe männlich kommt, dann wird <span class="math inline">\(x_i = 1\)</span> gesetzt.</p>
<p><span class="math display">\[\begin{equation*}
x_i = \begin{cases}
0\text{ wenn weiblich}\\
1\text{ wenn männlich}
\end{cases}
\end{equation*}\]</span></p>
<p>Jetzt müssen wir noch <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> in Formel <span class="math inline">\(\eqref{eq-mlm-dummy-lm}\)</span> festlegen. Wir können den <span class="math inline">\(y\)</span>-Achsenabschnitt <span class="math inline">\(\beta_0\)</span> gleich des Mittelwerts der Referenzgruppe setzen. Also <span class="math inline">\(\beta_0 = \mu_f\)</span>. Damit fehlt noch <span class="math inline">\(\beta_1\)</span>, hier machen wir die Festlegung <span class="math inline">\(\beta_1 = \mu_m - \mu_f = \Delta\)</span>. D.h. der Unterschied zwischen den beiden Gruppenmittelwerten. Damit ist aus Formel <span class="math inline">\(\eqref{eq-mlm-dummy-tTest-model}\)</span> das folgende lineare Modell geworden.</p>
<p><span class="math display">\[\begin{align*}
Y_i &amp;= \mu_f + \Delta_{m} \times x_{i} + \epsilon_i \\
\Delta_m &amp;= \mu_m - \mu_f \\
\end{align*}\]</span></p>
<p>Schauen wir uns einmal an wie das konkret aussieht. Wir definieren dazu noch die <em>Residuen</em> <span class="math inline">\(e_i\)</span> im Modell <span class="math inline">\(\eqref{eq-mlm-dummy-tTest-model}\)</span>.</p>
<p><span class="math display">\[\begin{align*}
e_{if} &amp;= y_{if} - \mu_f \\
e_{im} &amp;= y_{im} - \mu_m
\end{align*}\]</span></p>
<p>Im t-Test Modell ist eine Voraussetzung, dass die Werte Normalverteilt sind, damit sind wiederum die Residuen <span class="math inline">\(e_i\)</span> ebenfalls Normalverteilt, da die Subtraktion des Mittelwerts <span class="math inline">\(\mu\)</span> von den Werten nichts an der Form der Verteilung ändert, sondern nur deren Mittelwert verschiebt.</p>
<p>Damit können wir nun zum Beispiel den ersten Wert aus <a href="#tbl-mlm-dummy-gender">Tabelle&nbsp;<span>17.1</span></a> <span class="math inline">\(y_{1m} = 174.4\)</span>, mit <span class="math inline">\(\Delta = 179.53 - 168.78 = 10.75, e_{1m} = 174.4 - 179.53= -5.13\)</span> und <span class="math inline">\(x_{1m} = 1\)</span> abbilden.</p>
<p><span class="math display">\[\begin{align*}
y_{1m} = 174.4 &amp;= \mu_f + \Delta \cdot x_{1m} + e_{1m} \\
&amp;= 168.78 + 10.74 \cdot 1 - 5.13
\end{align*}\]</span></p>
<p>Das Gleiche für den ersten weiblichen Wert in <a href="#tbl-mlm-dummy-gender">Tabelle&nbsp;<span>17.1</span></a> <span class="math inline">\(y_{1f} = 171.3, \Delta = 10.75, e_{1f} = 171.3 - 168.78 = 2.52\)</span> und $x_{1f} = 0.</p>
<p><span class="math display">\[\begin{align*}
y_{1f} = 171.3 &amp;= \mu_f + \Delta \cdot x_{1f} + e_{1f} \\
&amp;= 168.78 + 10.74 \cdot 0 + 2.52
\end{align*}\]</span></p>
<p>Zusammenfassend, haben wir mit der Indikatorvariable und dem <span class="math inline">\(\Delta\)</span> zwischen den Mittelwerten der beiden Gruppen eine Möglichkeit gefunden das t-Test Modell auf das lineare Modell abzubilden. Und tatsächlich, wenn das Modell in <code>lm()</code> eingeben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(cm <span class="sc">~</span> gender, height)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Modellfit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
<th style="text-align: right;">t</th>
<th style="text-align: left;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">168.783</td>
<td style="text-align: right;">1.663</td>
<td style="text-align: right;">101.477</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">genderm</td>
<td style="text-align: right;">10.746</td>
<td style="text-align: right;">2.352</td>
<td style="text-align: right;">4.568</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Dann sehen wir, dass wir genau diese Werte auch herausbekommen. <code>lm()</code> gibt die Faktorstufe nach dem Namen der Faktorvariable an. Im Beispiel steht <code>genderm</code> für Stufe <code>m</code> aus dem Faktor <code>gender</code>. Wenn wir uns die Werte für den t-Wert für <span class="math inline">\(\beta_1 = \Delta\)</span> anschauen, dann sehen wir, dass der Wert exakt mit demjenigen übereinstimmt, den wir mittels des t-Test berechnet haben. Lediglich das Vorzeichen ist in der anderen Richtung was aber nur damit zusammenhängt welcher Gruppenmittelwert von dem anderen Gruppenmittelwert subtrahiert werden. Schauen wir uns das Konfidenzintervall für den <em>Steigungskoeffizienten</em> <span class="math inline">\(\beta_1\)</span> an:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 165.45401 172.11276
genderm       6.03713  15.45403</code></pre>
</div>
</div>
<p>Dann sehen wir, dass auch das Konfidenzintervall exakt demjenigen des t-Test, bis auf das Vorzeichen, entspricht. D.h. nochmal wir können einen t-Test als ein lineares Modell verstehen und anders herum wir können nun ohne Probleme nominale Variablen in ein lineares Modell mit aufnehmen.</p>
<p>Damit haben wir auch schon eine sehr gute Idee wie ‘lm()’ intern gemacht hat. Bei der Modellevaluierung erkennt <code>lm()</code> gender als nominale Variable und ersetzt es durch die Dummykodierung (siehe <a href="#tbl-mlm-dummy-dummy-lm">Tabelle&nbsp;<span>17.3</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-mlm-dummy-dummy-lm" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;17.3: Repräsentation der Faktorvariablen</caption>
<thead>
<tr class="header">
<th style="text-align: right;">cm</th>
<th style="text-align: left;">gender</th>
<th style="text-align: right;"><span class="math inline">\(x_1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">174.40</td>
<td style="text-align: left;">m</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">177.70</td>
<td style="text-align: left;">m</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">195.59</td>
<td style="text-align: left;">m</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">160.05</td>
<td style="text-align: left;">f</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">164.92</td>
<td style="text-align: left;">f</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">154.35</td>
<td style="text-align: left;">f</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><code>lm()</code> ersetzt <code>gender</code> durch die Dummy-Variable, also durch Zahlenwerte, und dann kann einfach wieder die uns bekannte Maschinerie des linearen Modell angeworfen werden. Schauen wir uns an, wie ein Residuenplot bei einer Dummyvariablen aussieht (siehe <a href="#fig-mlm-dummy-resid-plot">Abbildung&nbsp;<span>17.3</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-resid-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mlm_dummy_coding_files/figure-html/fig-mlm-dummy-resid-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.3: Residuenplot des Körpergrößenmodells</figcaption>
</figure>
</div>
</div>
</div>
<p>Der Plot sieht etwas komisch aus, da die Residuen nur für zwei vorhergesagte Werte <span class="math inline">\(\hat{y}_i\)</span> angezeigt werden. Kurzes überlegen sollte uns aber davon überzeugen, dass dies korrekt ist, da wir nun noch zwei verschiedene <span class="math inline">\(y\)</span>-Wert vorhersagen. Nämlich für die Werte <span class="math inline">\(x_i = 0\)</span> und <span class="math inline">\(x_i = 1\)</span>, eben die Mittelwerte aus den beiden Gruppen.</p>
</section>
<section id="dummyvariablen-bei-mehr-als-zwei-faktorstufen" class="level2" data-number="17.5">
<h2 data-number="17.5" class="anchored" data-anchor-id="dummyvariablen-bei-mehr-als-zwei-faktorstufen"><span class="header-section-number">17.5</span> Dummyvariablen bei mehr als zwei Faktorstufen</h2>
<p>Nachdem wir ein Beispiel mit zwei Faktorstufen durchgegangen sind stellt sich die Frage ob wir auch mehr als zwei Faktorstufen bei einer nominalen Variablen in ein lineares Modell überführen können?</p>
<p>Schauen wir uns dazu wiederum ein einfaches synthetisches Beispiel an (siehe <a href="#fig-mlm-dummy-reaction-01">Abbildung&nbsp;<span>17.4</span></a>)</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-reaction-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mlm_dummy_coding_files/figure-html/fig-mlm-dummy-reaction-01-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.4: Ein Reaktionszeitexperiment mit vier Stufen A, B, C und D</figcaption>
</figure>
</div>
</div>
</div>
<p>Wir haben Daten zu einem Reaktionszeitexperiment bei dem Probanden unter vier verschiedenen Konditionen <span class="math inline">\(A,B,C\)</span> und <span class="math inline">\(D\)</span> beobachtet wurden. Die deskriptive Daten sind <a href="#tbl-mlm-dummy-reaction-01">Tabelle&nbsp;<span>17.4</span></a> einsehbar. Der Einfachheit halber sind die Daten so generiert, dass die Gruppenmittelwert von <span class="math inline">\(A\)</span> nach <span class="math inline">\(D\)</span> immer größer werden.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-mlm-dummy-reaction-01" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;17.4: Gruppenmittelwerte, Standardabweichung und Unterschiede zu Stufe A</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Gruppe</th>
<th style="text-align: right;"><span class="math inline">\(\bar{y}_j\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_j\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\Delta_{j-A}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">509.53</td>
<td style="text-align: right;">45.66</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">599.68</td>
<td style="text-align: right;">43.57</td>
<td style="text-align: right;">90.15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">706.94</td>
<td style="text-align: right;">40.49</td>
<td style="text-align: right;">197.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: right;">805.09</td>
<td style="text-align: right;">52.51</td>
<td style="text-align: right;">295.56</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Die letzten Spalte zeigt die Abweichungen der Gruppenmittelwerte der Gruppen <span class="math inline">\(B,C,D\)</span> von der Gruppe <span class="math inline">\(A\)</span> an. Das sollte jetzt auch schon direkt eine Möglichkeit aufzeigen, wie wir diese Daten in ein lineares Modell überführen. Wir setzen wieder eine Referenzgruppe fest, z.B. Gruppe <span class="math inline">\(A\)</span> und anstatt ein einzelnes <span class="math inline">\(Delta\)</span> führen wir drei <span class="math inline">\(\Delta\)</span>s ein, die jeweils die Abweichungen der Faktorstufen von der Referenzstufe repräsentieren. Für jedes dieser <span class="math inline">\(\Delta_i\)</span>s führen wir jetzt eine Dummyvariable <span class="math inline">\(x_{ij}\)</span> ein, mit der wir jeweils über die <span class="math inline">\(0\)</span> und <span class="math inline">\(1\)</span> die Zugehörig des <span class="math inline">\(y_i\)</span> Wertes zu der Gruppe kodieren. Ein lineares Modell lässt nun wie folgt formulieren:</p>
<p><span class="math display">\[
y_i = \mu_A + \Delta_{B-A} x_{1i} + \Delta_{C-A} x_{2i} + \Delta_{D-A} x_{3i} + \epsilon_i
\]</span></p>
<p>Wir haben drei Dummyvariablen <span class="math inline">\(x_{1i}, x_{2i}\)</span> und <span class="math inline">\(x_{3i}\)</span> eingeführt und die Modellkoeffizienten bilden jeweils die Abweichungen der Mittelwerte von Gruppe <span class="math inline">\(A\)</span> ab. Dies führt dann zu der folgenden Kodierung der Daten (siehe <a href="#tbl-mlm-dummy-reaction-02">Tabelle&nbsp;<span>17.5</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-mlm-dummy-reaction-02" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabelle&nbsp;17.5: Kodierung der Dummyvariablen für das Reaktionszeitexperiment.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Wenn ein Wert <span class="math inline">\(y_i\)</span> aus Gruppe <span class="math inline">\(A\)</span> kommt, dann werden die Dummyvariablen <span class="math inline">\(x_{1i}, x_{2i}, x_{3i}\)</span> mit den Werten <span class="math inline">\((0,0,0)\)</span> belegt. Wenn ein Wert <span class="math inline">\(y_i\)</span> aus Gruppe <span class="math inline">\(B\)</span> kommt, dann <span class="math inline">\((1,0,0)\)</span> belegt usw..</p>
<p>Dieser Ansatz lässt sich wie folgt Verallgemeinern (siehe <a href="#tbl-mlm-dummy-coding">Tabelle&nbsp;<span>17.6</span></a>).</p>
<div id="tbl-mlm-dummy-coding" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;17.6: Dummykodierung bei <span class="math inline">\(k\)</span>-Faktorstufen.</caption>
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(x_1\)</span></th>
<th><span class="math inline">\(x_2\)</span></th>
<th><span class="math inline">\(\ldots\)</span></th>
<th><span class="math inline">\(x_{K-1}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Referenz (<span class="math inline">\(j=1\)</span>)</td>
<td>0</td>
<td>0</td>
<td></td>
<td>0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(j=2\)</span></td>
<td>1</td>
<td>0</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td>0</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(j=3\)</span></td>
<td>0</td>
<td>1</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td>0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(j=K\)</span></td>
<td>0</td>
<td>0</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
<p>Bei Integration einer nominalen Variable mit <span class="math inline">\(K\)</span> Faktorstufen werden <span class="math inline">\(K-1\)</span> Dummyvariablen <span class="math inline">\(x_1, x_2, \ldots, x_{K-1}\)</span> benötigt. Eine der Faktorstufen wird als Referenzstufe definiert. Die Dummyvariablen <span class="math inline">\(x_1\)</span> bis <span class="math inline">\(x_{K-1}\)</span> kodieren dann die Abweichungen der anderen Stufen von der Referenzstufe. Diese Art der Kodierung wird in der Literatur auch als <em>treatment</em> Kodierung bezeichnet.</p>
<div id="def-dummy" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 17.1 (Dummyvariablen ) </strong></span>Eine Dummyvariable, auch Indikatorvariable, ist eine binäre Prädiktorvariable die nur die Werte <span class="math inline">\(0\)</span> oder <span class="math inline">\(1\)</span> annimmt in einem linearem Modell einnimmt. Mit einer Dummyvariable kann die An- bzw. Abwesenheit eines kategorialen Effekts modelliert werden.</p>
</div>
<p>Das lineare Modell in unserem Reaktionszeitexperiment ergibt den folgenden Modellfit (siehe <a href="#tbl-mlm-dummy-reaction-03">Tabelle&nbsp;<span>17.7</span></a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(rt <span class="sc">~</span> group, data)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-mlm-dummy-reaction-03" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Tabelle&nbsp;17.7: Koeffizientenmatrix für die Dummykodierung des Reaktionszeitexperiments.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">$\hat{\beta}$</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">$s_e$</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">509.526</td>
<td style="text-align: right;">10.235</td>
<td style="text-align: right;">49.784</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">groupB</td>
<td style="text-align: right;">90.150</td>
<td style="text-align: right;">14.474</td>
<td style="text-align: right;">6.228</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">groupC</td>
<td style="text-align: right;">197.414</td>
<td style="text-align: right;">14.474</td>
<td style="text-align: right;">13.639</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">groupD</td>
<td style="text-align: right;">295.561</td>
<td style="text-align: right;">14.474</td>
<td style="text-align: right;">20.420</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Wir erhalten als Steigungskoeffizienten eben genau die Abweichungen der Mittelwerte der jeweiligen Faktorstufen von der Referenzstufe (siehe <a href="#tbl-mlm-dummy-reaction-02">Tabelle&nbsp;<span>17.5</span></a>). D.h. insgesamt haben wir also die Möglichkeit eine nominale Variable mit beliebig vielen Faktorstufen in einem linearen Modell abzubilden. Damit ist dann auch die Unterscheidung in ANOVA und linear Regression als überfällig anzusehen, da beide letztendlich auf dem gleichem Modell, nämlich dem linearen Modell, beruhen.</p>
<p>Schauen wir uns noch den Residuenplot an (siehe <a href="#fig-mlm-dummy-reaction-02">Abbildung&nbsp;<span>17.5</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-reaction-02" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mlm_dummy_coding_files/figure-html/fig-mlm-dummy-reaction-02-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.5: Residuenplot für das Modell der Reaktionszeitdaten.</figcaption>
</figure>
</div>
</div>
</div>
<p>Hier sehen wir wieder, dass nur vier verschiedene <span class="math inline">\(\hat{y}_i\)</span> Werte vorhergesagt werden, nämlich die Mittelwerte <span class="math inline">\(\bar{y}_k\)</span> in den jeweiligen <span class="math inline">\(K\)</span> Gruppen. Die Residuen <span class="math inline">\(e_i\)</span> streuen daher nur um diese vorhergesagten Werte.</p>
<p>Wir können die Dummy-Kodierung explizit von <code>R</code> mittels der <code>dummy.coef()</code>-Funktion erhalten.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dummy.coef</span>(mod)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Full coefficients are 
                                                       
(Intercept):     509.5262                              
group:                  A         B         C         D
                  0.00000  90.15023 197.41364 295.56065</code></pre>
</div>
</div>
</section>
<section id="kombination-von-kontinuierlichen-und-nominalen-prädiktorvariablen" class="level2" data-number="17.6">
<h2 data-number="17.6" class="anchored" data-anchor-id="kombination-von-kontinuierlichen-und-nominalen-prädiktorvariablen"><span class="header-section-number">17.6</span> Kombination von kontinuierlichen und nominalen Prädiktorvariablen</h2>
<p>Schauen wir uns nun als weiteren Fall ein Modell an, bei dem beide Typen von Variablen, nominale und kontinuierliche, integriert sind. In <a href="#fig-mlm-dummy-combi-01">Abbildung&nbsp;<span>17.6</span></a> haben wir einen hypothetischen Zusammenhang zwischen der körperlichen Leistung dem Trainingsalter und dem Gender.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-combi-01" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mlm_dummy_coding_files/figure-html/fig-mlm-dummy-combi-01-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.6: Hypothetische Leistungsentwicklung in Abhängigkeit vom Alter und Gender</figcaption>
</figure>
</div>
</div>
</div>
<p>Das Trainingsalter geht wie bisher als kontinuierliche Variable in das Modell ein, während wir gender als nominale Variable über eine Dummyvariable modellieren. Weibliche Teilnehmerinnen der Studie legen wir als Referenzstufe fest. Das resultiert in dem folgenden linearen Modell:</p>
<p><span class="math display">\[\begin{align*}
Y_i &amp;= \beta_{ta = 0,x_{1i}=0} + \Delta_m \times x_{1i} + \beta_{ta} \times ta + \epsilon_i \\
x_1 &amp;=
\begin{cases}
0\text{ wenn weiblich}\\
1\text{ wenn männlich}
\end{cases} \\
\end{align*}\]</span></p>
<p>Modellieren mit <code>lm()</code> führt dann zu:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(perf <span class="sc">~</span> gender_f <span class="sc">+</span> ta, lew)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-mlm-dummy-combi-01" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Tabelle&nbsp;17.8: Modellfit für das Modell mit Trainingsalter und Gender.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">41.181</td>
<td style="text-align: right;">1.083</td>
<td style="text-align: right;">38.024</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender_fm</td>
<td style="text-align: right;">-10.877</td>
<td style="text-align: right;">0.805</td>
<td style="text-align: right;">-13.503</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ta</td>
<td style="text-align: right;">1.927</td>
<td style="text-align: right;">0.145</td>
<td style="text-align: right;">13.261</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Die Variable <code>gender</code> ist durch <code>lm()</code> als Dummyvariable definiert worden und der Steigungskoeffizient <span class="math inline">\(\beta_1=\)</span><code>gender_fm</code> kodiert den mittleren Unterschied zwischen männlichen und weiblichen Studienteilnehmerinnen. Der <span class="math inline">\(y\)</span>-Achsenabschnitt kodiert daher die Leistung von weiblichen Teilnehmerinnen mit einem Trainingsalter von <code>ta</code><span class="math inline">\(= 0\)</span>. (Warum?). Schauen wir uns dazu die resultierenden Graden der vorhergesagten <span class="math inline">\(\hat{y}_i\)</span> an (siehe <a href="#fig-mlm-dummy-combi-02">Abbildung&nbsp;<span>17.7</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-combi-02" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mlm_dummy_coding_files/figure-html/fig-mlm-dummy-combi-02-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.7: Leistungsentwicklung in Abhängigkeit vom Alter und Gender</figcaption>
</figure>
</div>
</div>
</div>
<p>Wir haben zwei Geraden eine für die weiblichen und eine für die männlichen Teilnehmer mittels des Modells gefittet. Die Geraden sind parallel und um den Wert von <span class="math inline">\(\beta_1\)</span> gegeneinander verschoben.</p>
<p>Nichts hält uns davon ab auch eine Interaktion zwischen kontinuierlichen und nominalen Variablen zu modellieren. Wenn die Daten zum Beispiel dem Trend in <a href="#fig-mlm-dummy-combi-03">Abbildung&nbsp;<span>17.8</span></a> folgen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-combi-03" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mlm_dummy_coding_files/figure-html/fig-mlm-dummy-combi-03-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.8: Leistungsentwicklung in Abhängigkeit vom Alter und Gender</figcaption>
</figure>
</div>
</div>
</div>
<p>Hier sehen wir, dass die Zunahme der Leistung mit dem Trainingsalter nicht gleich ist in beiden gendern. Bei männlichen Teilnehmern ist der Zuwachs mit dem Trainingsalter größer. D.h der Einfluss der Prädiktorvariable Trainingsalter hängt mit der Ausprägung der Prädiktorvariablen gender zusammen. Es liegt ein Interaktionseffekt vor. Übertragen auf ein lineares Modell könnte der Modellansatz wie folgt aussehen:</p>
<p><span class="math display">\[\begin{equation*}
y_i = \beta_{ta=0,x_{1i}=0} + \Delta_m \times x_{1i} + \beta_{ta} \times ta + \beta_{ta \times gender} \times x_{1i} \times ta + \epsilon_i
\end{equation*}\]</span></p>
<p>In <code>lm()</code> ausgedrückt:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(perf <span class="sc">~</span> gender_f <span class="sc">*</span> ta, lew)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-mlm-dummy-combi-02" class="anchored">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Tabelle&nbsp;17.9: Modellfit für das Interaktionsmodell mit Trainingsalter und Gender.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">31.354</td>
<td style="text-align: right;">1.370</td>
<td style="text-align: right;">22.891</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender_fm</td>
<td style="text-align: right;">8.575</td>
<td style="text-align: right;">2.010</td>
<td style="text-align: right;">4.266</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ta</td>
<td style="text-align: right;">1.763</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">9.043</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">gender_fm:ta</td>
<td style="text-align: right;">2.362</td>
<td style="text-align: right;">0.290</td>
<td style="text-align: right;">8.139</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Die gefitteten Regressionsgeraden nehmen dann die folgende Form an (siehe <a href="#fig-mlm-dummy-combi-04">Abbildung&nbsp;<span>17.9</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-dummy-combi-04" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="mlm_dummy_coding_files/figure-html/fig-mlm-dummy-combi-04-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;17.9: Leistungsentwicklung in Abhängigkeit vom Alter und Gender</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="zusammenfassung" class="level2" data-number="17.7">
<h2 data-number="17.7" class="anchored" data-anchor-id="zusammenfassung"><span class="header-section-number">17.7</span> Zusammenfassung</h2>
<p>In diesem Kapitel haben wir gesehen, dass wir ohne Probleme auch nominale Prädiktorvariablen in das lineare Modell integrieren können. Dabei können die Variablen rein additiv oder auch als interaktive Effekte eingehen. Damit haben wir eine extrem flexiblen Prozess um Daten zu modellieren und dabei immer in dem bekannten Punkt-Steigungs-Modell bleiben.</p>
</section>
<section id="herleitung-der-identität-von-t-test-und-linearen-modell-advanced" class="level2" data-number="17.8">
<h2 data-number="17.8" class="anchored" data-anchor-id="herleitung-der-identität-von-t-test-und-linearen-modell-advanced"><span class="header-section-number">17.8</span> Herleitung der Identität von t-Test und linearen Modell (advanced)</h2>
<p>Seien beide Gruppen gleich groß (<span class="math inline">\(n\)</span>) mit <span class="math inline">\(N = n_m + n_w = 2 \times n\)</span>. Der t-Wert für <span class="math inline">\(\beta_1\)</span> berechnet sich aus <span class="math inline">\(t = \frac{b_1}{s_b}\)</span> mit:</p>
<p><span class="math display">\[
s_b = \sqrt{\frac{\sum_{i=1}^N (y_i - \bar{y})^2}{N-2}\frac{1}{\sum_{i=1}^N(x_i-\bar{x})^2}}
\]</span> Dadurch, das die <span class="math inline">\(x_i\)</span> entweder gleich <span class="math inline">\(0\)</span> oder <span class="math inline">\(1\)</span> sind, ist <span class="math inline">\(\bar{x}=0.5\)</span> und die Abweichungsquadrate im zweiten Term sind alle gleich <span class="math inline">\(\frac{1}{4}\)</span>.</p>
<p><span class="math display">\[
\sum_{i=1}^N(x_i - \bar{x})^2=\sum_{i=1}^N\left(x_i - \frac{1}{2}\right)^2 = \sum_{i=1}^N\frac{1}{4}=\frac{N}{4}=\frac{2n}{4}=\frac{n}{2}
\]</span></p>
<p>Der ersten Term kann mit etwas Algebra und der Definition für die Stichprobenvarianz <span class="math inline">\(s^2\)</span> auf die gewünschte Form gebracht werden.</p>
<p><span class="math display">\[
\frac{\sum_{i=1}^N(y_i-\hat{y})^2}{N-2}=\frac{\sum_{i=1}^n(\overbrace{y_{im} - \bar{y}_m}^{Männer})^2+\sum_{i=1}^n(\overbrace{y_{iw}-\bar{y}_w}^{Frauen})^2}{2(n-1)}=\frac{(n-1)s_m^2+(n-1)s_w^2}{2(n-1)}=\frac{s_m^2+s_w^2}{2}
\]</span></p>
<p>Die Herleitung für <span class="math inline">\(\beta_1 = \Delta = \mu_w - \mu_m\)</span> ist ebenfalls relativ geradlinig wenn wir uns an den Zusammenhang zwischen <span class="math inline">\(\beta_1\)</span> und der Kovarianz zwischen <span class="math inline">\(x\)</span> und <span class="math inline">\(y\)</span> erinnern. Mit <span class="math inline">\(s_x^2 = \frac{N\frac{1}{4}}{N-1} = \frac{N}{4(N-1)}\)</span> folgt:</p>
<p><span class="math display">\[\begin{align*}
    b_1 &amp;= \frac{cov(x,y)}{s_x^2} \\
    &amp;= \frac{\sum_{i=1}^N(y_i - \bar{y})(x_i - \bar{x})}{N-1} \frac{4(N-1)}{N} \\
    &amp;= 4\frac{\sum_{i=1}^n(y_{im}-\bar{y})\frac{-1}{2}+\sum(y_{iw}-\bar{y})\frac{1}{2}}{N} \\
    &amp;= \frac{4}{2}\frac{\sum_{i=1}^n(y_{iw}-\bar{y}) - \sum_{i=1}^n(y_{im}-\bar{y})}{2n} \\
    &amp;= \frac{\sum_{i=1}^n y_{iw}}{n} - \frac{n\bar{y}}{n} - \frac{\sum_{i=1}^n y_{im}}{n} + \frac{n\bar{y}}{n} \\
    &amp;= \bar{y}_w - \bar{y}_m = \Delta
\end{align*}\]</span></p>
<p>Zu guter Letzt noch die Herleitung für <span class="math inline">\(\beta_0 = \mu_m\)</span>.</p>
<p>Mit <span class="math inline">\(b_1 = \Delta = \bar{y}_w - \bar{y}_m\)</span>: <span class="math display">\[\begin{align*}
b_0 &amp;= \bar{y} - \Delta \times \bar{x} \\
&amp;= \frac{\sum_{i=1}^N y_i}{N} - \Delta \times \frac{1}{2} \\
&amp;= \frac{\sum_{i=1}^n y_{im} + \sum_{i=1}^n y_{iw}}{2n} - \frac{1}{2}(\bar{y}_w - \bar{y}_m)  \\
&amp;= \frac{1}{2}\frac{\sum_{i=1}^ny_{im}}{n} + \frac{1}{2}\frac{\sum_{i=1}^ny_{iw}}{n} - \frac{1}{2}\bar{y}_w + \frac{1}{2}\bar{y}_m \\
&amp;= \frac{1}{2}\bar{y}_m + \frac{1}{2}\bar{y}_w - \frac{1}{2}\bar{y}_w + \frac{1}{2}\bar{y}_m \\
&amp;= \bar{y}_m
\end{align*}\]</span></p>
</section>
<section id="zum-nach--und-weiterlesen" class="level2" data-number="17.9">
<h2 data-number="17.9" class="anchored" data-anchor-id="zum-nach--und-weiterlesen"><span class="header-section-number">17.9</span> Zum Nach- und Weiterlesen</h2>
<p>In <span class="citation" data-cites="kutner2005">(<a href="references.html#ref-kutner2005" role="doc-biblioref">Kutner u.&nbsp;a. 2005, p.313–319</a>)</span> sind die Herleitungen noch mal genauer erkärt.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-kutner2005" class="csl-entry" role="listitem">
Kutner, Michael H, Christopher J Nachtsheim, John Neter, und William Li. 2005. <em>Applied Linear Statistical Models</em>. 5. Aufl. McGraw-Hill Irwin New York.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./mlm_interactions.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Interaktionseffekte</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./mlm_hierarchies.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Modellhierarchien</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>