<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>18&nbsp; Einführung – Skriptum - Fortgeschrittene Statistik</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./mlm_interactions.html" rel="next">
<link href="./mlm_title.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>
<script>

  MathJax = {

    tex: {

      tags: 'ams'  // should be 'ams', 'none', or 'all'

    }

  };

</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./mlm_title.html">Multiple Regression</a></li><li class="breadcrumb-item"><a href="./mlm_basics.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Einführung</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skriptum - Fortgeschrittene Statistik</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./r_startup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eine Einführung in die Programmiersprache R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Eine Übersicht über <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_vars_types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Variablen und Datentypen in <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_flowcontrol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Ablaufkontrolle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Funktionen in <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Datenverarbeitung mit <code>tidyverse</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Datenvisualisierung mit <code>ggplot2</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_literate_programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Literate programming in <code>R</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stats_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistik - Die Grundlagen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Eine kleine Welt der Unsicherheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Statistische Signifikanz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hypothesentests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Theoretische Verteilungen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_hypotheses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Weitere Grundlagen der Statistik</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./slm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das einfache Regressionmodell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Inferenz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_model_fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Modellfit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Vorhersage</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Maximum-Likelihood</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mlm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_basics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Interaktionseffekte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_dummy_coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Integration von nominalen Variablen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_hierarchies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Modellhierarchien</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Polynome und Prädiktion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Logistische Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_lmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Gemischte Lineare Modelle</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./ed_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Messfehler und Reliabilität</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Completely Randomized Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_linear_contrasts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Lineare Kontraste</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crfd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Completely Randomized Factorial Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crbd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Block Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_split_plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Split-Unit Designs</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Mathematische Grundlagen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatur</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#bedeutung-der-koeffizienten-bei-der-multiplen-regression" id="toc-bedeutung-der-koeffizienten-bei-der-multiplen-regression" class="nav-link active" data-scroll-target="#bedeutung-der-koeffizienten-bei-der-multiplen-regression"><span class="header-section-number">18.1</span> Bedeutung der Koeffizienten bei der multiplen Regression</a></li>
  <li><a href="#interpretation-der-modellkoeffizienten" id="toc-interpretation-der-modellkoeffizienten" class="nav-link" data-scroll-target="#interpretation-der-modellkoeffizienten"><span class="header-section-number">18.2</span> Interpretation der Modellkoeffizienten</a>
  <ul class="collapse">
  <li><a href="#added-variable-plots" id="toc-added-variable-plots" class="nav-link" data-scroll-target="#added-variable-plots"><span class="header-section-number">18.2.1</span> Added-variable plots</a></li>
  <li><a href="#was-passiert-wenn-eine-prädiktorvariable-weggelassen-wird" id="toc-was-passiert-wenn-eine-prädiktorvariable-weggelassen-wird" class="nav-link" data-scroll-target="#was-passiert-wenn-eine-prädiktorvariable-weggelassen-wird"><span class="header-section-number">18.2.2</span> Was passiert wenn eine Prädiktorvariable weggelassen wird?</a></li>
  </ul></li>
  <li><a href="#multikollinearität" id="toc-multikollinearität" class="nav-link" data-scroll-target="#multikollinearität"><span class="header-section-number">18.3</span> Multikollinearität</a>
  <ul class="collapse">
  <li><a href="#variance-inflation-factor-vif-in-r-berechnen" id="toc-variance-inflation-factor-vif-in-r-berechnen" class="nav-link" data-scroll-target="#variance-inflation-factor-vif-in-r-berechnen"><span class="header-section-number">18.3.1</span> Variance Inflation Factor (VIF) in <code>R</code> berechnen</a></li>
  <li><a href="#wenn-prädiktorvariablen-x_j-sich-gegenseitig-maskieren" id="toc-wenn-prädiktorvariablen-x_j-sich-gegenseitig-maskieren" class="nav-link" data-scroll-target="#wenn-prädiktorvariablen-x_j-sich-gegenseitig-maskieren"><span class="header-section-number">18.3.2</span> Wenn Prädiktorvariablen <span class="math inline">\(X_j\)</span> sich gegenseitig maskieren</a></li>
  </ul></li>
  <li><a href="#unter-der-motorhaube-von-lm-die-modellmatrix" id="toc-unter-der-motorhaube-von-lm-die-modellmatrix" class="nav-link" data-scroll-target="#unter-der-motorhaube-von-lm-die-modellmatrix"><span class="header-section-number">18.4</span> Unter der Motorhaube von <code>lm()</code> die Modellmatrix</a></li>
  <li><a href="#take-away" id="toc-take-away" class="nav-link" data-scroll-target="#take-away"><span class="header-section-number">18.5</span> Take-away</a></li>
  <li><a href="#zum-nacharbeiten" id="toc-zum-nacharbeiten" class="nav-link" data-scroll-target="#zum-nacharbeiten"><span class="header-section-number">18.6</span> Zum Nacharbeiten</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./mlm_title.html">Multiple Regression</a></li><li class="breadcrumb-item"><a href="./mlm_basics.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Einführung</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Einführung</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In den meisten Fällen in der Praxis liegt selten der einfache Fall vor, dass eine abhängige Variable mittels nur einer einzigen Prädiktorvariablen erklärt bzw. vorhergesagt werden soll. In den meisten Fällen liegt das Interesse darin den Zusammenhang mehrerer Prädiktorvariablen auf die abhängige Varible zu zu modellieren. Ein Beispiel aus der Literatur ist eine Untersuchung von <span class="citation" data-cites="debanne2011">Debanne und Laffaye (<a href="references.html#ref-debanne2011" role="doc-biblioref">2011</a>)</span> über den Zusammenhang zwischen der Wurfgeschwindigkeit in Abhängigkeit vom Körpergewicht und der Armspannweite im Handball. In <a href="#tbl-debanne-2011" class="quarto-xref">Tabelle&nbsp;<span>18.1</span></a> ist ein Ausschnitt aus dem Datensatz abgebildet.</p>
<div class="cell">
<div id="tbl-debanne-2011" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-debanne-2011-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;18.1: Datenausschnitt: Wurfgeschwindigkeit, Körpermasse und Armspannweite bei professionellen Handballern (angelehnt an Debanne &amp; Laffaye, 2011).
</figcaption>
<div aria-describedby="tbl-debanne-2011-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Velocity[m/s]</th>
<th style="text-align: right;">body mass[kg]</th>
<th style="text-align: right;">arm span[cm]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">15.8</td>
<td style="text-align: right;">70.7</td>
<td style="text-align: right;">189.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">17.2</td>
<td style="text-align: right;">63.7</td>
<td style="text-align: right;">182.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">18.3</td>
<td style="text-align: right;">76.2</td>
<td style="text-align: right;">192.1</td>
</tr>
<tr class="even">
<td style="text-align: right;">18.4</td>
<td style="text-align: right;">64.9</td>
<td style="text-align: right;">171.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">18.4</td>
<td style="text-align: right;">63.0</td>
<td style="text-align: right;">181.1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Im Prinzip ändert sich an der Art der Daten nichts gegenüber der einfachen Regression. Die Daten beinhalten lediglich nun eine weitere Spalten mit einer weiteren Prädiktorvariablen. Im Prinzip könnte der isolierte Einfluss der beiden Prädiktorvariablen Körpermasse und Armspannweite auf die abhängige Variable Wurfgeschwindigkeit einzeln untersucht werden. Allerdings ist oft von größerem Interesse zu untersuchen, wie sich der gemeinsame Einfluss der beiden Variablen zusammen verhält und ob durch die Kombination der beiden Variablen ein <em>besseres</em> Modell erstellt werden kann. Aus dieser Problemstellung heraus ergibt sich die Notwendigkeit von der einfachen linearen Regression zur <strong>multiple lineare Regression</strong> überzugehen. Formal geschieht dies einfach dadurch, dass die Formel der einfachen Regression mit dem Prädiktor <span class="math inline">\(X\)</span> um eine weitere oder eben mehrere Variablen erweitert wird. Dementsprechend wird aus:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]</span></p>
<p>die Formel für die multiple Regression mit:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \dots + \beta_K x_{Ki} + \epsilon_i
\]</span></p>
<p>Da bei der einfachen Regression nur eine einzige <span class="math inline">\(X\)</span>-Variable in der Formel vorhanden war, ist kein Index <span class="math inline">\(j\)</span> notwendig gewesen um die <span class="math inline">\(X\)</span>-Variablen voneinander zu unterscheiden. Bei der multiplen Regression mit mehreren Prädiktorvariablen <span class="math inline">\(X\)</span> wird jeder <span class="math inline">\(X\)</span> Variable ein zusätzlicher Index <span class="math inline">\(j\)</span> angehängt um die Variablen eindeutig identifizieren zu können. Per Konvention, wobei diese leider nicht global eingehalten wird, wird die <strong>Anzahl der Prädiktorvaiablen</strong> mit <span class="math inline">\(K\)</span> bezeichnet (oft auch <span class="math inline">\(p\)</span>). Der <span class="math inline">\(y\)</span>-Achsenabschnitt erhält wieder den Index <span class="math inline">\(j=0\)</span> und die weiteren Steigungskoeffzienten <span class="math inline">\(\beta_1\)</span> bis <span class="math inline">\(\beta_K\)</span> erhalten den Prädiktorvariablen <span class="math inline">\(X_j\)</span> folgend den entsprechenden Index.</p>
<p>In welcher Reihenfolge die Prädiktorvariablen mit <span class="math inline">\(j=1, j=2, \ldots, j=K\)</span> verteilt werden hat zunächst keine Auswirkung auf das Modell und regelt lediglich die Bezeichnung. In unserem konkreten Fall der Handballwurfdaten wäre zum Beispiel eine mögliche Zuordnung, das <span class="math inline">\(X_1\)</span> die Körpermasse und <span class="math inline">\(X_2\)</span> die Armspannweite kodiert.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(i\)</span></th>
<th style="text-align: right;">Velocity[m/s]</th>
<th style="text-align: right;">body mass[kg] <span class="math inline">\(j=1\)</span></th>
<th style="text-align: right;">arm span[cm] <span class="math inline">\(j=2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">15.8</td>
<td style="text-align: right;">70.7</td>
<td style="text-align: right;">189.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">17.2</td>
<td style="text-align: right;">63.7</td>
<td style="text-align: right;">182.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">18.3</td>
<td style="text-align: right;">76.2</td>
<td style="text-align: right;">192.1</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">18.4</td>
<td style="text-align: right;">64.9</td>
<td style="text-align: right;">171.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">18.4</td>
<td style="text-align: right;">63.0</td>
<td style="text-align: right;">181.1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Rein formal hat sich nun der Übergang zur multiple Regression bereits vollzogen. Die Frage die sich nun direkt anschließt bezieht sich auf die Bedeutung der Koeffizienten <span class="math inline">\(\beta_1, \ldots, \beta_k\)</span>. Sind diese ebenfalls als Steigungen einer Geraden zu interpretieren? Ebenso, wie lassen sich die anderen Konzepte die bereits im Rahmen der einfachen Regression behandelt wurden haben auf die multiple Regression übertragen? Zunächst aber noch ein Beispiel.</p>
<div id="exm-rowing-example-01" class="theorem example">
<p><span class="theorem-title"><strong>Beispiel 18.1</strong></span> In <span class="citation" data-cites="riechman2002">Riechman u.&nbsp;a. (<a href="references.html#ref-riechman2002" role="doc-biblioref">2002</a>)</span> wurde ein Modell erstellt um die Leistung beim 2000m Indoor-Rudern von 12 Wettkampfruderinnen anhand eines 30-Sekunden-Ruder-Sprints, der maximalen Sauerstoffaufnahme und der Ermüdung vorherzusagen. Die Autoren bestimmten das folgende Modell: <span class="math display">\[\begin{equation*}
Zeit_{\text{2000m}} = 567.29-0.163\cdot\text{Power }-14.213\cdot \dot{V}0_{2\text{max}} + 0.738\cdot\text{Fatigue}
\end{equation*}\]</span> Mit einem Standardfehler von <span class="math inline">\(\hat{\sigma} = 0.96\)</span>.</p>
</div>
<section id="bedeutung-der-koeffizienten-bei-der-multiplen-regression" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="bedeutung-der-koeffizienten-bei-der-multiplen-regression"><span class="header-section-number">18.1</span> Bedeutung der Koeffizienten bei der multiplen Regression</h2>
<p>Um die Bedeutung der Regressionskoeffzienten bei der multiple Regression besser zu verstehen ist es von Vorteil sich noch einmal die Bedeutung der Koeffizienten im einfachen Regressionsmodell zu vergegenwärtigen (siehe <a href="#fig-mlm-basics-simple" class="quarto-xref">Abbildung&nbsp;<span>18.1</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-basics-simple" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-basics-simple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-simple-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-basics-simple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;18.1: Beispiel für eine einfache Regression und der resultierenden Regressiongeraden
</figcaption>
</figure>
</div>
</div>
</div>
<p>Bei der einfachen Regression wurde mittels der Methode der kleinsten Quadrate eine Regressionsgerade durch die Punktwolke der Daten gelegt. Dabei wurde die Regressionsgerade so gewählt, dass die senkrechten Abstände der beobachteten Punkte von der Regressionsgerade minimiert werden bzw. die Abstände zwischen denen auf der Gerade liegenden, vorhergesagten Werte <span class="math inline">\(\hat{y}_i\)</span> und den beobachteten Wert <span class="math inline">\(Y_i\)</span> (Residuen). Wird nun der Übergang von einer Prädiktorvariablen zum nächstkomplizierteren Fall mit zwei Prädiktorvariablen <span class="math inline">\(X_1\)</span> und <span class="math inline">\(X_2\)</span> durchgeführt, dann ist eine mögliche Darstellungsform der Daten eine Punktwolke im dreidimensionalen Raum (siehe <a href="#fig-mlm-basics-scatter-1" class="quarto-xref">Abbildung&nbsp;<span>18.2 (a)</span></a>).</p>
<div id="fig-mlm-basics-scatter" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-basics-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-basics-scatter" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-basics-scatter-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-basics-scatter-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-scatter-1.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-basics-scatter" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-basics-scatter-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) 3D Punktwolke
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-basics-scatter" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-basics-scatter-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-basics-scatter-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-scatter-2.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-basics-scatter" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-basics-scatter-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) 3D Punktwolke mit gefitteter Ebene
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-basics-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;18.2: Punktwolken bei der multiple Regression
</figcaption>
</figure>
</div>
<p>Da jetzt eine einzelne Gerade nicht mehr ausreichend ist um die Daten zu fitten, wird nun eine <strong>Ebene</strong> durch die Punktwolke gelegt (siehe <a href="#fig-mlm-basics-scatter-2" class="quarto-xref">Abbildung&nbsp;<span>18.2 (b)</span></a>). Dieser Ansatz ermöglicht nun die gleiche Herangehensweise wie bei der einfachen linearen Regression anzuwenden. Als Zielgröße wird aus den möglichen Ebenen diejenigen Ebene gesucht, deren vorhergesagte, in der Ebene liegende, Punkte <span class="math inline">\(\hat{y}_i\)</span> die geringsten, senkrechten Abstand zu den tatsächlich beobachteten Punkten <span class="math inline">\(y_i\)</span> haben (wieder Residuen). Anders ausgedrückt, es wird diejenigen Ebene durch die Punktwolke gesucht deren Summe der quadrierten Residuen <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span> minimal ist. Die Definition der Residuen ist dabei genau gleich derjenigen bei der einfachen linearen Regression.</p>
<p>Diese Herangehensweise hat den Vorteil, dass sie zum einem die einfache lineare Regression als Spezialfall mit <span class="math inline">\(K=1\)</span> beinhaltet und sich beliebig erweitern lässt. Lediglich mit der Einschränkung, dass bei <span class="math inline">\(K&gt;2\)</span> die dreidimensionale Darstellung mittels einer Grafik nicht mehr möglich ist da nicht ausreichend Dimensionen dargestellt werden können. Das Prinzip der Minimierung der Abweichungen von <span class="math inline">\(\hat{y}_i\)</span> zu <span class="math inline">\(y\)</span> von einer Ebene bleibt aber weiter erhalten. D.h. alle Konzepte die im Rahmen der einfachen linearen Regression erarbeitet wurden, lassen sich direkt auf die multiple lineare Regression übertragen.</p>
<p>Zusammenfassend:</p>
<ul>
<li>Die Berechnungen beim Übergang von der einfachen zur multiplen Regression bleiben alle gleich</li>
<li>Die Abweichungen, die Residuen <span class="math inline">\(\hat{\epsilon_i}\)</span> sind nun nicht mehr Abweichungen von einer Gerade sondern von einer <span class="math inline">\(K\)</span>-dimensionalen Hyperebene. Die grundlegenden Eigenschaften der Residuen bleiben alle erhalten.</li>
<li>Die Modellannahmen bleiben alle gleich: Unabhängige <span class="math inline">\(y_i\)</span> und <span class="math inline">\(\epsilon_i \sim \mathcal{N}(0,\sigma^2)\)</span> iid</li>
<li>Inferenz für die Koeffizienten mittels <span class="math inline">\(t_k = \frac{\hat{\beta}_k}{s_k} \sim t(N-K-1)\)</span> bleiben erhalten und übertragen sich auf die Konfidenzintervalle</li>
<li>Alle Konzepte für die Vorhersage bleiben erhalten</li>
<li>Modelldiagnosetools bleiben ebenfalls alle erhalten</li>
</ul>
<p>Als nächster Schritt soll nun die Interpretation der Modellkoeffizienten im multiplen Regressionsmodell näher betrachtet werden. Dazu wird zunächst ein einfaches synthetisches Beispiel betrachtet, dass dem folgenden DGP zugrunde hat.</p>
<p><span class="math display">\[
\begin{gather}
y_i = \beta_0 + \beta_1 \cdot x_{1i} + \beta_2 \cdot x_{2i} + \epsilon_i \\
\beta_0 = 1 ,\beta_1 = 3, \beta_2 = 0.7 \\
\epsilon_i \sim N(0,\sigma = 0.5)
\end{gather}
\]</span></p>
<p>Übersetzt in <code>R</code> code bedeutet dies, unter der Annahme, dass <span class="math inline">\(x_1\)</span> und <span class="math inline">\(x_2\)</span> jeweils einer Gleichverteilung mit <span class="math inline">\(U(-2,2)\)</span> folgen. Die Annahme welcher Verteilung die beiden <span class="math inline">\(X\)</span>-Variablen folgen, ist nicht wirklich Missionskritisch, dient die Wahl doch lediglich der einfachen Generierung von Werten.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">50</span> <span class="co"># Anzahl Datenpunkte</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>beta_0 <span class="ot">&lt;-</span> <span class="dv">1</span>   <span class="co"># y-Achsenabschnitt</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>beta_1 <span class="ot">&lt;-</span> <span class="dv">3</span>   <span class="co"># 1. Steigungskoeffizient</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>beta_2 <span class="ot">&lt;-</span> <span class="fl">0.7</span> <span class="co"># 2. Steigungskoeffizient</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.5</span>  <span class="co"># Standardabweichung der Residuen</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">x1 =</span> <span class="fu">runif</span>(N, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">x2 =</span> <span class="fu">runif</span>(N, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> beta_0 <span class="sc">+</span> beta_1<span class="sc">*</span>x1 <span class="sc">+</span> beta_2<span class="sc">*</span>x2 <span class="sc">+</span> <span class="fu">rnorm</span>(N, <span class="dv">0</span>, sigma)) <span class="co"># DGP</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Die <em>Hauptlogik</em> in dem Codeschnipsel ist die Anweisung <code>y = beta_0 + beta_1*x1 + beta_2*x2 + rnorm(N, 0, sigma))</code> hier werden basierend auf den Modellparametern <code>beta_0</code>, <code>beta_1</code>, <code>beta_2</code> und <code>sigma</code> zufällige <span class="math inline">\(Y\)</span>-Wert erzeugt. Wenn die Prädiktorvariablen <span class="math inline">\(x_1\)</span> und <span class="math inline">\(x_2\)</span> gegen <span class="math inline">\(y\)</span> jeweils in einem Streudiagramm abtragen werden, werden die folgenden Abbildungen erhalten (siehe <a href="#fig-mlm-basics-example-01" class="quarto-xref">Abbildung&nbsp;<span>18.3</span></a>).</p>
<div id="fig-mlm-basics-example-01" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-basics-example-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-basics-example-01" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-basics-example-01-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-basics-example-01-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-example-01-1.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-basics-example-01" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-basics-example-01-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Streudiagramm <span class="math inline">\(y\)</span> gegen <span class="math inline">\(x_1\)</span>
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mlm-basics-example-01" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlm-basics-example-01-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mlm-basics-example-01-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-example-01-2.png" class="img-fluid figure-img" data-ref-parent="fig-mlm-basics-example-01" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mlm-basics-example-01-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Streudiagramm <span class="math inline">\(y\)</span> gegen <span class="math inline">\(x_2\)</span>
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-basics-example-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;18.3: Streudiagramme der einfachen Zusammenhänge für das Beispiel.
</figcaption>
</figure>
</div>
<p>Der Zusammenhang zwischen <span class="math inline">\(x_1\)</span> und <span class="math inline">\(y\)</span> ist ziemlich deutlich in der Abbildung zu sehen (siehe <a href="#fig-mlm-basics-example-01-1" class="quarto-xref">Abbildung&nbsp;<span>18.3 (a)</span></a>). Dagegen ist der Zusammenhang im Streudiagramm für <span class="math inline">\(x_2\)</span> gegen <span class="math inline">\(y\)</span> nicht ganz so eindeutig (siehe <a href="#fig-mlm-basics-example-01-2" class="quarto-xref">Abbildung&nbsp;<span>18.3 (b)</span></a>). Dies ist eine Folge der (willkürlichen) Wahl der beiden Modellkoeffizienten <span class="math inline">\(\beta_1 = 3\)</span> und <span class="math inline">\(\beta_2 = 0.7\)</span> im Zusammenhang mit einer Varianz von <span class="math inline">\(\sigma^2 = 0.5^2\)</span>. Nun wird ein Modell mittels der <code>lm()</code>-Funktion in <code>R</code> an die Daten angepasst. Die beiden Variablen <span class="math inline">\(x_1\)</span> und <span class="math inline">\(x_2\)</span> gehen dem DGP folgend <strong>additiv</strong> in das Modell ein. Dies für zu der folgenden Modellformulierung für <code>lm()</code> <code>y ~ x1 + x2</code> (Tip: Im Kapitel zur einfachen Regression ist ein kurzer Primer zur Modellformulierung).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, df)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Das gefittete Modell kann nun wie üblich mittels <code>summary()</code> inspiziert werden. Insbesondere können hier, wie üblich, die berechneten Modellkoeffizienten <span class="math inline">\(\beta_0, \beta_1\)</span> und <span class="math inline">\(\beta_2\)</span> betrachtet werden. Der Übersicht halber sind in der folgenden Tabelle (siehe <a href="#tbl-mlm-basics-example-01" class="quarto-xref">Tabelle&nbsp;<span>18.2</span></a>) nur die Modellparameter und deren Standardfehler angezeigt.</p>
<div class="cell">
<div id="tbl-mlm-basics-example-01" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-basics-example-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;18.2: Modellkoeffizienten für das Beispiel.
</figcaption>
<div aria-describedby="tbl-mlm-basics-example-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<caption>Modellfit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.077</td>
<td style="text-align: right;">0.066</td>
</tr>
<tr class="even">
<td style="text-align: left;">x1</td>
<td style="text-align: right;">2.965</td>
<td style="text-align: right;">0.056</td>
</tr>
<tr class="odd">
<td style="text-align: left;">x2</td>
<td style="text-align: right;">0.708</td>
<td style="text-align: right;">0.060</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\hat{\sigma}\)</span></td>
<td style="text-align: right;">0.460</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In <a href="#tbl-mlm-basics-example-01" class="quarto-xref">Tabelle&nbsp;<span>18.2</span></a> ist zu sehen, dass die anhand der Daten berechneten Koeffizienten diejenigen des DGP sehr gut reproduziert haben. Die Wert sind nicht perfekt diejenigen diejenigen die im DGP verwendet wurden, dies ist aber auf Grund der Stichprobenvariabilität nicht zu erwarten. Insgesamt sollte dieses Ergebnis jedoch beruhigend wirken, da es zeigt, dass die multiple Regression in der Lage ist die <em>wahren</em> Modellparameter im Rahmen der Stichprobenunsicherheit abschätzen zu können. Die einzige Neuerung im Gegensatz zur einfachen linearen Regression ist die Erweiterung um einer weitere Variablen <span class="math inline">\(X_2\)</span> und operativ die Erweiterung in <code>R</code> um den Term <code>+ x2</code> in der Formel für <code>lm()</code>.</p>
<p>Die Interpretation von <span class="math inline">\(\beta_1\)</span> ist gleich derjenigen bei der einfachen linearen Regression allerdings mit einer kleinen Erweiterung. Zwei Objekte die sich in <span class="math inline">\(x_1\)</span> um eine Einheit voneinander unterscheiden und den gleichen Wert in <span class="math inline">\(x_2\)</span> haben, unterscheiden sich in der abhängigen Variablen <span class="math inline">\(y\)</span> um den Steigungskoeffizienten <span class="math inline">\(\beta_1\)</span>. Die gleiche Interpretation mit den Rollen vertauscht trifft ebenfalls auf <span class="math inline">\(\beta_2\)</span> zu. Zwei Objekte die sich in <span class="math inline">\(x_2\)</span> um eine Einheit unterscheiden und den gleichen Wert für <span class="math inline">\(x_1\)</span> haben unterscheiden sich in <span class="math inline">\(y\)</span> um <span class="math inline">\(\beta_2\)</span>.</p>
<p>Im nächsten Schritt soll nun betrachtet werden, wie die Koeffizienten zustandekommen und wie die Koeffizienten zu interpretieren sind.</p>
</section>
<section id="interpretation-der-modellkoeffizienten" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="interpretation-der-modellkoeffizienten"><span class="header-section-number">18.2</span> Interpretation der Modellkoeffizienten</h2>
<p>Die Interpretation von <span class="math inline">\(\beta_0\)</span> ist vollkommen identisch mit derjenigen bei der einfachen linearen Regression. Bei der einfachen linearen Regression bedeutete der Koeffizient <span class="math inline">\(\beta_0\)</span> derjenige Wert, den das Modell annimmt, der vorhergesagte Wert <span class="math inline">\(\hat{Y}\)</span>, wenn die Prädiktorvariable <span class="math inline">\(X\)</span> den Wert <span class="math inline">\(0\)</span> annimmt. Graphisch ist dies der <span class="math inline">\(y\)</span>-Achsenabschnitt. Bei der multiplen Regression bleibt diese Interpretation erhalten und <span class="math inline">\(\beta_0\)</span> ist nun der Wert <span class="math inline">\(\hat{Y}\)</span> wenn <strong>alle</strong> Prädiktorvariablen den Wert <span class="math inline">\(0\)</span> annehmen. Graphisch ist dies der Schnittpunkt der Modellebene mit der <span class="math inline">\(y\)</span>-Achse, also ebenfalls der <span class="math inline">\(y\)</span>-Achsenabschnitt (siehe <a href="#fig-mlm-basics-scatter-2" class="quarto-xref">Abbildung&nbsp;<span>18.2 (b)</span></a>).</p>
<p>Die Interpretation der Modellkoeffizienten <span class="math inline">\(\beta_1, \beta_2, \ldots, \beta_K\)</span> bleibt zunächst auch gleich derjenigen aus der einfachen Regression. Der Koeffizient <span class="math inline">\(\beta_j, (j\neq0)\)</span> gibt den Unterschied zwischen zwei Objekten an die sich um eine Einheit bezüglich der Variablen <span class="math inline">\(X_j\)</span> unterscheiden. Was dabei aber etwas unklar bleibt, ist wie sich die Werte der anderen Prädiktorvariablen verhalten und welchen Einfluss diese auf diese Aussage haben?</p>
<p>Um diesen Zusammenhang besser zu verstehen ist zunächst eine kleine Detour notwendig. Zunächst wird eine einfache lineare Regression der beiden Prädiktorvariablen berechnet. Die Variable <span class="math inline">\(X_1\)</span> wird durch <span class="math inline">\(X_2\)</span> modelliert. D.h. es wird der Teil der Varianz von <span class="math inline">\(X_1\)</span> der durch einen linearen Zusammenhang mit <span class="math inline">\(X_2\)</span> erklärt werden. Dies führt zu folgendem Modell:</p>
<p><span class="math display">\[
x_{1i} = \beta_0 + \beta_1 x_{2i} + \epsilon_i
\]</span></p>
<p>Anhand dieses Modells kann nun die Frage gestellt werden: Wenn <span class="math inline">\(X_2\)</span> bekannt ist, wie viel Information wird dadurch über <span class="math inline">\(X_1\)</span> erhalten werden? In dem Fall, dass ein perfekter linearer Zusammenhang zwischen <span class="math inline">\(X_1\)</span> und <span class="math inline">\(X_2\)</span> besteht dann wäre die Information von <span class="math inline">\(X_2\)</span> über <span class="math inline">\(X_1\)</span> ebenfalls perfekt. Für einen gegeben Wert von <span class="math inline">\(X_2\)</span> hat, könnte der entsprechende Wert für <span class="math inline">\(X_1\)</span> berechnet werden. Entsprechend umso schwächer der lineare Zusammenhang zwischen <span class="math inline">\(X_1\)</span> und <span class="math inline">\(X_2\)</span> ist, umso weniger Information besitzt <span class="math inline">\(X_2\)</span> über <span class="math inline">\(X_1\)</span>.</p>
<p>Nun können aber mit Hilfe des Regressionsmodell von <span class="math inline">\(X_1\)</span> gegen <span class="math inline">\(X_2\)</span> die Residuen <span class="math inline">\(e_i\)</span> berechnet werden. Aus Sicht der Information von <span class="math inline">\(X_2\)</span> über <span class="math inline">\(X_1\)</span>, können diese interpretieren werden. Die Residuen <span class="math inline">\(e_i\)</span> beziffern genau denjenigen Teil der Varianz von <span class="math inline">\(X_1\)</span> der nicht mit Hilfe des Regressionsmodells von <span class="math inline">\(X_1\)</span> gegen <span class="math inline">\(X_2\)</span> erklärt werden kann. D.h. die Residuen <span class="math inline">\(e_i\)</span> repräsentieren aus dieser Sichtweise die Varianz von <span class="math inline">\(X_1\)</span> die um denjenigen Anteil von <span class="math inline">\(X_2\)</span> bereinigt wurde. Die Residuen <span class="math inline">\(e_i\)</span> bleiben sozusagen übrig wenn die Information von <span class="math inline">\(X_2\)</span> aus <span class="math inline">\(X_1\)</span> herausgenommen wird.</p>
<p><span id="eq-mlm-basics-coef-01"><span class="math display">\[
e_i = x_{1i} - \beta_0 - \beta_1 x_{2i}
\tag{18.1}\]</span></span></p>
<p>Nochmal, die Residuen <span class="math inline">\(e_i\)</span> stellen denjenigen Teil der Varianz von <span class="math inline">\(X_1\)</span> dar, der sich nicht durch <span class="math inline">\(X_2\)</span> vorhersagen lässt. Eben derjenige Teil der Varianz von <span class="math inline">\(X_1\)</span> der um den Teil von <span class="math inline">\(X_2\)</span> <em>bereinigt</em> wurde. Die Residuen <span class="math inline">\(e_i\)</span> aus <a href="#eq-mlm-basics-coef-01" class="quarto-xref">Gleichung&nbsp;<span>18.1</span></a> werden nun als eine neue Prädiktorvariablen <span class="math inline">\(x_{1i}^*\)</span> verwendet. Formal:</p>
<p><span class="math display">\[
x_{1i^*} = e_i
\]</span></p>
<p>Im nächsten Schritt wird nun diese <em>neue</em> Prädiktorvariable <span class="math inline">\(x_1^*\)</span> verwendet um eine einfache lineare Regression von <span class="math inline">\(Y\)</span> gegen <span class="math inline">\(x_1^*\)</span> durchzuführen.</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{1i}^*
\]</span></p>
<p>In <code>R</code> können diese Schritte entsprechend mit <code>lm()</code> durchgeführt werden. Zunächst die Regression von <span class="math inline">\(X_1\)</span> gegen <span class="math inline">\(X_2\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mod_x1_star<span class="ot">&lt;-</span> <span class="fu">lm</span>(x1 <span class="sc">~</span> x2, df)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Das Modell <code>mod_x1_star</code> beinhaltet das Modell von <span class="math inline">\(X_1\)</span> gegen <span class="math inline">\(X_2\)</span>. Im nächsten Schritt nun die Berechnung der Residuen <span class="math inline">\(e_i\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>x1_star <span class="ot">&lt;-</span> <span class="fu">resid</span>(mod_x1_star)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Diese sind jetzt einer neuen Variable <code>x1_star</code> zugewiesen worden. Diese Variable wird nun verwendet um eine Regression gegen <span class="math inline">\(Y\)</span> zu rechnen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mod_y_x1_star <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1_star, df)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Das Modell ist nun <code>mod_y_x1_star</code> zugewiesen. Bei Betrachtung der Modellkoeffizienten werden die folgenden Wert erhalten (siehe <a href="#tbl-mlm-basics-example-02" class="quarto-xref">Tabelle&nbsp;<span>18.3</span></a>):</p>
<div class="cell">
<div id="tbl-mlm-basics-example-02" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-basics-example-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;18.3: Modellkoefizienten von <span class="math inline">\(y\)</span> gegen <span class="math inline">\(x_1^*\)</span>.
</figcaption>
<div aria-describedby="tbl-mlm-basics-example-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<caption>Modellfit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.250</td>
<td style="text-align: right;">0.164</td>
</tr>
<tr class="even">
<td style="text-align: left;">x1_star</td>
<td style="text-align: right;">2.965</td>
<td style="text-align: right;">0.141</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Der Steigungskoeffizient <span class="math inline">\(\beta_1\)</span> hat genau den gleichen Wert wie in dem Modell aus der multiplen linear Regression mit beiden Variablen (siehe <a href="#tbl-mlm-basics-example-01" class="quarto-xref">Tabelle&nbsp;<span>18.2</span></a>).</p>
<p>Der Ansatz funktioniert genau gleich wenn anstatt <span class="math inline">\(x_{1i}^*\)</span> wenn <span class="math inline">\(x_{2i}^*\)</span> Berechnet wird indem eine einfache linear Regression von <span class="math inline">\(X_2\)</span> gegen <span class="math inline">\(X_1\)</span> berechnet wird und deren Residuen verwendet werden um <span class="math inline">\(Y\)</span> zu modellieren.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mod_x2_star <span class="ot">&lt;-</span> <span class="fu">lm</span>(x2 <span class="sc">~</span> x1, df)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>x2_star <span class="ot">&lt;-</span> <span class="fu">resid</span>(mod_x2_star)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>mod_y_x2_star <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x2_star, df)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mod_y_x2_star)[<span class="dv">2</span>]</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  x2_star 
0.7081505 </code></pre>
</div>
</div>
<p>Wieder ist der Wert für den Steigungskoeffizienten <span class="math inline">\(\beta_2\)</span> aus dem Modell der Gleiche wie bei dem multiplen Regressionmodell mit beiden Variablen.</p>
<p>Das gleiche Prinzip greift auch für mehr als zwei Prädiktorvariablen. Der einzige Unterschied ist, dass in diesem Fall nicht mehr einer Regression der Variable <span class="math inline">\(X_i\)</span> gegen eine andere <span class="math inline">\(X_j\)</span> Prädiktorvariable berechnet wird, sondern es wird eine multiple Regression von <span class="math inline">\(X_i\)</span> gegen <strong>alle anderen</strong> Prädiktorvariablen <span class="math inline">\(X_j, j = 1, i-1,i+1,K\)</span> berechnet. Die Residuen aus diesem Modell können dann wieder für eine einfache Regression gegen <span class="math inline">\(Y\)</span> verwendet werden und der Steigungskoeffizient ist wieder gleich demjenigen der im multiplen Regressionsmodell berechnet wird.</p>
<p>Insgesamt folgt daraus die folgende Interpretation der Steigungskoeffizienten <span class="math inline">\(\beta_i\)</span> im multiplen Regressionsmodell:</p>
<p>Der Steigungskoeffizient <span class="math inline">\(\beta_i\)</span> drückt die Information der Variable <span class="math inline">\(X_i\)</span> aus, wenn der gemeinsame Anteil von <span class="math inline">\(X_i\)</span> mit allen anderen Prädiktorvariablen <span class="math inline">\(X_j, j \neq i\)</span> rausgerechnet, <em>bereinigt</em>, wurde. Anders ausgedrückt: Welche zusätzliche Information wird erhalten , wenn die Variable <span class="math inline">\(X_i\)</span> in das Modell integriert wird, wenn schon alle anderen Variablen <span class="math inline">\(X_j, j \neq i\)</span> im Modell enthalten sind. D.h., das multiple Regressionsmodell kontrolliert automatisch immer den Einfluss der anderen <span class="math inline">\(K-1\)</span> Variablen bei der Betrachtung der Variablen <span class="math inline">\(x_i\)</span>. Nochmal als Liste:</p>
<ul>
<li><span class="math inline">\(\hat{\beta}_1\)</span>: Wenn <span class="math inline">\(X_2\)</span> bekannt ist, welche zusätzlichen Informationen wird durch <span class="math inline">\(X_1\)</span> über <span class="math inline">\(Y\)</span> erhalten.</li>
<li><span class="math inline">\(\hat{\beta}_2\)</span>: Wenn <span class="math inline">\(X_1\)</span> bekannt ist, welche zusätzlichen Informationen wird durch <span class="math inline">\(X_2\)</span> über <span class="math inline">\(Y\)</span> erhalten.</li>
</ul>
<p>Bezogen auf die Werte der Steigungskoeffzienten <span class="math inline">\(\beta_i\)</span> ist die Bedeutung immer noch wie oben, wenn sich zwei Objekte auf der Variablen <span class="math inline">\(X_i\)</span> um eine Einheit voneinander unterscheiden und alle anderen Variablen den gleichen Wert haben, dann unterscheiden sich die erwarteten (vorhergesagten) Werte <span class="math inline">\(\hat{y}_i\)</span> laut des Modells um <span class="math inline">\(\beta_i\)</span>.</p>
<p>Die Eigenschaft, dass die anderen Variablen <span class="math inline">\(X_j\)</span> konstant gehalten werden ist dabei auch das Problem wenn ein einfaches Streudiagramm <span class="math inline">\(Y_i\)</span> gegen <span class="math inline">\(X_i\)</span> bei einer multiplen linearen Regression wie in <a href="#fig-mlm-basics-example-01" class="quarto-xref">Abbildung&nbsp;<span>18.3</span></a> erstellt wird. In <a href="#fig-mlm-basics-example-01-1" class="quarto-xref">Abbildung&nbsp;<span>18.3 (a)</span></a> kann der Einfluss von <span class="math inline">\(X_1\)</span> gut identifiziert, da der Steigungskoeffizient <span class="math inline">\(\beta_1\)</span> im Verhältnis zu <span class="math inline">\(\sigma\)</span> recht groß ist. Im Falle von <a href="#fig-mlm-basics-example-01-2" class="quarto-xref">Abbildung&nbsp;<span>18.3 (b)</span></a> ist dies nicht der Fall. Ein Möglichkeit trotzdem mit Hilfe von einfachen Streudiagrammen den isolierten Zusammenhang der Prädiktorvariablen <span class="math inline">\(X_i\)</span> auf die abhängige <span class="math inline">\(Y_i\)</span> zu untersuchen bieten sogenannte added-variable plots.</p>
<section id="added-variable-plots" class="level3" data-number="18.2.1">
<h3 data-number="18.2.1" class="anchored" data-anchor-id="added-variable-plots"><span class="header-section-number">18.2.1</span> Added-variable plots</h3>
<p>Die Idee hinter den sogenannten <em>added-variable plots</em> basiert auf der gleichen Herangehensweise wie eben in Bezug der Berechnung einer Variable <span class="math inline">\(X_{i}^*\)</span> mittels der Residuen <span class="math inline">\(e_i\)</span>. Neben der Bereinigung von <span class="math inline">\(X_1\)</span> aus <span class="math inline">\(X_2\)</span>, die eben bereits verwendet wurde, wird zusätzlich auch noch der Einfluss von <span class="math inline">\(X_1\)</span> aus <span class="math inline">\(Y\)</span> herausgerechnet. Dazu wird wieder eine einfache lineare Regression von <span class="math inline">\(Y\)</span> gegen <span class="math inline">\(X_1\)</span> berechnet und die resultierenden Residuen werden verwendet. Die beiden resultierenden Variablen werden dann in einem Streudiagramm dargestellt. In <code>R</code> kann ein added-varaible plot mittels des folgenden Ansatzes erzeugt werden (siehe <a href="#fig-mlm-basics-avplot-01" class="quarto-xref">Abbildung&nbsp;<span>18.4</span></a>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>y_star <span class="ot">&lt;-</span> <span class="fu">resid</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x1, df))   <span class="co"># Bereinigugn von y um x1</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>x2_star <span class="ot">&lt;-</span> <span class="fu">resid</span>(<span class="fu">lm</span>(x2 <span class="sc">~</span> x1, df)) <span class="co"># Bereinigung von x2 um x1</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">tibble</span>(x2_star, y_star),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(x2_star,y_star)) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'x2 | x1'</span>, <span class="at">y =</span> <span class="st">'y | x1'</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-mlm-basics-avplot-01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-basics-avplot-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-avplot-01-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-basics-avplot-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;18.4: Zusammenhang zwischen <span class="math inline">\(y\)</span> und <span class="math inline">\(x_2\)</span> bereinigt um den Einfluß von <span class="math inline">\(x_1\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Der Zusammenhang zwischen <span class="math inline">\(X_2\)</span> und <span class="math inline">\(Y\)</span> ist nun viel deutlicher zu sein, als dies in <a href="#fig-mlm-basics-example-01-2" class="quarto-xref">Abbildung&nbsp;<span>18.3 (b)</span></a> der Fall war. Im Paket <code>car</code> gibt es eine Funktion <code>avPlots()</code> mit der added-variable plots auch direkt erstellt werden können.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">avPlots</span>(mod)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mlm_basics_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Wenn eine multiple Regression mit mehr als zwei Prädiktorvariablen gerechnet wird, dann werden im added-variable plot jeweils alle <span class="math inline">\(K-1\)</span> Variablen aus <span class="math inline">\(x_i\)</span> und <span class="math inline">\(y\)</span> herausgerechnet. D.h. <span class="math inline">\(Y\)</span> und <span class="math inline">\(X_i\)</span> werden um den Einfluss aller, verbleibenden <span class="math inline">\(X_j, j \neq i\)</span> bereinigt. Die Darstellung von added-variable plots ist daher im Zusammenhang einer multiplen Regressionsanalyse immer von Vorteil um den Einfluss einzelner Variablen auf die abhängige Variable zu beurteilen.</p>
<p>Da ein Steigungskoeffizientt <span class="math inline">\(\beta_i\)</span> immer den Beitrag der Information von <span class="math inline">\(X_i\)</span> über denjenigen der anderen Prädiktorvariablen hinaus bestimmt, stellt sich die Frage was passiert wenn im Modell eine oder mehrere Prädiktorvariablen weggelassen werden.</p>
</section>
<section id="was-passiert-wenn-eine-prädiktorvariable-weggelassen-wird" class="level3" data-number="18.2.2">
<h3 data-number="18.2.2" class="anchored" data-anchor-id="was-passiert-wenn-eine-prädiktorvariable-weggelassen-wird"><span class="header-section-number">18.2.2</span> Was passiert wenn eine Prädiktorvariable weggelassen wird?</h3>
<p>In <a href="#tbl-mlm-basics-modelfit-01" class="quarto-xref">Tabelle&nbsp;<span>18.4</span></a> sind noch mal die Koeffizienten aus dem Beispiel abgebildet.</p>
<div class="cell">
<div id="tbl-mlm-basics-modelfit-01" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-basics-modelfit-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;18.4: Koeffizienten im Beispielmodell.
</figcaption>
<div aria-describedby="tbl-mlm-basics-modelfit-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<caption>Modellfit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(s_e\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.077</td>
<td style="text-align: right;">0.066</td>
</tr>
<tr class="even">
<td style="text-align: left;">x1</td>
<td style="text-align: right;">2.965</td>
<td style="text-align: right;">0.056</td>
</tr>
<tr class="odd">
<td style="text-align: left;">x2</td>
<td style="text-align: right;">0.708</td>
<td style="text-align: right;">0.060</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Was passiert nun, wenn anstatt einer multiplen Regression mit beiden Prädiktorvariablen zwei Einzelmodelle als einfache lineare Regression gefittet werden. Die Modell enthalten dabei jeweils mit eine der Prädiktorvariablen? Bleiben die Werte der Koeffizienten gleich derjenigen im multiplen Regressionsmodell? Dazu wird erst einmal das Modell mit nur der Prädiktorvariablen <span class="math inline">\(X_1\)</span> berechnet:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x1, df))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)          x1 
   1.007466    3.017589 </code></pre>
</div>
</div>
<p>Im Vergleich zum multiplen Regressionsmodell (siehe <a href="#tbl-mlm-basics-modelfit-01" class="quarto-xref">Tabelle&nbsp;<span>18.4</span></a>) hat sich der Modellkoeffizient verändert. Die Größe des Werts ist zwar in einem ähnlichen Bereich, die Werte sind aber nicht genau gleich. Das Gleiche nun für <span class="math inline">\(X_2\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x2, df))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)          x2 
  1.3377771   0.9555316 </code></pre>
</div>
</div>
<p>Wieder ist der Wert des Modellskoeffizient anders als derjenige im multiplen Regressionsmodell (siehe <a href="#tbl-mlm-basics-modelfit-01" class="quarto-xref">Tabelle&nbsp;<span>18.4</span></a>). Wieder ist die Größenordnung des Wertes aber ähnlich. Aus Sicht der vorgehenden Ausführungen betrachtet, deutet die Veränderung der Werte darauf hin, dass die Information die die Prädiktorvariablen über <span class="math inline">\(Y\)</span> aussagen sich ändert wenn die jeweils andere Variable im Modell enthalten ist.</p>
<p>Wird nochmal die der DGP der Daten betrachtet, könnte eingewendet, dass in diesem Beispiel, per Konstruktion des DGPs <span class="math inline">\(X_1\)</span> und <span class="math inline">\(X_2\)</span> eigentlich unabhängig voneinander sollten. Als die die Daten generiert wurden, wurden jeweils zwei unabhängige Zufallszahlenmengen erstellt. Eine Antwort auf dieses Problem liefert eine kurze Betrachtung der Korrelation zwischen den beiden Variablen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(df),<span class="dv">3</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      x1    x2     y
x1 1.000 0.078 0.969
x2 0.078 1.000 0.289
y  0.969 0.289 1.000</code></pre>
</div>
</div>
<p>Es ist zu sehen, dass <span class="math inline">\(x_1\)</span> und <span class="math inline">\(x_2\)</span> miteinander korrelieren, zwar nur leicht aber die Korrelation ist nicht exakt <span class="math inline">\(=0\)</span>. D.h. <span class="math inline">\(x_1\)</span> enthält rein durch Zufall etwas Informationen über <span class="math inline">\(x_2\)</span>. Dementsprechend ändern sich die Beiträge der Variablen zu <span class="math inline">\(y\)</span> in Abhängigkeit davon ob die jeweils andere Variable ebenfalls im Modell enthalten ist oder eben nicht. Die Änderungen sind dabei wie oben zu sehen war nur sehr gering.</p>
</section>
</section>
<section id="multikollinearität" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="multikollinearität"><span class="header-section-number">18.3</span> Multikollinearität</h2>
<p>Sei nun ein anderer Datensatz betrachtet <span class="citation" data-cites="kutner2005">(Beispiel aus <a href="references.html#ref-kutner2005" role="doc-biblioref">Kutner u.&nbsp;a. 2005</a>)</span>. Im Rahmen einer Untersuchung sind Körperfettmessungen durchgeführt an <span class="math inline">\(20\)</span> Personen durchgeführt worden. Neben einer Gesamtkörpermessung wurde auch der Körperfettanteil am Oberarm, Unterarm und am Oberschenkel bestimmt. In <a href="#tbl-mlm-basics-bodyfat-01" class="quarto-xref">Tabelle&nbsp;<span>18.5</span></a> ist ein Ausschnitt der Daten abgebildet.</p>
<div class="cell">
<div id="tbl-mlm-basics-bodyfat-01" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-basics-bodyfat-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;18.5: Ausschnitt der Körperfettdaten [%]
</figcaption>
<div aria-describedby="tbl-mlm-basics-bodyfat-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Oberarm</th>
<th style="text-align: right;">Unterarm</th>
<th style="text-align: right;">Oberschenkel</th>
<th style="text-align: right;">Gesamt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">19.5</td>
<td style="text-align: right;">43.1</td>
<td style="text-align: right;">29.1</td>
<td style="text-align: right;">11.9</td>
</tr>
<tr class="even">
<td style="text-align: right;">24.7</td>
<td style="text-align: right;">49.8</td>
<td style="text-align: right;">28.2</td>
<td style="text-align: right;">22.8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">30.7</td>
<td style="text-align: right;">51.9</td>
<td style="text-align: right;">37.0</td>
<td style="text-align: right;">18.7</td>
</tr>
<tr class="even">
<td style="text-align: right;">29.8</td>
<td style="text-align: right;">54.3</td>
<td style="text-align: right;">31.1</td>
<td style="text-align: right;">20.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">19.1</td>
<td style="text-align: right;">42.2</td>
<td style="text-align: right;">30.9</td>
<td style="text-align: right;">12.9</td>
</tr>
<tr class="even">
<td style="text-align: right;">25.6</td>
<td style="text-align: right;">53.9</td>
<td style="text-align: right;">23.7</td>
<td style="text-align: right;">21.7</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Als Modell sollen der Gesamtkörperfettanteil mit Hilfe der drei verschiedenen Messungen bestimmt werden.</p>
<p><span class="math display">\[
Y_{\text{Körperfettanteil}} = \beta_0 + \beta_1 \cdot X_{\text{Oberarm}} + \beta_2 \cdot X_{\text{Unterarm}} + \beta_3 \cdot X_{\text{Oberschenkel}} + \epsilon
\]</span></p>
<p>Um die Daten besser zu verstehen wird zunächst betrachtet, wie stark die Werte miteinander korrelieren. Dazu wird die Funktion <code>ggpairs()</code> aus dem <code>GGally</code> Paket. Diese ermöglicht mit wenig Aufwand eine übersichtliche Darstellung der Korrelation eines tibbles (siehe <a href="#fig-mlm-basics-bodyfat-01" class="quarto-xref">Abbildung&nbsp;<span>18.5</span></a>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggpairs</span>(bodyfat) </span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-mlm-basics-bodyfat-01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-basics-bodyfat-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-bodyfat-01-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-basics-bodyfat-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;18.5: Korrelationsmatrize der Körperfettdaten
</figcaption>
</figure>
</div>
</div>
</div>
<p>Wie bei Körperfettwerten nicht anders zu erwarten, korrelieren die Prädiktorvariablen relativ stark miteinander. Die Korrelation zwischen den Oberschenkeldaten und den Oberarmdaten in dieser Stichprobe ist sogar <span class="math inline">\(&gt;0.9\)</span>. Die Frage ist nun, wie sich diese Korrelation auf den Modellfit auswirkt, wenn nur Teilmengen der Prädiktorvariablen zur Anpassung verwenden werden. Insgesamt können vier verschiedene Modelle verwendet werden. Ein Modell mit allen Prädiktorvariablen und drei weitere Modelle bei denen wir jeweils eine der Prädiktorvariablen weglassen. In <code>R</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alle drei Prädiktoren</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>mod_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_fat <span class="sc">~</span> triceps <span class="sc">+</span> thigh <span class="sc">+</span> midarm, bodyfat)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ohne Arm</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>mod_wo_midarm <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_fat <span class="sc">~</span> triceps <span class="sc">+</span> thigh, bodyfat)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Ohne Oberschenkel</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>mod_wo_thigh <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_fat <span class="sc">~</span> triceps <span class="sc">+</span> midarm, bodyfat)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Ohne Triceps</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>mod_wo_triceps <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_fat <span class="sc">~</span> thigh <span class="sc">+</span> midarm, bodyfat)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In <a href="#tbl-mlm-basics-bodyfat-02" class="quarto-xref">Tabelle&nbsp;<span>18.6</span></a> sind nur die Steigungskoeffizienten für die vier verschiedenen Modell abgebildet.</p>
<div class="cell">
<div id="tbl-mlm-basics-bodyfat-02" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-basics-bodyfat-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;18.6: Koeffizienten der vier verschiedenen Modellen zu den Körperfettdaten.
</figcaption>
<div aria-describedby="tbl-mlm-basics-bodyfat-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Oberarm</th>
<th style="text-align: right;">Oberschenkel</th>
<th style="text-align: right;">Unterarm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alle</td>
<td style="text-align: right;">4.33</td>
<td style="text-align: right;">-2.86</td>
<td style="text-align: right;">-2.19</td>
</tr>
<tr class="even">
<td style="text-align: left;">ohne Unterarm</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">ohne Oberschenkel</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">-0.43</td>
</tr>
<tr class="even">
<td style="text-align: left;">ohne Oberarm</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">0.10</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Es ist zu beobachten, dass für diese Daten die Werte der Modellkoeffizienten sich sehr stark ändern in Abhängigkeit von welche Variablen in dem Modell enthalten sind. Beispielsweise änder der Koeffizient für den Oberschenkel nicht nur seine Größe sondern auch sein Vorzeichen, je nachdem ob der Ober- oder der Unterarm oder beide im Modell enthalten sind. D.h. durch die Korrelation der Prädiktorvariablen untereinander kommt es dazu, dass die Modellkoeffizienten sehr stark schwanken in Abhängigkeit von der Variablenkombination. Wird dies wieder aus der Sicht der Information betrachtet ist dieser Effekt eigentlich auch zu erwarten. Die Interpretation der Modellkoeffizienten bei der multiplen Regression war oben hergeleitet als, wie viel Information die <em>neue</em> Variablen liefert nachdem die anderen Variablen schon im Modell berücksichtigt wurden. Wenn die Variablen nun sehr stark miteinander korrelieren, dann bringt eine neue Variable wenige <em>neue Information</em> in das Modell über diejenige Information die schon durch die anderen Variablen repräsentiert wird. D.h. bei der multiplen Regression ist die Betrachtung der Beziehung der Prädiktorvariablen miteinander wichtig bei der Beurteilung des Modells. Dieses Konzept ist so wichtig, dass es einen eigenen Namen bekommt. Wenn mehrere Variablen in einem Modell miteinander korrelieren, dann wird dies als <strong>Multikollinearität</strong> bezeichnet.</p>
<div id="def-multicollinearity" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 18.1 (Multikollinearität)</strong></span> Wenn in einem Modell Prädiktorvariablen miteinander korrelieren, dann wird dies als Multikollinearität bezeichnet.</p>
</div>
<p>Multikollinearität hat verschiedene Einflüsse auf das Modell die sich vor allem hinsichtlich der Stabilität der Koeffizienten auswirken, wenn Prädiktorvariablen aus dem Modell herausgenommen werden bzw. dazugenommen werden. Dazu beeinflusst Multikollinearität auch die Größe der Standardfehler der geschätzten Koeffizienten <span class="math inline">\(\hat{\beta}_j\)</span>.</p>
<p>Multikollinearität hat unter anderem die folgenden Effekte:</p>
<ul>
<li>Große Änderungen in den Koeffizienten wenn Prädiktoren ausgelassen/eingefügt werden</li>
<li>Koeffizienten haben eine andere Richtung als erwartet</li>
<li>Hohe (einfache) Korrelationen zwischen Prädiktoren</li>
<li>Breite Konfidenzintervalle für “wichtige” Prädiktoren <span class="math inline">\(b_j\)</span></li>
</ul>
<p>Es lässt sich zeigen, dass die Varianz der geschätzten Modellkoefizienten <span class="math inline">\(b_j\)</span> die folgende Form hat (siehe <a href="#eq-mlm-basics-varb_j" class="quarto-xref">Gleichung&nbsp;<span>18.2</span></a>):</p>
<p><span id="eq-mlm-basics-varb_j"><span class="math display">\[
\widehat{\text{Var}}(b_j) = \frac{\hat{\sigma}^2}{(n-1)s_j^2}\frac{1}{1-R_j^2}
\tag{18.2}\]</span></span></p>
<p>Der Term <span class="math inline">\(R_j^2\)</span> wird als multipler Korrelationskoeffizient bezeichnet und beruht auf dem Determinationskoeffizienten der Prädiktorvariablen <span class="math inline">\(X_i, i\neq j\)</span> auf die Prädiktorvariable <span class="math inline">\(X_j\)</span>. D.h. es wird ein Regressionsmodell gerechnet, bei dem die Prädiktorvariable <span class="math inline">\(X_j\)</span> als abhängige Variable verwendet wird und mittels der anderen <span class="math inline">\(p-1\)</span> Prädiktorvariablen modelliert wird. Der zweiter Term in <a href="#eq-mlm-basics-varb_j" class="quarto-xref">Gleichung&nbsp;<span>18.2</span></a> <span class="math inline">\(\frac{1}{1-R_j^2}\)</span> wird als <strong>Variance Inflation Factor (VIF)</strong> bezeichnet (siehe <a href="#eq-mlm_basics_VIF" class="quarto-xref">Gleichung&nbsp;<span>18.3</span></a>).</p>
<p><span id="eq-mlm_basics_VIF"><span class="math display">\[
\text{VIF}_j = \frac{1}{1-R_j^2}
\tag{18.3}\]</span></span></p>
<p>Wie der Name bereits andeutet, kommt es durch die Korrelation der Prädiktorvariablen untereinander es zu einer <em>Inflation der Varianzen</em>. D.h. die Standardfehler, die Wurzeln der jeweiligen Varianzen, der Modellparameter werden größer. Dies kann dann dazu führen, dass die Modellkoeffizienten keine statistische Signifikanz erreichen obwohl ein klarer Zusammenhang zwischen der Prädiktorvariablen und der abhängigen Variablen besteht.</p>
<p>Anhand <a href="#eq-mlm-basics-varb_j" class="quarto-xref">Gleichung&nbsp;<span>18.2</span></a> ist weiter zu erkennen, dass wenn der Determinantionskoeffizient <span class="math inline">\(R^2_j\)</span>, also die Korrelation der Prädiktorvariablen <span class="math inline">\(j\)</span> mit den anderen Prädiktorvariablen größer wird, der zweite Term ebenfalls größer wird und dementsprechend die Varianz größer wird.</p>
<p>Der <span class="math inline">\(VIF_j\)</span> bietet daher eine einfache Möglichkeit, zumindest heuristisch, das gefittete Regressionsmodell auf Multikollinearitäten zu überprüfen. Bei der Interpretation der VIF gibt es allerdings keinen <em>magischen</em> Wert der eineindeutig Probleme identifiziert. Im Allgemeinen werden die VIFs niemals komplett null sein. Bei der Beurteilung von Problemen auf Grund von Multikollinearität wird üblicherweise der größte VIF Wert im Modell betrachtet.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wenn VIF &gt; 10 ist, dann deutet dies auf hohe Multikollinearität hin.</p>
</div>
</div>
<p>Manchmal wird in der Literatur auch die sogenannte Tolerance = <span class="math inline">\(\frac{1}{VIF}\)</span>, der Inverse Wert des VIF betrachtet.</p>
<p><span id="eq-mlm_basics_tolerance"><span class="math display">\[
\text{Tolerance}_j = \frac{1}{\text{VIF}_j} = 1 - R^2_j
\tag{18.4}\]</span></span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wenn der <span class="math inline">\(\text{Tolerance}_j\)</span> nahe bei <span class="math inline">\(1\)</span> ist, spricht dies für keine relevante Multikollinearität, während Werte <span class="math inline">\(&lt;0.1\)</span> auf Problem hindeuten.</p>
</div>
</div>
<p>Hinsichtlich des Einflusses bzw. des Umgangs bei Multikollinearität muss unterschieden werden, welches Ziel die Modellierung verfolgt. Das Problem das durch die Multikollinearität entsteht ist, basiert darauf das das Modell nicht eindeutig zuordnen kann, welche der miteinander korrelierten Variable für die beobachteten Veränderungen in der abhängigen Variablen <span class="math inline">\(Y\)</span> zuständig ist. Multikollinearität vermindert dabei <strong>nicht</strong> die Fähigkeit des Modells Mittelwerte <span class="math inline">\(E[y|x]\)</span> vorherzusagen oder einen guten Modellfit zu erhalten. Allerdings verkompliziert sich die Interpretation der Modellkoeffizienten <span class="math inline">\(\hat{\beta}_j\)</span>. Dadurch das die Prädiktorvariablen miteinander korrelieren, kann es beispielsweise gar nicht praktisch möglich sein die Variablen einzeln zu variieren, wodurch die Interpretation des Koeffizienten <span class="math inline">\(b_j\)</span> als die Veränderung von <span class="math inline">\(y\)</span> bei Veränderung von <span class="math inline">\(x_j\)</span> um eine Einheit problematisch wird. Da die Multikollinearität die Varianzen der Modelkoeffizienten vergrößert, kann es zu dem Fall kommen, dass ein Modellkoeffizienten <span class="math inline">\(b_j\)</span> statistisch nicht signifikant ist, obwohl eindeutig ein Zusammenhang zwischen <span class="math inline">\(x_j\)</span> und <span class="math inline">\(y\)</span> besteht. Zusätzlich, da die Modellkoeffizienten bei starken Multikollinearität eher instabil sind und sich stark bei Veränderung des Modells verändern können ist deren Interpretation grundsätzlich problematisch.</p>
<section id="variance-inflation-factor-vif-in-r-berechnen" class="level3" data-number="18.3.1">
<h3 data-number="18.3.1" class="anchored" data-anchor-id="variance-inflation-factor-vif-in-r-berechnen"><span class="header-section-number">18.3.1</span> Variance Inflation Factor (VIF) in <code>R</code> berechnen</h3>
<p>In <code>R</code> kann der VIF am einfachsten über zwei Funktionen berechnet werden. Einmal über die <code>vif()</code>-Funktion aus dem Paket <code>car</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mod_full) </span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> triceps    thigh   midarm 
708.8429 564.3434 104.6060 </code></pre>
</div>
</div>
<p>Eine weitere Möglichkeit besteht mittels der Funktion <code>check_collinearity()</code> aus dem <code>performance</code> Paket.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_collinearity</span>(mod_full)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div id="tbl-mlm-basics-collin" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-basics-collin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;18.7: Ausgabe von <code>check_collinearity()</code>
</figcaption>
<div aria-describedby="tbl-mlm-basics-collin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">VIF</th>
<th style="text-align: right;">VIF_CI_low</th>
<th style="text-align: right;">VIF_CI_high</th>
<th style="text-align: right;">SE_factor</th>
<th style="text-align: right;">Tolerance</th>
<th style="text-align: right;">Tolerance_CI_low</th>
<th style="text-align: right;">Tolerance_CI_high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">triceps</td>
<td style="text-align: right;">708.8429</td>
<td style="text-align: right;">383.98652</td>
<td style="text-align: right;">1309.2486</td>
<td style="text-align: right;">26.62410</td>
<td style="text-align: right;">0.0014107</td>
<td style="text-align: right;">0.0007638</td>
<td style="text-align: right;">0.0026043</td>
</tr>
<tr class="even">
<td style="text-align: left;">thigh</td>
<td style="text-align: right;">564.3434</td>
<td style="text-align: right;">305.76950</td>
<td style="text-align: right;">1042.2977</td>
<td style="text-align: right;">23.75591</td>
<td style="text-align: right;">0.0017720</td>
<td style="text-align: right;">0.0009594</td>
<td style="text-align: right;">0.0032704</td>
</tr>
<tr class="odd">
<td style="text-align: left;">midarm</td>
<td style="text-align: right;">104.6060</td>
<td style="text-align: right;">56.91565</td>
<td style="text-align: right;">192.9714</td>
<td style="text-align: right;">10.22771</td>
<td style="text-align: right;">0.0095597</td>
<td style="text-align: right;">0.0051821</td>
<td style="text-align: right;">0.0175699</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In <a href="#tbl-mlm-basics-collin" class="quarto-xref">Tabelle&nbsp;<span>18.7</span></a> ist zu sehen, dass <code>check_collinearity()</code> auch noch Konfidenzintervalle und besagten Tolerance Parameter (siehe <a href="#eq-mlm_basics_tolerance" class="quarto-xref">Gleichung&nbsp;<span>18.4</span></a>) ausgibt. In jedem Fall, ist zu sehen, dass bei Anwendung der Daumenregel <span class="math inline">\(VIF &gt; 10\)</span>, hohe Multikollinearität in unserem Körperfettmodell zu beobachten sind. Dies erklärt somit auch die großen Veränderung in den Koeffizienten bei Hinzu- bzw. Entnahme der Prädiktorvariablen.</p>
<div id="exm-mlm-basics-jiourumaru" class="theorem example">
<p><span class="theorem-title"><strong>Beispiel 18.2 (Gehparameter bei Älteren)</strong></span> Die Beziehung zwischen gebrechlichen älteren Menschen und der Gehgeschwindigkeit ist entscheidend, um den Bedarf an Langzeitpflege oder erhöhter Unterstützung zu minimieren. Insbesondere ist der Zusammenhang zwischen Gehleistung, respiratorischer Funktion und dynamischem Gleichgewicht bei älteren Menschen, die auf Langzeitpflege angewiesen sind, noch nicht gut verstanden. Zu diesem Zweck wurde in <span class="citation" data-cites="jiroumaru2023">Jiroumaru u.&nbsp;a. (<a href="references.html#ref-jiroumaru2023" role="doc-biblioref">2023</a>)</span> der Zusammenhänge zwischen Gehgeschwindigkeit, Atemmuskelkraft und dynamischem Gleichgewicht mittels multipler Regressionsanalyse untersucht.</p>
<p>Die Atemmuskelkraft wurde mittels des maximalen inspiratorische (PImax) und des maximalen exspiratorische Drucks (PEmax) bestimmt. Der maximale Doppelschrittlängentest (MDST) wurde als Index für das dynamische Gleichgewicht verwendet. Eine multiple Regressionsanalyse wurde durchgeführt, wobei die Gehgeschwindigkeit (normale und maximale Gehgeschwindigkeit) als abhängige Variable und PImax, PEmax sowie MDST als unabhängige Variablen verwendet wurden. Zusätzlich wurde das Geschlecht als Anpassungsvariable berücksichtigt und in den Daten als entweder <span class="math inline">\(0\)</span> oder <span class="math inline">\(1\)</span> kodiert. Die Daten sind im repository zum Skriptum zu finden. Eine Analyse der Daten für die abhängige Variable maximale Gehgeschwindigkeit (<code>mws</code>) führte zu folgendem Ergebnis:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mws ~ Pemax + mdst + Pimax + gender, data = jiro)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.49647 -0.11938  0.02674  0.09814  0.63112 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.089055   0.143775  -0.619   0.5388    
Pemax        0.005391   0.002381   2.264   0.0286 *  
mdst         0.810667   0.156529   5.179 5.33e-06 ***
Pimax        0.005307   0.002804   1.893   0.0650 .  
gender      -0.121083   0.083215  -1.455   0.1528    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2387 on 44 degrees of freedom
Multiple R-squared:  0.6331,    Adjusted R-squared:  0.5998 
F-statistic: 18.98 on 4 and 44 DF,  p-value: 3.918e-09</code></pre>
</div>
</div>
<p>D.h. es wurde ein stastistisch signifikanter Zusammenhang der maximalen Gehgeschwindigkeit mit PEmax und MDST beobachtet. Eine Untersuchung des VIF deutete auf keine starken Multikollineariäten zwischen den Variablen hin.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(mod)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Pemax     mdst    Pimax   gender 
2.137365 1.255722 1.866983 1.458773 </code></pre>
</div>
</div>
</div>
</section>
<section id="wenn-prädiktorvariablen-x_j-sich-gegenseitig-maskieren" class="level3" data-number="18.3.2">
<h3 data-number="18.3.2" class="anchored" data-anchor-id="wenn-prädiktorvariablen-x_j-sich-gegenseitig-maskieren"><span class="header-section-number">18.3.2</span> Wenn Prädiktorvariablen <span class="math inline">\(X_j\)</span> sich gegenseitig maskieren</h3>
<p>Insgesamt sind aus der operativen Seite durch den Übergang von der einfachen zur multiplen Regression keine großen Neuerungen hinzugekommen. Allerdings müssen jetzt, wie schon bezüglich der Multikollinearität gesehen wurde, das Verhältnis der Prädiktorvariablen <span class="math inline">\(X_j\)</span> untereinander näher betrachtet werden. Das folgenden Beispiel ist <span class="citation" data-cites="mcelreath2016">McElreath (<a href="references.html#ref-mcelreath2016" role="doc-biblioref">2016</a>)</span> entnommen und zeigt noch einmal zu welchen unerwarteten Effekten es kommen kann, wenn die Prädiktorvariablen miteinander in Beziehung stehen. In diesem Beispiel kommt es tatsächlich zu einer <em>Maskierung</em> der Effekt untereinander wenn Variablen hinzugenommen bzw. weggelassen werden. Daraus resultieren ebenfalls große Veränderungen in den Modellkoeffizienten in Abhängigkeit von der Kombination der Prädiktorvariablen.</p>
<p>Um das Beispiel so anschaulich wie möglich zu machen, wird ein DGP mit nur zwei Prädiktorvariablen <span class="math inline">\(X_{pos}\)</span> und <span class="math inline">\(X_{neg}\)</span> verwendet. Die Prädiktorvariable <span class="math inline">\(X_{pos}\)</span> sei positiv mit <span class="math inline">\(Y\)</span> korreliert, während die Prädiktorvariable <span class="math inline">\(X_{neg}\)</span> negativ mit <span class="math inline">\(Y\)</span> korreliert ist. Zusätzlich seien die beiden Prädiktorvariablen Variablen positiv miteinander korreliert. Es werden <span class="math inline">\(N = 100\)</span> Datenpunkte simuliert. Die genaue Herleitung der Werte ist im einzelnen nicht wichtig und die Werte sind wie immer bei den verwendeten Simulationen der Einfachheit halber gewählt. Zwischen <span class="math inline">\(X_{pos}\)</span> und <span class="math inline">\(Y\)</span> besteht eine Korrelation von <span class="math inline">\(rho_{X_{pos}y} = 0.15\)</span>, zwischen <span class="math inline">\(X_{neg}\)</span> und <span class="math inline">\(Y\)</span> von <span class="math inline">\(rho_{X_{neg}Y} = -0.5\)</span> und zwischen den beiden Prädiktorvariabeln von <span class="math inline">\(rho_{XX} = 0.5\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>Sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">0.15</span>, <span class="sc">-</span>.<span class="dv">5</span>, <span class="fl">0.15</span>, <span class="dv">1</span>, <span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="dv">1</span>), <span class="at">nr=</span><span class="dv">3</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>Sigma</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1] [,2] [,3]
[1,]  1.00 0.15 -0.5
[2,]  0.15 1.00  0.5
[3,] -0.50 0.50  1.0</code></pre>
</div>
</div>
<p>Um die gewünschte Korrelationsstruktur zwischen den Variablen kann nun die Funktion <code>mvrnorm()</code> aus dem Paket <code>MASS</code> verwendet werden. Mit <code>mvrnorm()</code> können Zufallszahlen generiert werden, die eine multivariaten Normalverteilung mit einer vorgegeben Kovarianzstruktur folgen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>df_temp <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">Sigma=</span>Sigma)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df_temp) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'y'</span>,<span class="st">'x_pos'</span>,<span class="st">'x_neg'</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(df_temp)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In <a href="#fig-mlm-basics-mask-01" class="quarto-xref">Abbildung&nbsp;<span>18.6</span></a> ist die resultierende Korrelationsmatrize der drei Variablen abgebildet.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mlm-basics-mask-01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlm-basics-mask-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mlm_basics_files/figure-html/fig-mlm-basics-mask-01-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlm-basics-mask-01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;18.6: x_pos maskiert den Einfluss von x_neg
</figcaption>
</figure>
</div>
</div>
</div>
<p>Es ist zu sehen, dass <code>x_pos</code> und <code>x_neg</code> die gewünschte Korrelation mit <span class="math inline">\(y\)</span> aufweisen sowie ebenfalls eine positive Korrelation miteinander aufweisen. Nun werden wieder drei verschiedene Modelle angepasst. Ein Modell mit bei Variablen, eine Modell mit nur <span class="math inline">\(x_{pos}\)</span> und ein Modell mit nur <span class="math inline">\(x_{neg}\)</span> als Prädiktorvariablen. In <a href="#tbl-mlm-basics-mask-02" class="quarto-xref">Tabelle&nbsp;<span>18.8</span></a> sind die resultierenden Modellkoeffizienten für die drei Modelle dokumentiert.</p>
<div class="cell">
<div id="tbl-mlm-basics-mask-02" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mlm-basics-mask-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;18.8: Koeffizienten und Standardfehler der unterschiedlichen Modelle.
</figcaption>
<div aria-describedby="tbl-mlm-basics-mask-02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 26%">
<col style="width: 31%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;"><span class="math inline">\(\hat{\beta_0} \pm s_e\)</span></th>
<th style="text-align: left;"><span class="math inline">\(\hat{\beta}_{pos} \pm s_e\)</span></th>
<th style="text-align: left;"><span class="math inline">\(\hat{\beta}_{neg} \pm s_e\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">pos</td>
<td style="text-align: left;"><span class="math inline">\(-0.1\pm 0.1\)</span></td>
<td style="text-align: left;"><span class="math inline">\(0.17\pm 0.11\)</span></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">neg</td>
<td style="text-align: left;"><span class="math inline">\(-0.04\pm 0.09\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"><span class="math inline">\(-0.57\pm 0.1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">pos + neg</td>
<td style="text-align: left;"><span class="math inline">\(0.03\pm 0.07\)</span></td>
<td style="text-align: left;"><span class="math inline">\(0.54\pm 0.09\)</span></td>
<td style="text-align: left;"><span class="math inline">\(-0.85\pm 0.1\)</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Es ist zu erkennen, dass die Größe der Modellkoeffizienten sehr stark davon abhängt welche Variablenkombination gefittet wird. Für das Modell mit nur dem positiven Prädiktor <span class="math inline">\(x_{pos}\)</span> kann bei Verwendung der Daumenregeln <span class="math inline">\(\pm 2\times \text{SE}\)</span> erkannt werden, dass der Modellkoeffizient <span class="math inline">\(b_{pos}\)</span> statistisch nicht signifikant ist. Erst wenn beide Prädiktorvariablen in dem Modell inkludiert sind, ist der Modellkoeffizient statistisch signifikant. Im ersten Modell maskiert der Effekte der Prädiktorvariablen <span class="math inline">\(x_{neg}\)</span>, welche gar nicht im Modell enthalten ist, den Effekt von <span class="math inline">\(x_{pos}\)</span> auf <span class="math inline">\(y\)</span>. Erst wenn beide Variablen im Modell auch enthalten sind, ist das Modell in der Lage den Effekt auch tatsächlich zu erfassen.</p>
<p>Zusammenfassend ist es entsprechend wichtig dass bei der Modellierung mittels einer multiplen linearen Regression theoretische Vorüberlegungen über die relevanten Variablen in die Studie mit eingehen. Ein einfaches probieren mittels In- und Exklusion von Prädiktorvariablen wird selten zum gewünschten Erfolg führen bzw. zu einem robustem Modell führen. Zumindest wenn es darum geht den Werten der Modellkoeffizienten auch inhaltliche Bedeutung zuweisen zu können.</p>
</section>
</section>
<section id="unter-der-motorhaube-von-lm-die-modellmatrix" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="unter-der-motorhaube-von-lm-die-modellmatrix"><span class="header-section-number">18.4</span> Unter der Motorhaube von <code>lm()</code> die Modellmatrix</h2>
<p>Für die weitere Arbeit mit der multiplen linearen Regression ist es von Vorteil ein etwas tiefergehendes Verständnis der Berechnungen in <code>R</code> bei der Verwendung von <code>lm()</code> zu haben. Insbesondere die Kenntnis der sogenannten Modellmatrix ist dabei von Vorteil.</p>
<div id="def-model-matrix" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 18.2 (Modellmatrix)</strong></span> Die Modellmatrix , auch als Designmatrix oder Regressionsmatrix , ist eine Matrix welche die zur Modellierung verwendeten Daten in Form einer Matrix enthält. Jede Zeile der Modellmatrix repräsentiert eine Beobachtung, während jede Spalte einer Prädiktorvariable entspricht. Die Modellmatrix wird oft mit dem Buchstaben <span class="math inline">\(X\)</span> bezeichnet.</p>
</div>
<p>In <code>R</code> kann eine Modellmatrix mit Hilfe der Funktion <code>model.matrix()</code> erzeugt werden. Am einfachsten ist die Funktion anhand eines Beispiels nach zu vollziehen. Sei der folgende einfache Beispieldatensatz gegeben:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="fl">2.5</span>,<span class="dv">7</span>),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_1 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_2=</span> <span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">11</span>,<span class="dv">14</span>,<span class="dv">13</span>) </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Wenn nun eine lineares Modell an die <em>Daten</em> gefittet wird, dann würde die folgende Syntax verwendet werden <code>lm(y ~ x_1 + x_2)</code> entsprechend zu dem Modell <span class="math inline">\(y_i = \beta_0 + \beta_1 x_{1i}+ \beta_2 x_{2i} + \epsilon_i\)</span>. Was nun intern in <code>lm()</code> passiert ist, das die Berechnung auf ein mathematisches Problem abgebildet wird, das mit Hilfe von Matrizenalgebra gelöst wird. Die genaueren Schritte sind zunächst nicht weiter wichtig, sondern nur der erste Schritt die Erstellung der Modellmatrix <span class="math inline">\(X\)</span>. Die erzeugte Modellmatrix kann angezeigt werden, indem die Funktion <code>model.matrix()</code> auf das Modellobjekt angewendet wird.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x_1 <span class="sc">+</span> x_2, df)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(mod)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) x_1 x_2
1           1   1  11
2           1   2  11
3           1   3  14
4           1   4  13
attr(,"assign")
[1] 0 1 2</code></pre>
</div>
</div>
<p>Alternativ kann die Modellmatrix anhand der <em>Formel</em> und dem Datensatz erstellt werden:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model.matrix</span>(<span class="sc">~</span> x_1 <span class="sc">+</span> x_2, <span class="at">data =</span> df)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) x_1 x_2
1           1   1  11
2           1   2  11
3           1   3  14
4           1   4  13
attr(,"assign")
[1] 0 1 2</code></pre>
</div>
</div>
<p>Laut der Definition, ist die Modellmatrix <span class="math inline">\(X\)</span> die numerische Darstellung der Prädiktorvariablen mittels einer Matrix. In der zweiten Spalte sind die Werte der Variablen <code>x_1</code>, während in der dritten Spalte die Werte der Variablen <code>x_2</code> eingetragen sind. Die Spalten entsprechen also den jeweiligen Einträgen der Prädiktorvariablen <span class="math inline">\(x_{ji}\)</span>. Die erste Spalte sticht hier etwas raus, da hier nur <span class="math inline">\(1\)</span> eingetragen sind. Diese Spalte ist dem ersten Modellkoeffizienten <span class="math inline">\(\beta_0\)</span> zugeordnet, also dem <em>konstanten</em> <span class="math inline">\(y\)</span>-Achsenabschnitt. Dies hat den Vorteil, dass die vorhergesagten Werte durch eine einfache Matrixmultiplikation berechnet werden können (im Anhang ist dazu eine kurze Erläuterung, ist aber nicht notwendig für das weitere Verständnis).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>beta_s <span class="ot">&lt;-</span> <span class="fu">coef</span>(mod)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span> x_1 <span class="sc">+</span> x_2, df)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>X <span class="sc">%*%</span> beta_s</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       [,1]
1 0.6296296
2 3.4629630
3 2.6851852
4 6.7222222</code></pre>
</div>
</div>
<p>Die Modellkoeffizienten werden bei der Berechnung der Werte <span class="math inline">\(\hat{y}_i\)</span> immer multiplikativ mit der jeweiligen Spalte verbunden. Etwas explizierter.</p>
<p><span class="math display">\[
\hat{y} = \begin{pmatrix} \hat{y}_1 \\ \hat{y}_2 \\ \hat{y}_3 \\ \hat{y}_4 \end{pmatrix} = \begin{pmatrix} 1 \\ 1 \\ 1 \\ 1 \end{pmatrix} \times \hat{\beta_0} + \begin{pmatrix} 1 \\ 2 \\ 3 \\ 4 \end{pmatrix} \times \hat{\beta_1} + \begin{pmatrix} 11 \\ 11 \\ 14 \\ 13 \end{pmatrix} \times \hat{\beta_2} = X \hat{\beta}
\]</span></p>
<p>Dies sind dementsprechend die gleichen Werte <span class="math inline">\(\hat{y}_i\)</span> wie mittels der Funktion <code>predict()</code> berechnet werden.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4 
0.6296296 3.4629630 2.6851852 6.7222222 </code></pre>
</div>
</div>
<p>Wenn sich nun das Modell ändert, dann ändert sich dementsprechend auch die Modellmatrix <span class="math inline">\(X\)</span>. Zu Beispiel bei der Hinzunahme von weiteren Prädiktorvariablen verändert sich die Modellmatrix <span class="math inline">\(X\)</span> dahingehend, dass zusätzliche Spalten an die Matrix angehängt werden. Etwas interessanter wird es, wenn im weiteren Verlauf des Skripts Interaktionseffekte und kategoriale Variablen in das Modell aufgenommen werden. Hier ist dann Kenntnis über die Modellmatrix von Vorteil um die Bedeutung der Modellkoeffizienten besser verstehen zu können.</p>
</section>
<section id="take-away" class="level2" data-number="18.5">
<h2 data-number="18.5" class="anchored" data-anchor-id="take-away"><span class="header-section-number">18.5</span> Take-away</h2>
<ul>
<li>Bei der multiplen Regression wird das Modell um zusätzliche Prädiktorvariablen erweitert</li>
<li>Die Interpretation der Modellkoeffizienten ist bezieht sich auf den Einfluss der jeweiligen Variblen über denjenigen der anderen Variablen hinaus</li>
<li>Die Korrelation der Prädiktorvariablen, die Multikollinearität, untereinander kann zu unvorhergesehenen Effekten bei den Modellkoeffizienten führen</li>
</ul>
</section>
<section id="zum-nacharbeiten" class="level2" data-number="18.6">
<h2 data-number="18.6" class="anchored" data-anchor-id="zum-nacharbeiten"><span class="header-section-number">18.6</span> Zum Nacharbeiten</h2>
<p>Die folgenden Texte eignen sich gut um die Inhalte noch einmal zu vertiefen. <span class="citation" data-cites="pos_multiple_regression">Altman und Krzywinski (<a href="references.html#ref-pos_multiple_regression" role="doc-biblioref">2015</a>)</span> diskutiert noch mal eingehend was passiert wenn Variablen miteinander korrelieren und wie sich das auf die Schätzer für die Koeffizienten auswirkt. <span class="citation" data-cites="kutner2005">(<a href="references.html#ref-kutner2005" role="doc-biblioref">Kutner u.&nbsp;a. 2005, p.278–288</a>)</span> und <span class="citation" data-cites="fox2011">(<a href="references.html#ref-fox2011" role="doc-biblioref">Fox 2011, p.325–327</a>)</span> sind nochmal als Zusammenfassungen zu lesen.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-pos_multiple_regression" class="csl-entry" role="listitem">
Altman, Naomi, und Martin Krzywinski. 2015. <span>„Points of significance: Multiple linear regression“</span>. <em>Nature Methods</em> 12 (12): 1103–4.
</div>
<div id="ref-debanne2011" class="csl-entry" role="listitem">
Debanne, Thierry, und Guillaume Laffaye. 2011. <span>„Predicting the throwing velocity of the ball in handball with anthropometric variables and isotonic tests“</span>. <em>Journal of Sports Sciences</em> 29 (7): 705–13.
</div>
<div id="ref-fox2011" class="csl-entry" role="listitem">
Fox, John. 2011. <em>An R companion to applied regression</em>. 2. Aufl. SAGE Publication Inc., Thousand Oaks.
</div>
<div id="ref-jiroumaru2023" class="csl-entry" role="listitem">
Jiroumaru, Takumi, Yutaro Hyodo, Michio Wachi, Nobuko Shichiri, Junko Ochi, und Takamitsu Fujikawa. 2023. <span>„Relationship between walking speed, respiratory muscle strength, and dynamic balance in community-dwelling older people who required long-term care or support and used a daycare center“</span>. <em>PeerJ</em> 11: e16630.
</div>
<div id="ref-kutner2005" class="csl-entry" role="listitem">
Kutner, Michael H, Christopher J Nachtsheim, John Neter, und William Li. 2005. <em>Applied Linear Statistical Models</em>. 5. Aufl. McGraw-Hill Irwin New York.
</div>
<div id="ref-mcelreath2016" class="csl-entry" role="listitem">
McElreath, Richard. 2016. <em>Statistical rethinking, A Bayesian Course with Examples in R and Stan</em>. 1. Aufl. Boca Raton: CRC Press.
</div>
<div id="ref-riechman2002" class="csl-entry" role="listitem">
Riechman, Steven E, Robert F Zoeller, G Balasekaran, Fredric L Goss, und Robert J Robertson. 2002. <span>„Prediction of 2000 m indoor rowing performance using a 30 s sprint and maximal oxygen uptake“</span>. <em>Journal of Sports Sciences</em> 20 (9): 681–87.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./mlm_title.html" class="pagination-link" aria-label="Multiple Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Multiple Regression</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./mlm_interactions.html" class="pagination-link" aria-label="Interaktionseffekte">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Interaktionseffekte</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>