<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Skriptum - Fortgeschrittene Statistik - 11&nbsp; Einführung</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./slm_inference.html" rel="next">
<link href="./slm_title.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/kbd/kbd.js"></script>
<link href="site_libs/quarto-contrib/kbd/kbd.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>
<script>
  MathJax = {
    tex: {
      tags: 'ams'  // should be 'ams', 'none', or 'all'
    }
  };
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./slm_title.html">Das einfache Regressionmodell</a></li><li class="breadcrumb-item"><a href="./slm_basics.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Einführung</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skriptum - Fortgeschrittene Statistik</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./r_startup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eine Schnelleinführung in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Eine Übersicht über <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_kickoff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title"><code>R</code> Kickoff</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_flowcontrol.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Ablaufkontrolle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Einfache Datenbearbeitung und Visualisierung in <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_literate_programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Literate programming in <code>R</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stats_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistik</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Eine kleine Welt der Unsicherheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistische Signifikanz, p-Wert und Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Parameterschätzung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Theoretische Verteilungen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_hypotheses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hypothesen testen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./slm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das einfache Regressionmodell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_basics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inferenz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_model_fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Modellfit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Vorhersage</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mlm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Interaktionseffekte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_dummy_coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Integration von nominalen Variablen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_hierarchies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Modellhierarchien</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./lm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das allgemeine lineare Modell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Synthese</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./ed_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experimentelles Design</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Completely Randomized Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_linear_contrasts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Lineare Kontraste</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crfd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Completely Randomized Factorial Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">ANCOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_crbd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Completely Randomized Block Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_irbd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Incomplete Randomized Block Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_split_plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Split-plot Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ed_cross_over.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Cross-over Design</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatur</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#back-to-school" id="toc-back-to-school" class="nav-link active" data-scroll-target="#back-to-school"><span class="header-section-number">11.1</span> Back to school</a></li>
  <li><a href="#funktionaler-versus-stochastischer-zusammenhang-zwischen-zwei-variablen" id="toc-funktionaler-versus-stochastischer-zusammenhang-zwischen-zwei-variablen" class="nav-link" data-scroll-target="#funktionaler-versus-stochastischer-zusammenhang-zwischen-zwei-variablen"><span class="header-section-number">11.2</span> Funktionaler versus stochastischer Zusammenhang zwischen zwei Variablen</a></li>
  <li><a href="#die-einfache-lineare-regression" id="toc-die-einfache-lineare-regression" class="nav-link" data-scroll-target="#die-einfache-lineare-regression"><span class="header-section-number">11.3</span> Die einfache lineare Regression</a></li>
  <li><a href="#methode-der-kleinsten-quadrate" id="toc-methode-der-kleinsten-quadrate" class="nav-link" data-scroll-target="#methode-der-kleinsten-quadrate"><span class="header-section-number">11.4</span> Methode der kleinsten Quadrate</a></li>
  <li><a href="#was-bedeuten-die-koeffizienten" id="toc-was-bedeuten-die-koeffizienten" class="nav-link" data-scroll-target="#was-bedeuten-die-koeffizienten"><span class="header-section-number">11.5</span> Was bedeuten die Koeffizienten?</a></li>
  <li><a href="#die-einfache-lineare-regression-in-r" id="toc-die-einfache-lineare-regression-in-r" class="nav-link" data-scroll-target="#die-einfache-lineare-regression-in-r"><span class="header-section-number">11.6</span> Die einfache lineare Regression in <code>R</code></a></li>
  <li><a href="#sec-step-by-step-normal" id="toc-sec-step-by-step-normal" class="nav-link" data-scroll-target="#sec-step-by-step-normal"><span class="header-section-number">11.7</span> Schritt-für-Schritt Herleitung der Normalengleichungen (advanced)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Einführung</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="back-to-school" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="back-to-school"><span class="header-section-number">11.1</span> Back to school</h2>
<p>Wir beginnen mit einem uns bekannten Konzept, der Punkt-Steigungsform aus der Schule (siehe Formel <span class="math inline">\(\eqref{eq-slm-psform-1}\)</span>).</p>
<p><span class="math display">\[\begin{equation}
y = m x + b
\label{eq-slm-psform-1}
\end{equation}\]</span></p>
<p>Wir haben eine abhängige Variable <span class="math inline">\(y\)</span> und eine lineare Formel <span class="math inline">\(mx + b\)</span> die den funktionalen Zusammenhang zwischen den Variablen <span class="math inline">\(y\)</span> und <span class="math inline">\(x\)</span> beschreibt. Um das Ganze einmal konkret zu machen setzen wir <span class="math inline">\(m = 2\)</span> und <span class="math inline">\(b = 3\)</span> fest. Die Formel <span class="math inline">\(\eqref{eq-slm-psform-1}\)</span> wird dann zu:</p>
<p><span class="math display">\[\begin{equation}
y = 2 x + 3
\label{eq-slm-psform-2}
\end{equation}\]</span></p>
<p>Um ein paar Werte für <span class="math inline">\(y\)</span> zu erhalten setzen wir jetzt verschiedene Wert für <span class="math inline">\(x\)</span> ein indem wir <span class="math inline">\(x\)</span> in Einserschritten zwischen <span class="math inline">\([0, \ldots, 5]\)</span> erhöhen. Um die Werte darzustellen verwenden wir zunächst eine Tabelle (vgl. <a href="#tbl-slm-psform">Tabelle&nbsp;<span>11.1</span></a>)</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-slm-psform" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;11.1: Tabelle der Daten</caption>
<thead>
<tr class="header">
<th style="text-align: right;">x</th>
<th style="text-align: right;">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">13</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Wenig überraschend nimmt <span class="math inline">\(y\)</span> für den Wert <span class="math inline">\(x = 0\)</span> den Wert <span class="math inline">\(3\)</span> an und z.B. für den Wert <span class="math inline">\(x = 3\)</span> nimmt <span class="math inline">\(y\)</span> den Wert <span class="math inline">\(2 \cdot 3 + 3 = 9\)</span> an.</p>
<p>Eine weitere Darstellungsform ist die graphische Darstellung in dem wir die Werte von <span class="math inline">\(y\)</span> gegen <span class="math inline">\(x\)</span> in einem Graphen abtragen (siehe <a href="#fig-slm-psform-1">Abbildung&nbsp;<span>11.1</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-psform-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_basics_files/figure-html/fig-slm-psform-1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;11.1: Graphische Darstellung der Daten aus <a href="#tbl-slm-psform">Tabelle&nbsp;<span>11.1</span></a></figcaption>
</figure>
</div>
</div>
</div>
<p>Wiederum wenig überraschen sehen wir einen linearen Zuwachs der <span class="math inline">\(y\)</span>-Wert mit den größerwerdenden <span class="math inline">\(x\)</span>-Werten. Da in der Definition der Formel <span class="math inline">\(\eqref{eq-slm-psform-2}\)</span> nirgends festgelegt wurde, dass diese nur für ganzzahlige <span class="math inline">\(x\)</span>-Werte gilt, haben wir direkt eine Gerade durch die Punkte gelegt. Somit sollte auch die Bedeutung von <span class="math inline">\(m\)</span> und <span class="math inline">\(b\)</span> direkt klar. Die Variable <span class="math inline">\(m\)</span> bestimmt die Steigung der Gleichung während <span class="math inline">\(b\)</span> den y-Achsenabschnitt beschreibt.</p>
<div id="def-slm-basics-y-intercept" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 11.1 (<span class="math inline">\(y\)</span>-Achsenabschnitt) </strong></span>Der y-Achsenabschnitt ist der Wert den <span class="math inline">\(y\)</span> einnimmt wenn <span class="math inline">\(x\)</span> den Wert <span class="math inline">\(0\)</span> annimmt. Sei <span class="math inline">\(y\)</span> durch eine lineare Gleichung <span class="math inline">\(y = mx + b\)</span> definiert, dann wird der y-Achsenabschnitt durch den Wert <span class="math inline">\(b\)</span> bestimmt.</p>
</div>
<p>Die Variable <span class="math inline">\(m\)</span> dahingehend bestimmt die Steigung der Gerade.</p>
<div id="def-slm-basics-slope" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 11.2 (Steigungskoeffizient) </strong></span>Wenn <span class="math inline">\(y\)</span> durch eine lineare Gleichung <span class="math inline">\(y = mx + b\)</span> definiert ist, dann bestimmt die Variable <span class="math inline">\(m\)</span> die Steiung der dazugehörenden Gerade. D.h. wenn sich die Variable <span class="math inline">\(x\)</span> um einen Einheit vergrößert (verkleinert) wird der Wert von <span class="math inline">\(y\)</span> um <span class="math inline">\(m\)</span> Einheiten größer (kleiner). Gilt <span class="math inline">\(m &lt; 0\)</span> dann umgekehrt.</p>
</div>
<p>Diese beiden trivialen Konzepte mit eigenen Definitionen zu versehen erscheint im ersten Moment vielleicht etwas übertrieben. Wie sich allerdings später zeigen wird, sind diese beiden Einsichten immer wieder zentral wenn es um die Interpretation von linearen statistischen Modellen geht.</p>
<p>Soweit so gut. Führen wir direkt ein paar Symbole ein, die uns später noch behilflich sein werden. Sei jetzt die Menge der <span class="math inline">\(x\)</span>-Werte geben <span class="math inline">\(x = [0, 1, 2, 3, 4, 5]\)</span>. Strenggenommen handelt es sich wieder um ein Tupel, da wir jetzt die Reihenfolge nicht mehr ändern. Wir führen nun einen Index <span class="math inline">\(i\)</span> ein, um einzelne Werte in dem Tupel über ihre Position zu bestimmen und wir hängen diesen Index <span class="math inline">\(i\)</span> an <span class="math inline">\(x\)</span> an. Dann wird aus <span class="math inline">\(x\)</span>, <span class="math inline">\(x_i\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-slm-basic-index" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;11.2: <span class="math inline">\(x\)</span>-Werte und ihr Index <span class="math inline">\(i\)</span></caption>
<thead>
<tr class="header">
<th style="text-align: right;">Index <span class="math inline">\(i\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x\)</span>-Wert</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Damit können wir jetzt einen speziellen Wert zum Beispiel den dritten Wert mit <span class="math inline">\(x_3 = 2\)</span> bestimmen. Wenden wir unseren Index auf unsere Formel <span class="math inline">\(\eqref{eq-slm-psform-1}\)</span> an, folgt daraus, dass <span class="math inline">\(y\)</span> jetzt auch einen Index <span class="math inline">\(i\)</span> erhält.</p>
<p><span class="math display">\[
y_i = m x_i + b \qquad i \text{ in } [1,2,3,4,5,6]
\]</span></p>
<p>Wir bezeichnen die beiden Variablen <span class="math inline">\(m\)</span>, die Steigung, und <span class="math inline">\(b\)</span>, den y-Achsenabschnitt, mit neuen Variablen die ebenfalls einen Index erhalten. Aus <span class="math inline">\(m\)</span> wird <span class="math inline">\(\beta_1\)</span> und aus <span class="math inline">\(b\)</span> wird <span class="math inline">\(\beta_0\)</span>. Damit wird der y-Achsenabschnitt mit <span class="math inline">\(\beta_0\)</span> bezeichnet und die Steigung wird mit <span class="math inline">\(\beta_1\)</span> bezeichnet. Dann wir aus unserer Gleichung:</p>
<p><span class="math display">\[\begin{equation}
y_i = \beta_0 + \beta_1 x_i
\label{eq-slm-psform-beta}
\end{equation}\]</span></p>
<p>Formel <span class="math inline">\(\eqref{eq-slm-psform-beta}\)</span> ist immer noch unsere einfache Punkt-Steigungsform, wir haben lediglich den Index <span class="math inline">\(i\)</span> eingeführt um unterschiedliche <span class="math inline">\(y-x\)</span>-Wertepaare zu bezeichnen und wir haben den <span class="math inline">\(y\)</span>-Achsenabschnitt und die Steigung mit neuen Symbolen versehen. Wenn wir uns später mit der multiplen linearen Regression beschäftigen und nicht mehr nur eine einzige <span class="math inline">\(x\)</span>-Variable haben, dann vereinfacht die Benutzung von <span class="math inline">\(\beta\)</span>s die Schreibweise, da wir einfach zusätzliche <span class="math inline">\(\beta\)</span>s anhängen und mit einem fortlaufenden Index (z.B. <span class="math inline">\(\beta_2, \beta_3, \ldots\)</span>) versehen.</p>
</section>
<section id="funktionaler-versus-stochastischer-zusammenhang-zwischen-zwei-variablen" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="funktionaler-versus-stochastischer-zusammenhang-zwischen-zwei-variablen"><span class="header-section-number">11.2</span> Funktionaler versus stochastischer Zusammenhang zwischen zwei Variablen</h2>
<p>Bei dem bisherigen Zusammenhang handelt es sich um einen funktionalen Zusammenhang zwischen den beiden Variablen <span class="math inline">\(x\)</span> und <span class="math inline">\(y\)</span>. Funktional deswegen, weil wir eine definiertes mathematisches Modell angeben können, d.h. wir haben eine präzise mathematische Funktion welche die Beziehung zwischen den beiden Variablen beschreibt. Wenn wir den Wert für <span class="math inline">\(x\)</span> kennen, dann können wir einen, einzigen Wert für <span class="math inline">\(y\)</span> ausreichnen indem wir den Wert <span class="math inline">\(x\)</span> in Formel <span class="math inline">\(\eqref{eq-slm-psform-1}\)</span> einsetzen. Aus der Schule kennen wir noch die Darstellung <span class="math inline">\(y = f(x)\)</span>. Streng genommen ist diese Darstellung für Formel <span class="math inline">\(\eqref{eq-slm-psform-1}\)</span> nicht ausreichend, denn um den Wert für <span class="math inline">\(y\)</span> auszurechnen benötigen wir auch noch Kenntnis über die Werte <span class="math inline">\(m\)</span> und <span class="math inline">\(b\)</span>, bzw. in unsere weiteren Darstellung <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>. Daher sollte der Zusammenhang eigentlich mit <span class="math inline">\(y = f(x, \beta_0, \beta_1)\)</span> bezeichnet werden. Es gilt aber immernoch, für gegebene <span class="math inline">\(x, \beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> ist der Wert für <span class="math inline">\(y\)</span> fest determiniert.</p>
<p>Wenn wir mit realen Daten arbeiten, dann funktioniert dieser Ansatz leider nicht direkt. Selbst wenn wir ein Experiment mehrmals genau gleich durchführen, werden wir immer etwas unterschiedliche Werte im Sinne der Messungenauigkeit messen. Wenn wir biologische Systeme messen, kommt dazu das diese in den seltensten Fällen zeitstabil sind sondern immer bestimmte Veränderungen von einem Zeitpunkt zum nächsten auftauchen.</p>
<p>In <a href="#fig-slm-basics-jump-1">Abbildung&nbsp;<span>11.2</span></a> ist ein realer Datensatz abgetragen. Auf der <span class="math inline">\(y\)</span>-Achse sind die Sprungweiten von mehreren Weitspringerinnen gegen die Anlaufgeschwindigkeit auf der <span class="math inline">\(x\)</span>-Achse abgetragen. Bei der Betrachtung der Daten erscheint ein linearer Zusammenhang zwischen diesen beiden Variablen durchaus als plausibel.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-jump-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_basics_files/figure-html/fig-slm-basics-jump-1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;11.2: Zusammenhang der Anlaufgeschwindigkeit und der Sprungweite beim Weitsprung</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-basics-jump-1">Abbildung&nbsp;<span>11.2</span></a> sind zwei Punkte rot markiert. Die beiden Werte haben praktisch den gleichen <span class="math inline">\(x\)</span>-Wert unterscheiden sich allerdings bezüglich ihrer <span class="math inline">\(y\)</span>-Werte deutlich voneinander. Und dies sind nicht die einzigen Beispielpaare bei denen die <span class="math inline">\(x\)</span>-Werte nahe beiandern liegen, während die <span class="math inline">\(y\)</span>-Werte klar voneiander getrennt sind. Dies ist im Unterschied zu einen funktionalen Zusammenhang nach Formel <span class="math inline">\(\eqref{eq-slm-psform-1}\)</span>. Bei einem rein funktionalen Zusammenhang wird jedem <span class="math inline">\(x\)</span>-Wert nur genau ein <span class="math inline">\(y\)</span>-Wert zugeordent.</p>
<p>Die Abweichungen kommen durch zufällige Einflussfaktoren wie eben zum Beispiel die Veränderungen angesprochener biologischer Faktoren und Messunsicherheiten. Beim Beispiels des Weitsprung spielen auch noch externe Einflüsse, wie beispielsweise Windverhältnisse, eine Rolle. Vielleicht wenn es sich um den gleichen Springer handelt, hat er auch beim zweiten Mal keine Lust mehr gehabt. Wenn die Punkte zwei unterschiedliche Springer sind, dann kommt auch dazu, dass zwei Weitspringer bei identischer Anlaufgeschwindigkeit unterschiedliche Sprungfähigkeiten haben oder auch technisch nicht gleich gesprungen sind und so weiter und so fort. Insgesamt führen alle diese Einflüsse dazu, dass wir nicht mehr einen streng funktionalen Zusammenhang zwischen unseren beiden Variablen <span class="math inline">\(x\)</span> der Anlaufgeschwindigkeit und <span class="math inline">\(y\)</span> der Sprungweite vorfinden. Es handelt sich um einen stochastischen Zusammenhang zwischen den beiden Variablen. Wie wir mit diesen zufälligen Einflüssen umgehen ist das zentrale Thema des nächsten Abschnitts und markiert auch unseren Eingang zur einfachen linearen Regression.</p>
</section>
<section id="die-einfache-lineare-regression" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="die-einfache-lineare-regression"><span class="header-section-number">11.3</span> Die einfache lineare Regression</h2>
<p>Bleiben wir bei unserem Beispiel aus <a href="#fig-slm-basics-jump-1">Abbildung&nbsp;<span>11.2</span></a>. Wir versetzen uns in die Lage einer Weitsprungtrainerin und die vor der Aufgabe steht ihr Training zu optimieren um die Weitsprungleistung ihrer Athleten zu verbessern. Wir haben uns dazu entschlossen am Anlauf etwas zu verbessern wissen jetzt aber nicht ob das wirklich lohnenswert ist. Von einer befreundeten Trainerin haben wir einen Datensatz bekommen mit Anlaufgeschwindigkeiten und den dazugehörigen Sprungweiten. Schauen wir uns zunächst die einmal die Struktur der Daten an.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-slm-basics-jump-1" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;11.3: Ausschnitt der Sprungdaten</caption>
<thead>
<tr class="header">
<th style="text-align: right;">jump_m</th>
<th style="text-align: right;">v_ms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">4.36</td>
<td style="text-align: right;">6.13</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.31</td>
<td style="text-align: right;">6.39</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4.56</td>
<td style="text-align: right;">6.56</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.75</td>
<td style="text-align: right;">6.44</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5.52</td>
<td style="text-align: right;">7.30</td>
</tr>
<tr class="even">
<td style="text-align: right;">5.63</td>
<td style="text-align: right;">7.19</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5.70</td>
<td style="text-align: right;">7.30</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In <a href="#tbl-slm-basics-jump-1">Tabelle&nbsp;<span>11.3</span></a> sind die ersten <span class="math inline">\(7\)</span> Zeilen der Sprungdaten abgebildet. Die Daten zeigen eine einfache Struktur mit zwei Spalten. <code>jump_m</code> bezeichnet die Sprungweiten und <code>v_ms</code> die Anlaufgeschwindigkeiten. Damit wir die Datenpaare voneinander unterscheiden bzw. identifzieren können führen wir unseren bereits besprochenen Index <span class="math inline">\(i\)</span> und können so einzelne Paare ansprechen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-slm-basics-jump-2" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;11.4: Ausschnitt der Sprungdaten</caption>
<thead>
<tr class="header">
<th style="text-align: right;">i</th>
<th style="text-align: right;">jump_m</th>
<th style="text-align: right;">v_ms</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.36</td>
<td style="text-align: right;">6.13</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">4.31</td>
<td style="text-align: right;">6.39</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.56</td>
<td style="text-align: right;">6.56</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4.75</td>
<td style="text-align: right;">6.44</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">5.52</td>
<td style="text-align: right;">7.30</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">5.63</td>
<td style="text-align: right;">7.19</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">5.70</td>
<td style="text-align: right;">7.30</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Daher hat zum Beispiel der dritte Datenpunkt <span class="math inline">\(i = 3\)</span> die Datenwerte <span class="math inline">\(\text{jump} = 4.31\)</span> und <span class="math inline">\(\text{v}_3 = 6.56\)</span>.</p>
<p>Das waren bisher aber nur Formalitäten. Wir wollen jetzt denn Zusammenhang zwischen den beiden Variablen modellieren. Wir könnten wahrscheinlich auch einfach Pi-mal-Daumen abschätzen wie groß der Zusammenhang ist. Wenn wir jetzt aber einen unserer Läufer haben, der z.B. etwa <span class="math inline">\(9m/s\)</span> anläuft, welchen Vergleichswerte nehmen wir dann aus Formel <span class="math inline">\(\eqref{fig-slm-basics-jump-1}\)</span>. Den unteren oder den oberen der beiden roten Werte? Oder vielleicht den Mittelwert? Welchen Wert nehmen wir wenn unserer Athlete <span class="math inline">\(9.7m/s\)</span> anläuft. Da haben wir leider keinen Vergleichswert in unserer Tabelle. Daher wäre es schon ganz praktisch eine Formel nach dem Muster von Formel <span class="math inline">\(\eqref{eq-slm-psform-beta}\)</span> zu haben. Wie wir allerdings schon festgestellt haben, geht dies nicht so einfach da wir eben das Problem mit den Einflussfaktoren haben, die dazu führen, dass die Werte nicht präzise auf eine Gerade liegen. Somit liegt die Herausforderung nun darin, eine Gerade zu finden die möglichst <em>genau</em> die Daten wiederspiegelt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-line-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_basics_files/figure-html/fig-slm-basics-line-1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;11.3: Mögliche Geraden um den Zusammenhang der Anlaufgeschwindigkeit und der Sprungweite zu modellieren</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-basics-line-1">Abbildung&nbsp;<span>11.3</span></a> sind die Daten zusammen mit verschiedenen möglichen Geraden abgebildet. Eine kurze Überlegung macht schnell klar, dass es im Prinzip unendlich viele unterschiedliche Geraden gibt die durch die Datenpunkte gelegt werden können. Da jede Gerade durch die beiden Parameter <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> spezifiziert ist, gibt es somit auch unendlich viele Kombinationen von <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>, die die jeweiligen Geraden definieren. Um nun eine spezielle Gerade aus den unendlich vielen Geraden auswählen zu können, benötigen wir ein Kriterium welches definiert was eine besser passende versus eine schlechter passende Gerade durch die gegebenen Punkte ist. D.h. wir such eine Geraden die im Sinne des Kriterium <em>optimal</em> ist. Tatsächlich gibt es dort auch verschiedene Möglichkeiten Kriterien zu entwickeln. Dasjenige Kriterium das am weitesten verbreitet ist und auch intuitiv nachvollziehbar ist basiert auf den quadrierten Abweichungen der Gerade von den Datenpunkten (engl. least squares). Versuchen wir daher nun die Herleitung der least squares schrittweise nachzuvollziehen.</p>
</section>
<section id="methode-der-kleinsten-quadrate" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="methode-der-kleinsten-quadrate"><span class="header-section-number">11.4</span> Methode der kleinsten Quadrate</h2>
<p>Fangen wir dazu zunächst einmal nur mit den einfachen Abweichunge, also nicth den quadrierten Abweichungen an. In <a href="#fig-slm-basics-line-2">Abbildung&nbsp;<span>11.4</span></a> ist zur Übersicht nur ein Ausschnitt der Daten zusammen mit einer möglichen Gerade eingezeichnet. Die senkrechten Abweichungen der Geraden zu den jeweiligen Datenpunkten sind rot eingezeichnet. Es ist ersichtlich, dass für diese Wahl der Geraden es zwei Punkte gibt die ziemlich genau auf der Geraden liegen während die anderen Punkte zum Teil oberhalb bzw. unterhalb der Geraden liegen. Das Kriterium wäre jetzt dementsprechen die jenige Geraden aus den unendlich vielen zu finden, bei der die Abweichung (die roten Linien) ein Minimum annehmen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-line-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_basics_files/figure-html/fig-slm-basics-line-2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;11.4: Abweichungen der Gerade von der Datenpunkten für die Daten mit eine Anlaufgeschwindigkeit zwischen <span class="math inline">\(8m/s\)</span> und <span class="math inline">\(10m/s\)</span>.</figcaption>
</figure>
</div>
</div>
</div>
<p>Um die Abweichungen (rote Linien) berechnen zu können benötigen wir die dazugehörenden Punkte auf der Geraden. Wenn wir die Gerade schon hätten, dann wäre das kein Problem. Die Punkte auf der Geraden sind genau diejenigen <span class="math inline">\(y\)</span>-Werte die für die jeweiligen <span class="math inline">\(x\)</span>-Werte berechnen <span class="math inline">\(\beta_0 + \beta_1 x_i\)</span>. Die Abweichung für einen Punkt lässt sich dann wie folgt berechnen:</p>
<p><span class="math display">\[\begin{equation*}
\text{Abweichung}_i = y_i - (\beta_0 + \beta_1 x_i)
\end{equation*}\]</span></p>
<p>Entsprechend führt unser Kriterium zu Summation der Abweichungen für alle Punkte.</p>
<p><span class="math display">\[\begin{equation*}
\text{min}\sum_{i=1}^n y_i - (\beta_0 + \beta_1 x_i) = \sum_{i=1}^n y_i - \beta_0 - \beta_1 x_i
\end{equation*}\]</span></p>
<p>Wir verschärfen das Kriterium nun noch etwas indem wir größere Abweichungen stärker gewichten wollen als kleinere Abweichungen. D.h. große Abweichungen zwischen der Gerade und den Datenpunkten sollen stärker berücksichtigt werden, als kleine Abweichungen. Dies können wir erreichen indem wir die Abweichungen quadrieren. Dementsprechend erhalten wir die folgende Funktion:</p>
<p><span class="math display">\[\begin{equation}
E(\beta_0, \beta_1) = \sum_{i=1}^n(y_i - (\beta_0 + \beta_1 x_i))^2
\label{eq-slm-basics-rms-1}
\end{equation}\]</span></p>
<p>Mit <span class="math inline">\(E(\beta_0, \beta_1)\)</span> wird ausgedrückt, dass die Summe von der Wahl der beiden Parameter <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> abhängt. <span class="math inline">\(E\)</span> ist eine Funktion von <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>. Um unsere Gerade zu bestimmen suchen wir daher nun das Minimum von <span class="math inline">\(E\)</span> (<span class="math inline">\(E\)</span> nach englisch error).</p>
<p>Die Abweichungen der Punkte auf der Gerade von den tatsächlichen Datenpunkten spielen in der weiteren Betrachtung immer wieder eine wichtige Rolle und haben daher einen eigenen Term. Die Abweichungen werden als Residuen <span class="math inline">\(e_i\)</span> bezeichnet. Dementsprechend kann die Minimierungsgleichung auch mit:</p>
<p><span class="math display">\[
\text{min} \sum_{i=1}^n e_i^2
\]</span> dargestellt werden. Es gilt <span class="math inline">\(e_i := y_i - (\beta_0 + \beta_1 x_i)\)</span>. Insgesamt:</p>
<p><span class="math display">\[\begin{equation*}
E(\beta_0, \beta_1) = \sum_{i=1}^n e_i^2 = \sum_{i=1}^n (y_i - \beta_0 - \beta_1 x_i)^2
\end{equation*}\]</span></p>
<p>Das Minimum läßt sich nun bestimmen, indem wir die partiellen Ableitungen von <span class="math inline">\(E\)</span> nach <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> berechnet werden und, wie wir es aus der Schule kennen, diese gleich Null setzen.</p>
<p><span class="math display">\[\begin{align*}
\frac{\partial E(\beta_0, \beta_1)}{\partial \beta_0} &amp;= -2 \sum_{i=1}^n (y_i - \beta_0 - \beta_1 x_i) = 0 \\
\frac{\partial E(\beta_0, \beta_1)}{\partial \beta_1} &amp;= -2 \sum_{i=1}^n x_i (y_i - \beta_0 - \beta_1 x_i) = 0
\end{align*}\]</span></p>
<p>Dies Gleichungen bilden ein Gleichungssystem mit zwei Unbekannten <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> und können mittels etwas Algebra nach <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> aufgelöst werden (siehe <a href="#sec-step-by-step-normal"><span>Kapitel&nbsp;11.7</span></a>). Dies führt zu den folgenden Lösungen für <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>:</p>
<p><span class="math display">\[\begin{align}
\label{eq-slm-basics-norm-1}
\hat{\beta_1} &amp;= \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^n (x_i - \bar{x})^2} \\
\label{eq-slm-basics-norm-2}
\hat{\beta_0} &amp;= \bar{y} - \hat{\beta_1} \bar{x}
\end{align}\]</span></p>
<p><span class="math inline">\(\bar{x}\)</span> und <span class="math inline">\(\bar{y}\)</span> sind die Mittelwerte von <span class="math inline">\(x_i\)</span> und <span class="math inline">\(y_i\)</span>. Diese beiden Gleichungen werden als die Normalengleichungen bezeichnet.</p>
<p>Wir führen noch einen weiteren Term ein, den vorhergesagten Wert <span class="math inline">\(\hat{y}_i\)</span> von <span class="math inline">\(y_i\)</span> anhand der Geradengleichung. Das Hütchen über <span class="math inline">\(y_i\)</span> ist dabei immer das Signal dafür, das es sich um einen abgeschätzten Wert handelt. Wenn wir <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> anhand der Normalengleichung bestimmen, dann sind das mit großer Wahrscheinlichkeit nicht die <em>wahren</em> Werte aus der Population, sondern wir haben sie nur anhand der Daten abgeschätzt. Daher bekommen die berechneten Werte ebenfalls ein Hütchen <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span>. Insgesamt nimmt die lineare Geradengleichung dann die folgende Form an:</p>
<p><span class="math display">\[
\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 \cdot x_i
\]</span></p>
<p>D.h. die Residuen können auch mittels <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span> dargestellt werden. Graphisch sind die <span class="math inline">\(\hat{y}_i\)</span>s die Werte auf der Geraden für die gegebenen <span class="math inline">\(x_i\)</span>-Werte.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-line-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_basics_files/figure-html/fig-slm-basics-line-3-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;11.5: Die vorhergesaten Werte <span class="math inline">\(\hat{y}_i\)</span> auf der Gerade.</figcaption>
</figure>
</div>
</div>
</div>
<p>Gehen wir zurück zu unseren Weitsprungdaten. Wenn wir die Datenpunkte in die Normalengleichungen Formeln <span class="math inline">\(\eqref{eq-slm-basics-norm-1}\)</span> und <span class="math inline">\(\eqref{eq-slm-basics-norm-2}\)</span> einsetzen, dann erhalten wir für die Koeffizienten die Werte <span class="math inline">\(\hat{\beta}_0 = -0.14\)</span> und <span class="math inline">\(\hat{\beta}_1 = 0.76\)</span>. Somit folgt für die Geradengleichung:</p>
<p><span class="math display">\[
\hat{y}_i = -0.14 + 0.76 \cdot x_i
\]</span></p>
<p>Wir erhalten die graphische Darstellung der Geradengleichung indem die <span class="math inline">\(x_i\)</span>-Werte eingesetzt werden und eine Gerade durch die Punkte gezogen wird. Oder auch einfacher für den größten und den kleinsten <span class="math inline">\(x_i\)</span>-Wert.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-line-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_basics_files/figure-html/fig-slm-basics-line-4-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;11.6: Die Regressionsgerade der Sprungdaten.</figcaption>
</figure>
</div>
</div>
</div>
<p>Um uns auch zu vergewissern, dass unsere Berechnungen korrekt sind, schauen wir uns noch einmal an, wie sich <span class="math inline">\(E\)</span> verhält, wenn wir unterschiedliche Kombinationen von Werten für <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> in die lineare Gleichung einsetzen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-gradient" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_basics_files/figure-html/fig-slm-basics-gradient-1.png" class="img-fluid figure-img" width="384"></p>
<figcaption class="figure-caption">Abbildung&nbsp;11.7: Heatmap von <span class="math inline">\(log(E)\)</span> für verschiedene Werte von <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span></figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-basics-gradient">Abbildung&nbsp;<span>11.7</span></a> sind verschiedene Werte für <span class="math inline">\(E\)</span> in Form einer heatmap dargestellt. Die Abweichungen wurden <span class="math inline">\(log\)</span>-transformiert (d.h. der Logarithmus der <span class="math inline">\(E\)</span>-Werte wurde berechnet), da sonst die Unterschiede in der diagnaolen Bildrichtung zu schnell wachsen und die Unterschiede nicht mehr so einfach zu erkennen sind. Werte näher an Weiß bedeuten kleine Werte und Werte näher an Rot bedeuten größere Werte von <span class="math inline">\(E\)</span>. Das berechnete Paar für <span class="math inline">\((\hat{\beta}_0, \hat{\beta}_1)\)</span> mit <span class="math inline">\(\hat{\beta}_0 = -0.14\)</span> und <span class="math inline">\(\hat{\beta}_1 = 0.76\)</span> ist schwarz eingezeichnet. Die Abbildung zeigt, dass dieses Wertepaar tatsächlich ein Minimum bezüglich der Funktion <span class="math inline">\(E\)</span> ist, da in alle Richtung weg von dem schwarzen Punkt die Werte für <span class="math inline">\(E\)</span> zunehmen. Da wir nur einen Ausschnitt der möglichen Werte sehen, handelt es sich zunächst um eine lokales Minimum aber es lässt sich zeigen, dass es sich dabei auch um ein globales Minimum handelt. Diese Eigenschaft hängt mit der Form der Funktion <span class="math inline">\(E\)</span> zusammen. In <a href="#tbl-slm-basics-gradient">Tabelle&nbsp;<span>11.5</span></a> sind beispielhaft ein paar Werte für <span class="math inline">\(log(E)\)</span> für Paare von <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> angezeigt, die in <a href="#fig-slm-basics-gradient">Abbildung&nbsp;<span>11.7</span></a> gelb eingezeichnet sind.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-slm-basics-gradient" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;11.5: Werte von <span class="math inline">\(log(E)\)</span> für verschiedenen Kombinationen von <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>.</caption>
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(\beta_0\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\beta_1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(log(E)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-0.48</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">70.34</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.44</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">51.85</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-0.38</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">22.04</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.30</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">6.46</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-0.22</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">3.77</td>
</tr>
<tr class="even">
<td style="text-align: right;">-0.14</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">2.41</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Wir können in <a href="#tbl-slm-basics-gradient">Tabelle&nbsp;<span>11.5</span></a> erkennen, das das Wertepaar für <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>, welches wir mit Hilfe der Normalengleichung bestimmt haben, denn kleinesten Abweichungswert hat. Also im Sinne unseres Kriteriums ein Optimum darstellt.</p>
</section>
<section id="was-bedeuten-die-koeffizienten" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="was-bedeuten-die-koeffizienten"><span class="header-section-number">11.5</span> Was bedeuten die Koeffizienten?</h2>
<p>Gehen wir zurück nun zu unseren Ausgangsproblem der Weitspringer, was haben wir jetzt durch die Berechnung der Gerade eigentlich gewonnen? Dazu müssen wir erst einmal verstehen was die beiden Koeffizienten <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span> bedeuten. Wenn wir zurück zu Formel <span class="math inline">\(\eqref{eq-slm-psform-1}\)</span> gehen, haben die beiden Koeffzienten den <span class="math inline">\(y\)</span>-Achsenabschnitt und die Steigung der Geraden beschrieben. In unserem Beispiel haben wir anhand der Daten einen <span class="math inline">\(y\)</span>-Achsenabschnitt <span class="math inline">\(\hat{\beta}_0\)</span> von <span class="math inline">\(-0.14\)</span> berechnet. D.h ein Weitspringer der mit einer Anlaufgeschwindigkeit von <span class="math inline">\(x = 0\)</span> anläuft, landet <span class="math inline">\(14\)</span>cm hinter der Sprunglinie. Dies macht offensichtlich nicht viel Sinn (warum?). Der Grund warum hier ein offensichtlich unrealistischere Wert berechnet wurde, werden wir später noch genauer betrachten. Wir können trotzdem zwei Eigenschaften von <span class="math inline">\(\hat{\beta}_0\)</span> beobachten. 1) der Koeffizient hat eine Einheit, nämlich die gleiche Einheit wie die Variable <span class="math inline">\(y\)</span>. 2) Ob der Wert zu interpretieren ist, hängt von der Verteilung der Daten ab. Schauen wir uns nun den Steigungskoeffizienten <span class="math inline">\(\hat{\beta}_0\)</span> an. Der Steigungskoeffizient in Formel <span class="math inline">\(\eqref{eq-slm-psform-1}\)</span> zeigt an, wie sich der <span class="math inline">\(y\)</span>-Wert verändert, wenn sich der <span class="math inline">\(x\)</span>-Wert um einen Einheit verändert. In unserem Fall welcher Unterschied zu erwarten ist zwischen zwei Weitspringern die sich in der Anlaufgeschwindigkeit um eine <span class="math inline">\(m/s\)</span> unterscheiden. D.h. der Steigungskoeffizient ist ebenfalls in der Einheit der <span class="math inline">\(y\)</span>-Variable zu interpretieren.</p>
<p>Unsere Trainerin kann jetzt die berechnete Gerade dazu nehmen um zu überprüfen ob es sich lohnen würde Trainingszeit in den Anlauf zu stecken und welche Verbesserung dort zu erwarten sind. Allerdings fehlt dazu noch etwas, wir wissen nämlich noch nicht ob die berechnete Gerade auch wirklich die Daten gut wiederspiegelt. Im Beispiel erscheint dies anhand der Grafik als relativ plausibel. Das muss aber nicht immer so sein. Wir können nämlich für alle möglichen Daten eine Gerade berechnen ohne das diese Gerade die Daten wirklich auch nur annährend korrekt wiedergibt. In den Formeln <span class="math inline">\(\eqref{eq-slm-basics-norm-1}\)</span> und <span class="math inline">\(\eqref{eq-slm-basics-norm-2}\)</span> steht nirgends für welche Daten die Berechnung nur erlaubt ist.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-cubepoly" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_basics_files/figure-html/fig-slm-basics-cubepoly-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;11.8: Gefittete Gerade durch die Daten einer Funktion <span class="math inline">\(f(x) = x^3\)</span>.</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-basics-cubepoly">Abbildung&nbsp;<span>11.8</span></a> sind synthetische Daten der Funktion <span class="math inline">\(f(x) = x^3\)</span> abgebildet und die mittels <span class="math inline">\(\eqref{eq-slm-basics-norm-1}\)</span> berechneten Gerade eingezeichnet. Die Gerade ist zwar in der Lage die ansteigenden Werte zu modellieren aber eben nicht Schwingungen die durch die kubische Abhängigkeit zustande kommen. Aber, nichts verhindert die Anwendung der Formel auf die Daten!</p>
<p>Der gleiche Effekt ist auch in <a href="#fig-slm-basics-sinus">Abbildung&nbsp;<span>11.9</span></a> wieder zu beobachten. Hier besteht eine sinusförmige Abhängigkeit zwischen <span class="math inline">\(y\)</span> und <span class="math inline">\(x\)</span>. Wir können wieder die Normalengleichungen anwenden und erhalten wieder ein Ergebnis für <span class="math inline">\(\hat{\beta}_0\)</span> und <span class="math inline">\(\hat{\beta}_1\)</span>. Allerdings repräsentiert die Gerade in keinster Weise den tatsächlichen Zusammenhang zwischen den Daten wie in <a href="#fig-slm-basics-sinus">Abbildung&nbsp;<span>11.9</span></a> zu beobachten ist.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-sinus" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_basics_files/figure-html/fig-slm-basics-sinus-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;11.9: Gefittete Gerade durch die Daten einer Funktion <span class="math inline">\(f(x) = sin(x) + 3\)</span>.</figcaption>
</figure>
</div>
</div>
</div>
<p>Im nächsten Kapitel werden wir uns daher damit beschäftigen die Repräsentation der Daten näher zu betrachten und zu präzisieren.</p>
<p>Wir nehmen noch eine weitere Eigenschaft der Gerade mit, die zunächst nichts mit der Interpretation der Koeffizienten zu tun hat, aber später noch mal von Interesse sein wird. Die Gerade hat nämlich die Eigenschaft durch den Punkt (<span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(\bar{y}\)</span>) zu gehen. Dies kann daran gesehen werden wenn in die Gleichung <span class="math inline">\(\bar{x}\)</span> für <span class="math inline">\(x_i\)</span> eingesetzt wird. Anhand der Formel <span class="math inline">\(\eqref{eq-slm-basics-norm-2}\)</span> der Normalgleichungen kann die Geradengleichung in der folgenden Form dargestellt werden.</p>
<p><span class="math display">\[
y_i = \hat{\beta}_0 + \hat{\beta}_1 \cdot x_i = \underbrace{\bar{y} - \hat{\beta}_1 \bar{x}}_{\text{Def. }\hat{\beta}_0} + \hat{\beta}_1 \cdot x_i
\]</span></p>
<p>Wird jetzt für <span class="math inline">\(x_i\)</span> der Mittelwer der <span class="math inline">\(x\)</span>-Werte <span class="math inline">\(\bar{x}\)</span> eingesetzt folgt daraus.</p>
<p><span class="math display">\[
y_i = \bar{y} - \hat{\beta}_1 \bar{x} + \hat{\beta}_1 \bar{x} = \bar{y}
\]</span></p>
<p>D.h. für den Wert <span class="math inline">\(\bar{x}\)</span> nimmt die Geradengleichung der Wert <span class="math inline">\(\bar{y}\)</span> an. Für die Sprungdaten ist diese Eigenschaft auch noch mal in <a href="#fig-slm-basics-hatxy">Abbildung&nbsp;<span>11.10</span></a> graphisch dargestellt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-basics-hatxy" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_basics_files/figure-html/fig-slm-basics-hatxy-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;11.10: Regressionsgerade der Sprungdaten und der Punkt <span class="math inline">\((\bar{x}, \bar{y})\)</span></figcaption>
</figure>
</div>
</div>
</div>
<p>Eine weitere Eigenschaft die in weiteren Behandlung der Regression immer wieder auftaucht bezieht sich auf die <span class="math inline">\(x\)</span>-Werte. Bei der Regression wird im Allgemeinen davon ausgegangen, dass die beobachteten <span class="math inline">\(x\)</span>-Werte fixiert sind. D.h. trotzdem die <span class="math inline">\(x\)</span>-Werte bei einem Experiment möglicherweise zufällige Werte angenommen haben, werden diese in den nachfolgenden Analyseschritten als fixiert bzw. gegeben angesehen.</p>
</section>
<section id="die-einfache-lineare-regression-in-r" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="die-einfache-lineare-regression-in-r"><span class="header-section-number">11.6</span> Die einfache lineare Regression in <code>R</code></h2>
<p>In <code>R</code> wird eine Regression mit der Funktion <code>lm()</code> berechnet. Die für uns zunächst wichtigsten Parameter von <code>lm()</code> sind der erste Parameter <code>formula</code> und der zweite Parameter <code>data</code>. Mit der Formel wird der Zusammenhang zwischen den Variablen beschrieben, dabei können die Namen bzw. Bezeichner aus dem <code>tibble()</code> benutzt werden, die an den zweiten Parameter <code>data</code> übergeben werden. D.h. die Spaltennamen aus dem <code>tibble()</code> werden in <code>formula</code> verwendet.</p>
<p>In unserem Weitsprungbeispiel konnten wir in <a href="#tbl-slm-basics-jump-1">Tabelle&nbsp;<span>11.3</span></a> sehen, das das <code>tibble()</code> zwei Spalten mit den Namen <code>v_ms</code>, den Anlaufgeschwindigkeiten, und <code>jump_m</code>, den Weitsprungweiten enthielt. Dementsprechend, müssen wir diese beiden Bezeichner in <code>formula</code> verwenden, um unser Regressionsmodell zu beschreiben. Die Form der Modellbeschreibung folgt, dabei einer bestimmten Syntax die wir uns zunächst anschauen müssen. Zentrales Element der Syntax ist das Tilde Zeichen <code>~</code> (WIN: <kbd>ALTGR-+</kbd>, MAC: <kbd>ALT-n</kbd>), welches interpretiert wird als <em>modelliert mit</em>. Der Term der auf der linken Seite steht bezeichnet die abhängige Variable während die Terme auf der rechten Seite der Tilde stehen die unabhängige Variablen spezifizieren. Dementsprechend kann der Satz <em>“Y wird mittels X modelliert”</em> in die Formelsyntax mit <code>Y ~ X</code> übersetzt. Die komplette Syntax orientiert sich an eine Arbeit von <span class="citation" data-cites="wilkinson1973">Wilkinson und Rogers (<a href="references.html#ref-wilkinson1973" role="doc-biblioref">1973</a>)</span>.</p>
<p>Wenn ein konstanter in der Syntax benötigt wird, dann wird dieser mit einer <span class="math inline">\(1\)</span> bezeichnet. Also zum Beispiel wenn wir die Formel <span class="math inline">\(\eqref{eq-slm-psform-beta}\)</span> modellieren wollen benutzen wir die Syntax <code>y ~ 1 + x</code>. Die beiden Koeffizienten <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> brauchen wir nicht explizit anzugeben, sondern <code>R</code> generiert uns automatisch anhand der Bezeichner Koeffizienten, die allerdings die Namen der Bezeichner bekommen. Dazu kommt noch eine Besonderheit, dass <code>R</code> bei einer Regressionsgleichung automatisch davon ausgeht, dass ein konstanter Term verwendet werden soll, d.h. der Term <code>+1</code> wird automatisch dazugefüht. Wenn wir ein Modell ohne einen <span class="math inline">\(y\)</span>-Achsenabschnitt fitten wollen, dann müssen wir dies <code>R</code> explizit mitteilen, indem wir <code>-1</code> der linken Seite hinzufügen, also z.B. <code>y ~ x - 1</code>. Die Syntax generalisiert dann später einfach, wenn zusätzliche Terme in der multiplen Regression benötigt werden, in dem weitere unabhängige Variablen durch <code>+</code> dazugefügt werden. Dementsprechend würde sich die Formel <code>y ~ x_1 + x_1</code> übersetzen in <em>die abhängige Variable <span class="math inline">\(y\)</span> wird mittels der unabhängigen Variablen <code>x_1</code> und <code>x_2</code> und einem konstaten Term modelliert</em>.</p>
<p>In <a href="#tbl-slm-basics-formelsyntax">Tabelle&nbsp;<span>11.6</span></a> sind weitere Beispiele für die Syntax von Formeln für <code>lm()</code> gezeigt.</p>
<div id="tbl-slm-basics-formelsyntax" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;11.6: Formelsyntaxbeispiele für <code>lm()</code> (y-Ab = y-Achsenabschnitt, StKoef = Steigungskoeffizient)</caption>
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Modell</th>
<th>Formel</th>
<th>Erklärung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(y=\beta_0\)</span></td>
<td><code>y ~ 1</code></td>
<td>y-Achsenabschnitt</td>
</tr>
<tr class="even">
<td><span class="math inline">\(y=\beta_0+\beta_1 \times x_1\)</span></td>
<td><code>y ~ x</code></td>
<td>y-Ab und StKoef</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(y=\beta_0+\beta_1 \times x_1+\beta_2 \times x_2\)</span></td>
<td><code>y ~ x1 + x2</code></td>
<td>y-Ab und 2 StKoe</td>
</tr>
</tbody>
</table>
</div>
<p>Um unsere Weitsprungdaten mittels <code>lm()</code> zu modellieren, müssen wir den folgenden Befehl verwenden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(jump_m <span class="sc">~</span> v_ms, <span class="at">data =</span> jump)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = jump_m ~ v_ms, data = jump)

Coefficients:
(Intercept)         v_ms  
    -0.1385       0.7611  </code></pre>
</div>
</div>
<p>Der Rückgabewert von <code>lm()</code> ist in der Form nicht besonders hilfreich und es werden nur die beiden berechneten Koeffizienten ausgegeben. Dabei bezeichnet der Term <code>(Intercept)</code> den automatisch dazugefügten konstanten Term in der Formel, sprich den <span class="math inline">\(y\)</span>-Achsenabschnitt <span class="math inline">\(\hat{\beta}_0\)</span> und mit <code>v_ms</code> den Steigungskoeffizienten <span class="math inline">\(\hat{\beta}_1\)</span>.</p>
<p>Um aus <code>lm()</code> mehr Informationen heraus zu bekommen, ist es sinnvoll das Ergebnis von <code>lm()</code> einer Variable zuzuweisen. In dem vorliegenden Arbeit wird dazu in den meisten Fällen eine Variante des Bezeichners <code>mod</code> benutzt, als Kurzform vom <em>model</em>. Diese Bezeichnung ist aber wie alle Bezeichner in <code>R</code> vollkommen willkürlich und entspringt nur der Tippfaulheit des Autors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(jump_m <span class="sc">~</span> v_ms, <span class="at">data =</span> jump)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Um mehr Informationen aus dem gefitteten <code>lm()</code>-Objekt zu bekommen kann nun eine der zahlreichen Helferfunktionen verwendet werden. Die wichtigste Funktion ist die <code>summary()</code>-Funktion (<code>?summary.lm</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = jump_m ~ v_ms, data = jump)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.44314 -0.22564  0.02678  0.19638  0.42148 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.13854    0.23261  -0.596    0.555    
v_ms         0.76110    0.02479  30.702   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2369 on 43 degrees of freedom
Multiple R-squared:  0.9564,    Adjusted R-squared:  0.9554 
F-statistic: 942.6 on 1 and 43 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Hier bekommen wir schon deutlich mehr Informationen mitgeteilt. Ganz oben, als erstes wird die <code>lm()</code> übergebene Formel angezeigt. Es folgt ein Abschnitt über die Residuen, gefolgt von den Koeffzienten (<code>Coefficients</code>) und im unteren Abschnitt noch weitere Statistiken. Wir konzentrieren uns zunächst einmal nur auf die Tabelle im Abschnitt <code>Coefficients</code>. Hier begegnen uns wieder in der ersten Spalte die Bezeichner für die beiden <span class="math inline">\(\beta\)</span>s in Form von <span class="math inline">\(\beta_0\)</span> <code>(Intercept)</code> und <span class="math inline">\(\beta_1\)</span> <code>v_ms</code>. In der zweiten Spalte daneben stehen die berechneten Koeffizienten die wir jetzt schon mehrmals gesehen haben. Die weiteren Spalten ignorieren wir zunächst. Im Laufe der folgenden Kapitel werden wir uns die weiteren Statistiken anschauen und deren Bedeutung erarbeiten.</p>
<p>Bei der Benutzung von <code>lm()</code> werden uns noch weitere Helferfunktionen begegnen, die den Umgang mit dem gefitteten Modell vereinfachen. Wollen wir zum Beispiel die beiden Koeffiziente aus dem Modell extrahieren können wir dazu die Funktion <code>coefficients()</code> oder auch nur kurz <code>coef()</code> verwenden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mod)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        v_ms 
 -0.1385361   0.7611019 </code></pre>
</div>
</div>
<p>Die Funktion <code>coef()</code> gibt einen benannten Vektor zurück der entweder über die Bezeichner oder einfach über die Position der Koeffizienten angesprochen werden kann. Möchte ich zum Beispiel den Steigungskoeffizienten extrahieren, kann ich die folgende Syntax verwenden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mod)[<span class="dv">1</span>]</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
 -0.1385361 </code></pre>
</div>
</div>
<p>oder</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mod)[<span class="st">'v_ms'</span>]</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     v_ms 
0.7611019 </code></pre>
</div>
</div>
<p>Ein etwas übersichtlichere Arbeitsweise ist wieder zunächst einmal das Ergebnis von <code>coef()</code> einer Variablen zuweisen und diese dann weiter benutzen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>jump_betas <span class="ot">&lt;-</span> <span class="fu">coef</span>(mod)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>jump_betas[<span class="dv">1</span>]</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
 -0.1385361 </code></pre>
</div>
</div>
<p>Die Koeffizienten kann ich zum Beispiel benutzen um die Regressionsgerade in ein Streudiagramm hinzuzufügen (Das <code>tibble()</code> mit den Sprungdaten hat den Bezeichner <code>jump</code>). Entweder mit dem <code>ggplot2()</code> Grafiksystem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(jump,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> v_ms, <span class="at">y =</span> jump_m)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> jump_betas[<span class="dv">1</span>],</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> jump_betas[<span class="dv">2</span>],</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">'red'</span>) <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slm_basics_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Oder mit den Standard <code>R</code>-Grafiksystem. Hier kann der Funktion <code>abline()</code> das gefittete <code>lm()</code>-Objekt direkt übergeben werden und die Koeffizienten werden automatisch extrahiert.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(jump_m <span class="sc">~</span> v_ms, <span class="at">data =</span> jump)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod, <span class="at">col =</span> <span class="st">'red'</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="slm_basics_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Schauen wir uns noch mal ein ganz einfaches Beispiel, bei dem wir tatsächlich wissen welcher Zusammenhang zwischen den beiden Variablen. Wir halten das Beispiel ganz einfache und nehmen vier verschiedene <span class="math inline">\(x\)</span>-Werte mit <span class="math inline">\(x_i = i\)</span>. Wir setzen <span class="math inline">\(\beta_0 = 1\)</span> und <span class="math inline">\(\beta_1 = 0.5\)</span>. Wir generieren die vier Werte mit <code>R</code>, speichern diese in einem <code>tibble()</code> mit dem Bezeichner <code>data</code> und berechnen die resultierenden Koeffizienten mittels <code>lm()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="dv">1</span> <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> x</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, data)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mod)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           x 
        1.0         0.5 </code></pre>
</div>
</div>
<p>Und tatsächlich können wir die korrekten Koeffizienten mittels der einfachen linearen Regression wiedergewinnen. Diesen Ansatz mittels synthetisch generierten Daten die eingeführten Konzepte und Ansätze zu überprüfen werden wir im weiteren Verlauf des Skripts immer wieder anwenden, da er die Möglichkeit bietet relativ einfach und nachvollziehbar das Verhalten verschiedener Ansätze auszutesten.</p>
<p>Zusammenfassend lässt sich sagen, das wir jetzt gelernt haben wie wir ein einfaches Regressionmodell der Form Formel <span class="math inline">\(\eqref{eq-slm-psform-beta}\)</span> an einen beliebigen Datensatz fitten können. Die Berechnung der beiden Koeffizienten <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> erfolgt mittels Formeln <span class="math inline">\(\eqref{eq-slm-basics-norm-1}\)</span> und <span class="math inline">\(\eqref{eq-slm-basics-norm-2}\)</span>. Dabei berechnen wir die Koeffizienten nicht von Hand sondern lassen die von <code>R</code> mittels der <code>lm()</code> durchführen. Die Berechnung ist dabei vollkommen mechanisch und die Koeffizienten per-se sagen nichts darüber aus, ob das lineare Modell die Daten tatsächlich auch widerspiegelt. Dazu müssen wir noch etwas mehr Theorie aufbauen um Aussagen darüber zu treffen ob das Modell adäquat ist. Dies gehen wir in den folgenden Abschnitten und Kapiteln an.</p>
</section>
<section id="sec-step-by-step-normal" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="sec-step-by-step-normal"><span class="header-section-number">11.7</span> Schritt-für-Schritt Herleitung der Normalengleichungen (advanced)</h2>
<p>Um die Herleitung der Normalengleichungen Schritt-für-Schritt nachvollziehen zu können benötigen wir zunächst einmal ein paar algebraische Tricks.</p>
<p>Für den Mittelwert gilt: <span class="math display">\[
\bar{x} = \frac{1}{n}\sum x_i \Leftrightarrow \sum x_i = n \bar{x}
\]</span></p>
<p>Bei Summen und konstanten <span class="math inline">\(a\)</span> konstant gilt: <span class="math display">\[\begin{align}
    \sum a &amp;= n a \\
    \sum a x_i &amp;= a \sum x_i \\
    \sum (x_i + y_i) &amp;= \sum x_i + \sum y_i
\end{align}\]</span></p>
<p>Wenn eine Summe abgeleitet wird, kann in die Ableitung in die Summe reingezogen werden. <span class="math display">\[
\frac{d}{d x}\sum f(x) = \sum\frac{d}{d x} f(x)
\]</span></p>
Hier ein zwei Umformungen bei Summen und dem Kreuzprodukt bzw. dem Quadrat. <span class="math display">\[\begin{alignat}{2}
&amp;&amp; \sum(x_i-\bar{x})(y_i-\bar{y}) \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum (x_iy_i-\bar{x}y_i-x_i\bar{y}+\bar{x}\bar{y}) \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum x_i y_i - \sum\bar{x}y_i - \sum x_i \bar{y} + \sum \bar{x} \bar{y} \nonumber \\
\Leftrightarrow\mkern40mu&amp;&amp;  \sum x_iy_i - n\bar{x}\bar{y}-n\bar{x}\bar{y}+n\bar{x}\bar{y} \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum x_iy_i - n\bar{x}\bar{y} \nonumber
\end{alignat}\]</span> <span class="math display">\[\begin{alignat}{2}
&amp;&amp; \sum(x_i - \bar{x})^2 \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum(x_i^2 - 2 x_i \bar{x} + \bar{x}^2) \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum x_i^2 - 2\bar{x}\sum x_i + \sum\bar{x}^2 \nonumber\\
\Leftrightarrow\mkern40mu &amp;&amp; \sum x_i^2 - 2\bar{x}n\bar{x} + n\bar{x}^2 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum x_i^2 - n \bar{x}^2 \nonumber
\end{alignat}\]</span>
<p>Zurück zu unserem Problem. Es gilt <span class="math inline">\(E\)</span> zu minimieren:</p>
<p><span class="math display">\[\begin{alignat}{2}
&amp;&amp; E = \sum e_i^2 = \sum (y_i - \hat{y}_i)^2 \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum (y_i - (\beta_0 + \beta_1 x_i))^2 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum (y_i - \beta_0 - \beta_1 x_i)^2 \nonumber
\end{alignat}\]</span></p>
<p>Die Gleichung hängt von zwei Variablen <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>. Um das Minimum der Gleichung zu erhalten, verfährt man wie in der Schule, indem man die Ableitung gleich Null setzt. Der vorliegenden Fall ist jedoch etwas komplizierter, da die Gleichung von zwei Variablen abhängt. Daher müssen wir die partiellen Ableitungen <span class="math inline">\(\frac{\partial}{\partial \beta_0}\)</span> und <span class="math inline">\(\frac{\partial}{\partial \beta_1}\)</span> verwendet. Wir erhalten dadurch ein Gleichungssystem mit zwei Gleichungen (die jeweiligen Ableitungen) in zwei Unbekannten (<span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span>). Die Lösung erfolgt, indem zuerst eine Gleichung nach der einen Unbekannten umgestellt wird und das Ergebnis dann in die andere Gleichung eingesetzt wird.</p>
<p>Wir beginnen mit der partiellen Ableitung nach <span class="math inline">\(\beta_0\)</span> für den y-Achsenabschnitt. (Zurück an die Schule erinnern: Äußere Ableitung mal innere Ableitung)</p>
<p><span class="math display">\[\begin{alignat}{2}
&amp;&amp; \frac{\partial \sum (y_i - \beta_0 - \beta_1 x_i)^2}{\partial \beta_0} \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum\frac{\partial}{\partial \beta_0}(y_i - \beta_0- \beta_1 x_i)^2 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum 2(y_i - \beta_0- \beta_1 x_i) (-1) \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; -2 \sum (y_i - \beta_0- \beta_1 x_i) \nonumber
\end{alignat}\]</span> Zum minimieren gleich Null setzen. <span class="math display">\[\begin{alignat}{2}
&amp;&amp; -2 \sum (y_i - \beta_0- \beta_1 x_i) = 0 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum (y_i - \beta_0- \beta_1 x_i) = 0 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum y_i - \sum \beta_0- \sum \beta_1 x_i = 0 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; n \bar{y} - n \beta_0- \beta_1 n \bar{x} = 0 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \bar{y} - \beta_0- \beta_1 \bar{x} = 0 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \bar{y} - \beta_1 \bar{x} = \beta_0\nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \beta_0= \bar{y} - \beta_1 \bar{x}
\end{alignat}\]</span></p>
<p>Es folgt nach dem gleichen Prinzip die Herleitung für die Steigung <span class="math inline">\(\beta_1\)</span> und indem die Lösung für <span class="math inline">\(\beta_0\)</span> eingesetzt wird.</p>
<p><span class="math display">\[\begin{alignat}{2}
&amp;&amp; \frac{\partial \sum (y_i - \beta_0 - \beta_1x_i)^2}{\partial \beta_1} \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum\frac{\partial}{\partial b}(y_i - \beta_0 - \beta_1x_i)^2 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum2(y_i - \beta_0 - \beta_1x_i) -x_i \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; -2 \sum(y_i - \beta_0 - \beta_1x_i)x_i
\end{alignat}\]</span> Wiederum gleich Null setzen. <span class="math display">\[\begin{alignat}{2}
&amp;&amp; -2 \sum(y_i - \beta_0 - \beta_1x_i)x_i = 0 \nonumber\\
\Leftrightarrow\mkern40mu &amp;&amp; \sum (y_i - \beta_0 - \beta_1x_i)x_i = 0 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum (y_i x_i - \beta_0 x_i - \beta_1x_i x_i) = 0 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum y_i x_i - \beta_0 \sum x_i - b\sum x_i^2 = 0 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum y_i x_i - n \beta_0 \bar{x} - \beta_1\sum x_i^2 = 0 \nonumber
\end{alignat}\]</span> Einsetzen der Lösung für <span class="math inline">\(\beta_0\)</span> führt zu: <span class="math display">\[\begin{alignat}{2}
\Leftrightarrow\mkern40mu &amp;&amp; \sum y_i x_i - n (\bar{y} - \beta_1 \bar{x}) \bar{x} - \beta_1\sum x_i^2 = 0 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum y_i x_i - n\bar{y}\bar{x} + n \beta_1\bar{x}^2 - \beta_1\sum x_i^2 = 0 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum y_i x_i - n\bar{y}\bar{x} = \beta_1 \sum x_i^2 - \beta_1n \bar{x}^2 \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \sum (x_i-\bar{x})(y_i-\bar{y}) = \beta_1 (\sum x_i^2 - n\bar{x}^2) \nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \frac{\sum (x_i-\bar{x})(y_i-\bar{y})}{\sum x_i^2 - n\bar{x}^2} = \beta_1\nonumber \\
\Leftrightarrow\mkern40mu &amp;&amp; \beta_1= \frac{\sum (x_i-\bar{x})(y_i-\bar{y})}{\sum(x_i-\bar{x})^2} \nonumber
\end{alignat}\]</span></p>
<p>Somit erhält man die beiden Normalengleichungen der Regression.</p>
<p>Über diese beiden Gleichungen erhalten wir die gewünschten Koeffizienten <span class="math inline">\(\hat{\beta_0}\)</span> und <span class="math inline">\(\hat{\beta_1}\)</span>. Die Methode wird als die als die Methode der kleinsten Quadrate bezeichnet oder im Englischen Root-Mean-Square (RMS).</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-wilkinson1973" class="csl-entry" role="listitem">
Wilkinson, G. N., und C. E. Rogers. 1973. <span>„Symbolic description of factorial models for analysis of variance“</span>. <em>Applied Statistics</em> 22 (3): 392–99.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./slm_title.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Das einfache Regressionmodell</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./slm_inference.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inferenz</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>