<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Skriptum - Fortgeschrittene Statistik - 13&nbsp; Modellfit</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./slm_prediction.html" rel="next">
<link href="./slm_inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>
<script>
  MathJax = {
    tex: {
      tags: 'ams'  // should be 'ams', 'none', or 'all'
    }
  };
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./slm_title.html">Das einfache Regressionmodell</a></li><li class="breadcrumb-item"><a href="./slm_model_fit.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Modellfit</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Skriptum - Fortgeschrittene Statistik</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./r_startup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eine Schnelleinführung in R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Eine Übersicht über <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_kickoff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title"><code>R</code> Kickoff</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_example_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Ein Beispielworkflow mit Skripten in <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Einfache Datenbearbeitung und Visualisierung in <code>R</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_literate_programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Literate programming in <code>R</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./stats_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistik</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Eine kleine Welt der Unsicherheit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistische Signifikanz, p-Wert und Power</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Parameterschätzung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Theoretische Verteilungen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stats_hypotheses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hypothesen testen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./slm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das einfache Regressionmodell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inferenz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_model_fit.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Modellfit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./slm_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Vorhersage</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mlm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Interaktionseffekte</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_dummy_coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Integration von nominale Variablen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mlm_hierarchies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Modellhierarchien</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./lm_title.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Das allgemeine lineare Modell</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lm_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Synthese</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatur</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#residuen" id="toc-residuen" class="nav-link active" data-scroll-target="#residuen"><span class="header-section-number">13.1</span> Residuen</a>
  <ul class="collapse">
  <li><a href="#quantile-quantile-plots" id="toc-quantile-quantile-plots" class="nav-link" data-scroll-target="#quantile-quantile-plots"><span class="header-section-number">13.1.1</span> Quantile-Quantile-Plots</a></li>
  <li><a href="#qq-plot-in-r" id="toc-qq-plot-in-r" class="nav-link" data-scroll-target="#qq-plot-in-r"><span class="header-section-number">13.1.2</span> qq-Plot in <code>R</code></a></li>
  <li><a href="#standardisierte-residuen" id="toc-standardisierte-residuen" class="nav-link" data-scroll-target="#standardisierte-residuen"><span class="header-section-number">13.1.3</span> Standardisierte Residuen</a></li>
  <li><a href="#studentized-residuals" id="toc-studentized-residuals" class="nav-link" data-scroll-target="#studentized-residuals"><span class="header-section-number">13.1.4</span> Studentized Residuals</a></li>
  <li><a href="#übersicht-über-die-residuenarten" id="toc-übersicht-über-die-residuenarten" class="nav-link" data-scroll-target="#übersicht-über-die-residuenarten"><span class="header-section-number">13.1.5</span> Übersicht über die Residuenarten</a></li>
  <li><a href="#ausgabe-von-summary-continued" id="toc-ausgabe-von-summary-continued" class="nav-link" data-scroll-target="#ausgabe-von-summary-continued"><span class="header-section-number">13.1.6</span> Ausgabe von <code>summary()</code> (continued)</a></li>
  <li><a href="#zum-nachlesen" id="toc-zum-nachlesen" class="nav-link" data-scroll-target="#zum-nachlesen"><span class="header-section-number">13.1.7</span> Zum Nachlesen</a></li>
  </ul></li>
  <li><a href="#einflussmetriken" id="toc-einflussmetriken" class="nav-link" data-scroll-target="#einflussmetriken"><span class="header-section-number">13.2</span> Einflussmetriken</a>
  <ul class="collapse">
  <li><a href="#dffits-difference-in-fits" id="toc-dffits-difference-in-fits" class="nav-link" data-scroll-target="#dffits-difference-in-fits"><span class="header-section-number">13.2.1</span> DFFITS (difference in fits)</a></li>
  <li><a href="#cook-abstand" id="toc-cook-abstand" class="nav-link" data-scroll-target="#cook-abstand"><span class="header-section-number">13.2.2</span> Cook-Abstand</a></li>
  <li><a href="#dfbetas" id="toc-dfbetas" class="nav-link" data-scroll-target="#dfbetas"><span class="header-section-number">13.2.3</span> DFBETAS</a></li>
  <li><a href="#übersicht-über-die-einflussmetriken" id="toc-übersicht-über-die-einflussmetriken" class="nav-link" data-scroll-target="#übersicht-über-die-einflussmetriken"><span class="header-section-number">13.2.4</span> Übersicht über die Einflussmetriken</a></li>
  <li><a href="#zum-nacharbeiten" id="toc-zum-nacharbeiten" class="nav-link" data-scroll-target="#zum-nacharbeiten"><span class="header-section-number">13.2.5</span> Zum Nacharbeiten</a></li>
  </ul></li>
  <li><a href="#diagnoseplots-in-r" id="toc-diagnoseplots-in-r" class="nav-link" data-scroll-target="#diagnoseplots-in-r"><span class="header-section-number">13.3</span> Diagnoseplots in <code>R</code></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Modellfit</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Nachdem ein Modell mittels einer einfachen linearen Regression an die Daten gefittet wurde, sollte immer überprüft werden ob das Modell tatsächlich auch den Annahmen entspricht. Ein zentrales Mittel dazu ist eine Analyse der Residuen.</p>
<section id="residuen" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="residuen"><span class="header-section-number">13.1</span> Residuen</h2>
<p>Dazu schauen wir uns zunächst noch einmal an, was überhaupt Residuen <span class="math inline">\(e_i\)</span> sind und gehen noch mal von den grundlegenden Modellannahmen aus (siehe Formel <span class="math inline">\(\eqref{eq-sim-model-lr}\)</span>).</p>
<p><span class="math display">\[\begin{equation}
y_i = \beta_0 + \beta_1 \cdot x_i + \epsilon_i, \qquad \epsilon_i \sim \mathcal{N}(0,\sigma^2)
\label{eq-sim-model-lr}
\end{equation}\]</span></p>
<p>Das lineare Regressionsmodell geht von einem linearen Zusammenhang in den Koeffizienten zwischen der Variablen <span class="math inline">\(x_i\)</span> und den Variablen <span class="math inline">\(y_i\)</span> aus. Additiv kommt daz ein normalverteilter Fehler <span class="math inline">\(\epsilon_i\)</span>. Die Normalverteilung der <span class="math inline">\(\epsilon_i\)</span> habem einen Erwartungswert von <span class="math inline">\(\mu = 0\)</span> und eine Standardabweichung von <span class="math inline">\(\sigma\)</span>. Die Standardabweichung <span class="math inline">\(\sigma\)</span> ist zunächst unbekannt und muss über die Daten abgeschätzt werden. Dies führt dazu, dass <span class="math inline">\(y_i\)</span> für jeden gegebenen Wert von <span class="math inline">\(x_i\)</span> einer Normalverteilung mit <span class="math inline">\(\mathcal{N}(\beta_0 + \beta_1 x_i, \sigma^2)\)</span> folgen und der bereits bekannten graphischen Darstellung (siehe <a href="#fig-slm-model-resid-1">Abbildung&nbsp;<span>13.1</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-resid-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-resid-1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.1: Beispiel einer Regressionsgeraden und der Verteilung der Residuen um den Vorhersagewert <span class="math inline">\(\hat{y_i}\)</span></figcaption>
</figure>
</div>
</div>
</div>
<p>Für jeden gegebenen Wert von <span class="math inline">\(X\)</span> sind die <span class="math inline">\(Y\)</span>-Werte Normalverteilt. Die Varianz dieser Normalverteilungen ist gleich <span class="math inline">\(\sigma\)</span> während der Mittelwert <span class="math inline">\(\mu\)</span> immer um den Wert der Regressionsgeraden verschoben ist. D.h. die Streuung von <span class="math inline">\(\epsilon_i\)</span> überträgt sich auf die Streuung von <span class="math inline">\(y_i\)</span> für jeden gegebenen <span class="math inline">\(X\)</span>-Wert. Ohne den zufälligen Einfluss der Fehlerwerte würden wir alle <span class="math inline">\(y_i\)</span>-Werte perfekt auf der Regressionsgeraden erwarten. Dies deutet daher auch schon eine Möglichkeit an die Residuen <span class="math inline">\(\epsilon_i\)</span> mittels der Daten abzuschätzen. Man verwendet die Abweichungen der beobachteten Werten <span class="math inline">\(y_i\)</span> von den vorhergesagten Werten <span class="math inline">\(\hat{y}_i\)</span> auf der Regressionsgeraden (siehe Formel <span class="math inline">\(\eqref{eq-sim-model-res-1}\)</span>).</p>
<p><span class="math display">\[\begin{equation}
\hat{\epsilon}_i = e_i = y_i - \hat{y_i}
\label{eq-sim-model-res-1}
\end{equation}\]</span></p>
<p>Diese Abweichungen <span class="math inline">\(e_i\)</span> können als Schätzer <span class="math inline">\(\hat{\epsilon}_i\)</span> für die wahren Residuen <span class="math inline">\(\epsilon_i\)</span> verwendet werden (siehe <a href="#fig-slm-model-resid-2">Abbildung&nbsp;<span>13.2</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-resid-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-resid-2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.2: Examplarische Darstellung der Berechnung der Residuen <span class="math inline">\(e_i\)</span> als Abweichung der beobachteten Werte <span class="math inline">\(y_i\)</span> von den vorhergesagten Werten <span class="math inline">\(\hat{y}_i\)</span></figcaption>
</figure>
</div>
</div>
</div>
<p>Da die Normalverteilungen der <span class="math inline">\(\epsilon_i\)</span> für jeden <span class="math inline">\(X\)</span>-Wert immer gleich sein sollten bis auf die Verschiebung von <span class="math inline">\(\mu_{Y|X}\)</span>, deutet dies ebenfalls eine erste Möglichkeit an, die Modellannahmen graphisch zu überprüfen. Wenn die Residuen <span class="math inline">\(e_i\)</span> geben die vorhergesagten Werte <span class="math inline">\(\hat{y}_i\)</span> abgetragen werden, dann sollte die Verteilung der Residuen <span class="math inline">\(e_i\)</span> überall nahezu gleich sein, da die Streuung <span class="math inline">\(\sigma\)</span> unabhängig von der <em>Position</em> auf der Regressionsgerade ist. In <code>R</code> können die Residuen mittels der Funktion <code>residuals()</code> bzw. der Kurzform <code>resid()</code> ermittelt werden. <code>residuals()</code> erwartet als Parameter das gefittete <code>lm()</code>-Objekt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(mod)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          1           2           3           4           5           6 
 -9.3009275  -9.3682884 -11.2176585  -5.5721082  -6.3635647  -7.4162019 
          7           8           9          10          11          12 
 -3.9665569  -8.7152962  -3.8032898  -0.4662810  -2.0491941  -2.1323841 
         13          14          15          16          17          18 
  0.1867102  -0.3382894  -2.7300208  -4.0317532  -6.1475804  -0.3782884 
         19          20          21          22          23          24 
  1.1267111  -0.4588401  -2.0417532  -2.5546673  -0.2276585   2.3352546 
         25          26          27          28          29          30 
 -3.2075794   2.7949787   2.9982458   2.4379709   1.1162385   3.1894284 
         31          32          33          34          35          36 
  7.8049787  -0.9063196   4.0336013  11.3778918   7.6817897   8.6991516 
         37          38          39          40          41 
 12.3052546   7.2595065  20.9634431  -1.3171838  -1.5994700 </code></pre>
</div>
</div>
<p>Die anhand des Modells vorhergesagten Werte <span class="math inline">\(\hat{y_i}\)</span> werden der Funktion <code>predict()</code> berechnet. Diese Funktion werden wir uns im nächsten Kapitel noch ausführlich betrachten. Als Parameter wird wiederum das gefittete <code>lm()</code>-Modell übergeben.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mod)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7        8 
13.35093 14.39829 16.24766 13.61211 14.40356 15.45620 12.02656 16.77530 
       9       10       11       12       13       14       15       16 
12.82329 11.49628 13.07919 14.14238 12.82329 13.34829 15.72002 17.04175 
      17       18       19       20       21       22       23       24 
19.15758 14.39829 13.87329 15.45884 17.04175 17.57467 16.24766 14.66475 
      25       26       27       28       29       30       31       32 
20.20758 15.19502 15.99175 17.57203 18.89376 17.83057 15.19502 23.90632 
      33       34       35       36       37       38       39       40 
19.94640 13.61211 17.30821 17.31085 14.66475 20.74049 12.02656 13.32718 
      41 
13.60947 </code></pre>
</div>
</div>
<p>Beide Funktionen, <code>resid()</code> und <code>predict()</code> geben die berechneten Werte in der Reihenfolge aus, in der die Originaldaten an <code>lm()</code> übergeben wurde. D.h. <span class="math inline">\(e_1\)</span> und <span class="math inline">\(\hat{y}_1\)</span> gehören zum ersten <span class="math inline">\(X\)</span>-Wert <span class="math inline">\(x_1\)</span> aus den Originaldaten. Mit Hilfe dieser beiden Variablen kann nun ein Residuenplot erstellt werden (siehe <a href="#fig-sim-model-rplot-1">Abbildung&nbsp;<span>13.3</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sim-model-rplot-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-sim-model-rplot-1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.3: Residuenplot der Residuen <span class="math inline">\(e_i\)</span> gegen die vorhergesagten Werte <span class="math inline">\(\hat{y}_i\)</span></figcaption>
</figure>
</div>
</div>
</div>
<p>Der Plot sollte im Optimalfall so aussehen, dass die Residuen <span class="math inline">\(e_i\)</span> gleichmäßig oberhalb und unterhalb um die Nulllinie verteilt sind und keine weiteren Strukturen oder Muster im Zusammenhang mit <span class="math inline">\(\hat{y}_i\)</span> zu erkennen sind. In dem Residuenplot in <a href="#fig-sim-model-rplot-1">Abbildung&nbsp;<span>13.3</span></a> ist zunächst einmal kein größeres Problem zu erkennen, bis auf den einen Wert links oben.</p>
<p>Um besser zu Verstehen wir Problem aussehen könnten, schauen wir uns zwei Residuenplots an, bei denen eine Struktur zu erkennen ist (siehe <a href="#fig-sim-model-rplot-2">Abbildung&nbsp;<span>13.4</span></a>)</p>
<div id="fig-sim-model-rplot-2" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-sim-model-rplot-2-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-sim-model-rplot-2-1.png" class="img-fluid figure-img" data-ref-parent="fig-sim-model-rplot-2" width="672"></p>
<figcaption class="figure-caption">(a) Parabelförmiger Zusammenhang zwischen <span class="math inline">\(e_i\)</span> und <span class="math inline">\(\hat{y}_i\)</span></figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-sim-model-rplot-2-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-sim-model-rplot-2-2.png" class="img-fluid figure-img" data-ref-parent="fig-sim-model-rplot-2" width="672"></p>
<figcaption class="figure-caption">(b) Ansteigende Streuung mit größer werdendem <span class="math inline">\(\hat{y}_i\)</span></figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;13.4: Residuenplots die Probleme anzeigen.</figcaption><p></p>
</figure>
</div>
<p>In <a href="#fig-sim-model-rplot-2-1">Abbildung&nbsp;<span>13.4 (a)</span></a> ist ein parabelförmiger Zusammenhang zwischen <span class="math inline">\(e_i\)</span> und <span class="math inline">\(\hat{y}_i\)</span> zu erkennen. Für kleine und große <span class="math inline">\(\hat{y}_i\)</span> Werte sind die Residuen <span class="math inline">\(e_i\)</span> negativ während für mittlere Werte von <span class="math inline">\(\hat{y}_i\)</span> die Residuen <span class="math inline">\(e_i\)</span> positiv sind. Diese deutet darauf hin, das zusäztliche Struktur in den Daten nicht im Modell erfasst wird und führt dazu dass die Modellannahmen der Normalverteilung der <span class="math inline">\(\epsilon_i\)</span> nicht erfüllt sind.</p>
<p>In <a href="#fig-sim-model-rplot-2-2">Abbildung&nbsp;<span>13.4 (b)</span></a> ist dagegen eine anderes Problem zu beobachten, die Residuen <span class="math inline">\(e_i\)</span> zeigen zwar keine Struktur bezüglich positiv zu negativen Werten, allerdings werden die Abweichung von <span class="math inline">\(0\)</span> mit größer werdenen <span class="math inline">\(\hat{y}_i\)</span> immer stärker. Dies deutet darauf hin, das die Streuung der Daten nicht gleich ist. Dies wird als Heteroskedastizität bezeichnet und deutet wiederum auf eine Verletzung der Annahmen bei der Homoskedastitzität ausgegangen wird. D.h. die Streuung soll über den gesamten Bereich von <span class="math inline">\(\hat{y}_i\)</span> gleich bleiben.</p>
<div id="def-homoscedasticity" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.1 (Homoskedastizität) </strong></span>Wenn die Größe der Varianz der Residuen <span class="math inline">\(\epsilon_i\)</span> in einem Regressionsmodell unabhängig von der Größe der Vorhersagevariable <span class="math inline">\(X_i\)</span> ist, wird dies als Homoskedastizität bezeichnet. Die Streuung der Residuen ist dann für alle Werte <span class="math inline">\(X_i\)</span> gleich. Wenn dies nicht der Fall ist, wird von Heteroskedastizität gesprochen.</p>
</div>
<p>Da die Varianz also konstant für alle Werte von <span class="math inline">\(X_i\)</span> ist, trifft dies ebenfalls für die vorhergesagten Werte <span class="math inline">\(\hat{Y}_i\)</span> zu. Daher werden bei vielen der Plots die Residuen <span class="math inline">\(\hat{\epsilon}_i\)</span> gegen die <span class="math inline">\(\hat{Y_i}\)</span> abgetragen. Dies hat den Vorteil, dass später bei der multiplen Regression die gleiche Art von Graphen benutzt werden kann, um Homoskeastizität zu analysieren.</p>
<p>Eine weitere Möglichkeit die Verteilung der Residuen zu überprüfen ist die Anfertigung von sogenannten qq-Plots. Dies ermöglichen etwas strukturierter die Verteilung der Residuen zu überprüfen.</p>
<section id="quantile-quantile-plots" class="level3" data-number="13.1.1">
<h3 data-number="13.1.1" class="anchored" data-anchor-id="quantile-quantile-plots"><span class="header-section-number">13.1.1</span> Quantile-Quantile-Plots</h3>
<p>qq-Plot ist die Kurzform von Quantile-Quantile-Plot. D.h. es werden die Quantilen von zwei Variablen gegeneinander abgetragen. Um die Funktionsweise besser zu verstehen schauen wir uns erst einmal ein Spielzeugbeispiel an. In <a href="#tbl-slm-model-toy-1">Tabelle&nbsp;<span>13.1</span></a> ist eine kleiner Datensatz mit <span class="math inline">\(n = 5\)</span> Datenpunkten angezeigt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-slm-model-toy-1" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;13.1: Spielzeugbeispieldaten mit <span class="math inline">\(n=5\)</span></caption>
<thead>
<tr class="header">
<th style="text-align: right;">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-2.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-1.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Wir wollen jetzt überprüfen ob dieser Datensatz einer Normalverteilung folgt (Wohlwissend das mit fünf Datenpunkten keine Verteilungsannahme überprüft werden kann). Dazu schauen wir uns zunächst noch einmal die bekannte Standardnormalverteilung <span class="math inline">\(\Phi(z) = \mathcal{N}(\mu=0,\sigma^2=1)\)</span> an (siehe <a href="#fig-slm-model-toy-1">Abbildung&nbsp;<span>13.5</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-toy-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-toy-1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.5: Dichtefunktion der Standardnormalverteilung</figcaption>
</figure>
</div>
</div>
</div>
<p>Im ersten Schritt unterteilen wir die Standardnormalverteilung <span class="math inline">\(\Phi(z)\)</span> in <span class="math inline">\(n+1 = 6\)</span> gleich große Flächen. D.h. die durch die Flächen bestimmten Abschnitte haben alle die gleiche Wahrscheinlichkeit (=Fläche unter der Dichtefunktion). Die Flächen werden durch jeweiligen Trennpunkte unterteilt die gleichzeitig die Quantilen sind.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-toy-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-toy-2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.6: Unterteilung der Standardnormalverteilung in sechs gleich große Flächen</figcaption>
</figure>
</div>
</div>
</div>
<p>In unserem Fall haben wir <span class="math inline">\(n=5\)</span> Datenpunkte, unterteilen also unsere Verteilung in <span class="math inline">\(6\)</span> Abschnitte die jeweils eine Fläche von <span class="math inline">\(p = \frac{1}{6} = 0.17\)</span> haben. D.h. <span class="math inline">\(\frac{1}{6}\)</span> der Werte von <span class="math inline">\(\Phi(x)\)</span> liegen links des ersten Trennpunktes, <span class="math inline">\(\frac{2}{6}\)</span> der Werte von <span class="math inline">\(\Phi(x)\)</span> liegen links des zweiten Trennpunktes, usw. D.h. die Trennpunkte bestimmen die jeweiligen Quantilen, oder genauer die theoretischen Quantilen die unter der Verteilungsannahme erwartet werden.</p>
<p>Die Idee hinter dem qq-Plot besteht nun darin, die empirischen Quantilen gegen die theoretischen Quantilen abzutragen (siehe <a href="#fig-slm-model-qqconcept">Abbildung&nbsp;<span>13.7</span></a>). Wenn die beobachteten Daten aus der gleichen Verteilung wie die theoretische Verteilung stammen, dann sollten die Punkte einer Geraden folgen. Die Steigung der Geraden ist <span class="math inline">\(1\)</span>, wenn es sich um die identischen Verteilungen handelt. Wenn die Steigung <span class="math inline">\(\neq1\)</span> ist, dann kommen die Datenpunkte aus der gleichen Familie sind aber um einen Skalierungsfaktor unterschiedlich bzw. um den Mittelwert verschoben. Die Punkte sollten aber trotzdem auf einer Geraden liegen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-qqconcept" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-qqconcept-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.7: Skizze der theoretischen und der empirischen Verteilung mit unterschiedlicher Skalierung (Faktor <span class="math inline">\(2\times\)</span>) aber aus der gleichen Verteilungsfamilie. In beiden Graphen ist die gleiche Quartile markiert</figcaption>
</figure>
</div>
</div>
</div>
<p>Um die empirischen Quartilen zu bestimmen, werden dazu zunächst die beobachteten Datenpunkte aus <a href="#tbl-slm-model-toy-1">Tabelle&nbsp;<span>13.1</span></a> aufsteigend nach der Größe sortiert (siehe <a href="#tbl-slm-model-toy-2">Tabelle&nbsp;<span>13.2</span></a>). Diese Werte können als <em>empirische</em> Quantilen bezeichnet werden. Unter der Annahme, dass die Werte eine repräsentative Stichprobe aus der Verteilung darstellen, erwarten wir, dass wenn wir weitere Werte beobachten würden, etwa <span class="math inline">\(\frac{1}{6}\)</span> der Werte kleiner als der kleinste Wert wären, <span class="math inline">\(\frac{2}{6}\)</span> der weiteren Werte kleiner als der 2. kleinste Wert wären und so weiter und so fort.</p>
<div id="tbl-slm-model-toy-2" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;13.2: Sortierte Datenwerte des Spielzeugbeispiels</caption>
<thead>
<tr class="header">
<th>kleinster</th>
<th>2.kleinster</th>
<th>mittlerer</th>
<th>2.größter</th>
<th>größter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>-2</td>
<td>-1.2</td>
<td>0.1</td>
<td>5</td>
<td>7</td>
</tr>
</tbody>
</table>
</div>
<p>Daher, wenn die beobachteten Werte der angenommenen theoretischen Verteilung folgen, dann sollte ein Graph der empirischen Quartilen gegen die theoretischen Quartilen nahezu (Stichprobenvariabilität) einer Geraden folgen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-toy-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-toy-3-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.8: Streudiagramm der empirischen Werte gegen die theoretischen Quantilen</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-model-toy-3">Abbildung&nbsp;<span>13.8</span></a> sind die empirischen Quartilen gegen die theoretischen Quantilen für unser kleines Beispiel abgetragen. Tatsächlich ist es in diesem Fall schwierig eine Gerade zu erkennen bzw. von einer zu sprechen, da es sich nur um besagte fünf Wert handelt. Nochmals, mit <span class="math inline">\(n=5\)</span> kann eine realistische Verteilungsannahme nicht überprüft werden.</p>
<p>Wenn der Datensatz größer ist, dann eignet sich ein qq-Plot allerdings sehr gut Abweichungen zu erkennen. In <a href="#fig-slm-model-qqplots">Abbildung&nbsp;<span>13.9</span></a> sind verschiedene Beispiele abgetragen.</p>
<div id="fig-slm-model-qqplots" class="cell quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-slm-model-qqplots-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-qqplots-1.png" class="img-fluid figure-img" data-ref-parent="fig-slm-model-qqplots" width="672"></p>
<figcaption class="figure-caption">(a) Perfekt</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-slm-model-qqplots-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-qqplots-2.png" class="img-fluid figure-img" data-ref-parent="fig-slm-model-qqplots" width="672"></p>
<figcaption class="figure-caption">(b) Enden schwer</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-slm-model-qqplots-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-qqplots-3.png" class="img-fluid figure-img" data-ref-parent="fig-slm-model-qqplots" width="672"></p>
<figcaption class="figure-caption">(c) Enden leicht</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-slm-model-qqplots-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-qqplots-4.png" class="img-fluid figure-img" data-ref-parent="fig-slm-model-qqplots" width="672"></p>
<figcaption class="figure-caption">(d) Rechtsschief</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;13.9: Beispiele für verschiedenen qq-Plots</figcaption><p></p>
</figure>
</div>
<p>In <a href="#fig-slm-model-qqplots-1">Abbildung&nbsp;<span>13.9 (a)</span></a> ist ein perfekter Zusammenhang zwischen den empirischen und den theoretischen Quantilen abgebildet. In diesem Falle wurden synthetisch für 50 normalverteiltet Zufallsdaten ein qq-Plot erstellt. Es ist zu sehen, das tatsächlich eine Gerade den Zusammenhang beschreibt. In <a href="#fig-slm-model-qqplots-2">Abbildung&nbsp;<span>13.9 (b)</span></a> ist dagegen ein Zusammenhang abgetragen, bei dem die empirischen und die theoretische Verteilung nicht zusammenpassen. In diesem Fall sind die haben die Randwerte der empirischen Vereteilung eine höhere Wahrscheinlichkeit als die unter der theoretischen Verteilung zu erwarten ist. D.h. extreme Werte kommen in der beobachteten Verteilung öfter in der theoretischen Verteilung vor. Dies deutet darauf hin, dass die Streuung der Daten möglicherweise nicht korrekt modelliert wurde. In diesem Fall, wird von einer <em>tail heavy</em> Verteilung gesprochen.</p>
<p>In <a href="#fig-slm-model-qqplots-3">Abbildung&nbsp;<span>13.9 (c)</span></a> ist der gegenteilige Effekt abgetragen. Hier hat die theoretische Verteilung mehr Wahrscheinlichkeitsmasse in den Randzonen als die empirische Verteilung. Die beobachtete Verteilung ist <em>tail light</em>. Entsprechend ist in <a href="#fig-slm-model-qqplots-4">Abbildung&nbsp;<span>13.9 (d)</span></a> ein Beispiel abgebildet, bei dem nur eine der Randzonen zu viel Wahrscheinlichkeitsmasse besitzt. Da die theoretische Verteilung wiederum die Normalverteilung ist und diese Symmetrisch ist, deutet diese darauf hin, das die empirische Verteilung ähnlich wie in <a href="#fig-slm-model-qqplots-2">Abbildung&nbsp;<span>13.9 (b)</span></a> in der rechten Randzone zu <em>viele</em> Werte hat und daher Rechtsschief ist.</p>
<p>Für unsere Daten ergibt sich das folgende qq-Diagramm (siehe <a href="#fig-slm-model-qqplot-data">Abbildung&nbsp;<span>13.10</span></a>)</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-qqplot-data" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-qqplot-data-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.10: QQ-Diagramm der Residuen des ADAS-ADCS-Modells</figcaption>
</figure>
</div>
</div>
</div>
<p>Der Graph sieht zunächst einmal gar nicht so schlecht aus. Allerdings deutet die Abweichung rechts oben darauf hin, das möglicherweise die Streuung nicht korrekt abgeschätzt wurde. Insbesondere ist ein Wert zu sehen, der im Verhältnis zu den anderen Werten schon relativ weit von der Gerade weg ist. Daher ist es hier angezeigt, diesen Wert noch einmal genauer zu untersuchen.</p>
</section>
<section id="qq-plot-in-r" class="level3" data-number="13.1.2">
<h3 data-number="13.1.2" class="anchored" data-anchor-id="qq-plot-in-r"><span class="header-section-number">13.1.2</span> qq-Plot in <code>R</code></h3>
<p>In <code>R</code> gibt es zwei direkte Methoden einen qq-Plot zu erstellen. Mittels des Standardgrafiksystem können mit den Funktionen <code>qqnorm()</code> und <code>qqline()</code> qq-Plots mit der dazugehörigen Gerade erstellt werden. Für das <code>ggplot()</code>-System stehen die <code>geom</code>s <code>geom_qq()</code> und <code>geom_qq_line()</code> zur Verfügung. Wichtig ist hierbei, das in <code>aes()</code> der Parameter <code>sample</code> definiert werden muss. Für unser Spielzeugbeispiel sieht dies folgendermaßen aus:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df_toy <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(<span class="at">y =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">5</span>, <span class="sc">-</span><span class="fl">1.2</span>, <span class="fl">0.1</span>, <span class="dv">7</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_toy, <span class="fu">aes</span>(<span class="at">sample=</span>y)) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-slm-model-qqplot-toy" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-qqplot-toy-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.11: qq-Plot der Spielzeugdaten mittels <code>ggplot()</code></figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="standardisierte-residuen" class="level3" data-number="13.1.3">
<h3 data-number="13.1.3" class="anchored" data-anchor-id="standardisierte-residuen"><span class="header-section-number">13.1.3</span> Standardisierte Residuen</h3>
<p>Eine Möglichkeit so einen Wert zu untersuchen, ist abzuschätzen wie <em>ungewöhnlich</em> der zu dem Residuen <span class="math inline">\(e_i\)</span> gehörende <span class="math inline">\(y_i\)</span>-Wert ist. Ein Problem der einfachen Residuen <span class="math inline">\(e_i\)</span> ist, dass diese laut der Modellannahmen die gleiche Varianz <span class="math inline">\(\sigma^2\)</span> haben sollten. Allerdings, auf Grund der Art, wie die <span class="math inline">\(e_i\)</span> berechnet werden, folgt die Randbedingung, dass die Summe der <span class="math inline">\(e_i\)</span> gleich Null ist, <span class="math inline">\(\sum_{i=1}^n e_i = 0\)</span>. Dies führt dazu, dass die einfachen Residuen nicht unanbhängig voneinander sind und nicht immer Homoskedastizität besitzen. Daher gibt es eine weitere Art Residuen anhand des Modell zu berechnen, die nicht unter diesen Beschränkungen leiden. Dies sind die standardisierten Residuen <span class="math inline">\(e_{Si}\)</span>. Dazu müssen wir uns zunächst mit Hebelwerte <span class="math inline">\(h_i\)</span> beschäftigen.</p>
<section id="hebelwerte" class="level4" data-number="13.1.3.1">
<h4 data-number="13.1.3.1" class="anchored" data-anchor-id="hebelwerte"><span class="header-section-number">13.1.3.1</span> Hebelwerte</h4>
<p>Wenn ein Modell an die Daten gefittet wird, dann haben nicht alle Werte den gleichen Einfluss auf die Modellparameter. Manche Werte üben einen stärkeren Einfluss auf das Modell aus als andere Werte. In <a href="#fig-slm-model-outlier-1">Abbildung&nbsp;<span>13.12</span></a> ist ein Beispiel abgebildet für einen Datensatz bei dem ein einzelner Punkt einen übermäßig großen Einfluss auf das Modell ausübt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-outlier-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-outlier-1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.12: Beispiel für einen Datenpunkt mit einem großen Einfluss auf das Modell. Die resultierenden Regressionsgeraden sind mit dem Punkt (rot) und ohne den Punkt (grün) abgetragen.</figcaption>
</figure>
</div>
</div>
</div>
<p>Der einzelen Punkt rechts oben in <a href="#fig-slm-model-outlier-1">Abbildung&nbsp;<span>13.12</span></a> hat einen großen Einfluss auf die resultierende Regressionsgerade wie in der Abbildung zu sehen ist. Der Einfluss ist zum Teil durch den großen Abstand des <span class="math inline">\(x_i\)</span>-Wertes vom Mittelwert der <span class="math inline">\(x_i\)</span>-Werte <span class="math inline">\(\bar{x}\)</span> bestimmt. Der Einfluss jedes einzelnen <span class="math inline">\(x\)</span>-Wertes wird mittels der sogenannten Hebelwerte <span class="math inline">\(h_i\)</span> bestimmt. Die genaue Berechnung der Hebelwerte <span class="math inline">\(h_i\)</span> ist für das weitere Verständnis allerdings nicht wichtig, sondern mehr das Verständnis des Konzepts. Die Hebelwerte <span class="math inline">\(h_i\)</span> können Werte in <span class="math inline">\(h_i \in [1/n,1]\)</span> annehmen. In <code>R</code> können die Hebelwerte mit der Funktion <code>hatvalues()</code> berechnet werden.</p>
<p>Tragen wir in die Grafik die Hebelwerte in die Grafik <a href="#fig-slm-model-outlier-1">Abbildung&nbsp;<span>13.12</span></a> ein (siehe <a href="#fig-slm-model-outlier-2">Abbildung&nbsp;<span>13.13</span></a>), dann ist zu sehen, dass der abgesetzte Wert auch den größten Hebelwert hat.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-outlier-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-outlier-2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.13: Beispiel für einen Datenpunkt mit einem großen Einfluss auf das Modell. Die Werte geben die jeweiligen Hebelwerte <span class="math inline">\(h_i\)</span> der Datenpunkte wieder.</figcaption>
</figure>
</div>
</div>
</div>
<p>Eine Daumenregel für die Hebelwerte ist der Schwellenwert von <span class="math inline">\((2k+2)/n\)</span>, wobei <span class="math inline">\(k\)</span> die Anzahl der unabhängigen Variablen ist. Für den Beispieldatensatz in <a href="#fig-slm-model-outlier-2">Abbildung&nbsp;<span>13.13</span></a> würde sich daher ein Wert von <span class="math inline">\((2\cdot 1+2)/30 = 0.13\)</span> ergeben. Entsprechend wäre der abgesetzte Wert mit einem Hebelwert von <span class="math inline">\(h_i = 0.54\)</span> als problematisch einzustufen.</p>
<p>Nach diesem kurzen Exkurs zu den Hebelwerten <span class="math inline">\(h_i\)</span>, schauen wir uns für unsere weitere Betrachtung der Residuen zunächst den Zusammenhang zwischen der Varianz der Residuen in der Population <span class="math inline">\(\sigma^2\)</span> und der Varianz der geschätzten Residuen <span class="math inline">\(\sigma^2(\hat{\epsilon}_i) = \sigma^2(e_i)\)</span> an. Es gilt:</p>
<p><span class="math display">\[\begin{equation}
\sigma^2(e_i) = \sigma^2 (1 - h_i)
\label{eq-slm-model-vare_i}
\end{equation}\]</span></p>
<p>D.h. wenn ein Datenpunkt <span class="math inline">\(x_i\)</span> einen kleineren Einfluss auf das Modell ausübt und dementsprechend einen kleinen Hebelwert <span class="math inline">\(h_i\)</span>, dann wird die Varianz für diesen Wert nahezu korrekt eingeschätzt. Hat der Wert <span class="math inline">\(x_i\)</span> allerdings, einen großen Hebelwert <span class="math inline">\(h_i\)</span>, führt die dazu, dass die Varianz für diesen Wert stärker unterschützt wird. Dieser Zusammenhang kann dazu benutzt werden standardisierte Residuen zu erstellen.</p>
<p><span class="math display">\[\begin{equation}
e_{Si} = \frac{e_i}{\hat{\sigma}\sqrt{1-h_i}}
\label{eq-slm-model-stresid}
\end{equation}\]</span></p>
<p>Die standardisierten Residuen <span class="math inline">\(e_{Si}\)</span> haben dazu die Eigenschaft, dass sie eine Varianz und damit Standardabweichung von <span class="math inline">\(\sigma^2(e_{Si}) = 1\)</span> haben, also Standardnormalverteilt <span class="math inline">\(\Phi(z)\)</span> sein sollten. Dadurch können Abweichungen von den Modellannahmen leichter Identifiziert werden, da die Skala normiert ist. In <code>R</code> kann die standardiserten Residuen <span class="math inline">\(e_{Si}\)</span> mittels der Funktion <code>rstandard()</code> berechnet werden. Eine Standardgrafik zum inspizieren der standardisierten Residuen ist wiederum eine Abbildung der <span class="math inline">\(e_{Si}\)</span> gegen die <span class="math inline">\(\hat{y}_i\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-rstandard" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-rstandard-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.14: Grafik der standardisierten Residuen <span class="math inline">\(e_{Si}\)</span> gegen die Vorhersagewerte <span class="math inline">\(\hat{y}_i\)</span> für das ADL-Modell.</figcaption>
</figure>
</div>
</div>
</div>
<p>Die <a href="#fig-slm-model-rstandard">Abbildung&nbsp;<span>13.14</span></a> sieht relativ ähnlich zu <a href="#fig-sim-model-rplot-1">Abbildung&nbsp;<span>13.3</span></a> aus. Durch die Änderung der Skala ist jetzt aber leichter abschätzbar ob die Verteilung der erwarteten Normalverteilung folgt. D.h. etwa <span class="math inline">\(\frac{2}{3}\)</span> der Werte sollten zwischen <span class="math inline">\(-1\)</span> und <span class="math inline">\(1\)</span> liegen und etwa <span class="math inline">\(95\%\)</span> zwischen <span class="math inline">\(-2\)</span> und <span class="math inline">\(2\)</span>. Bis auf den einen Punkt oben rechts, sieht alles soweit unauffällig aus.</p>
</section>
</section>
<section id="studentized-residuals" class="level3" data-number="13.1.4">
<h3 data-number="13.1.4" class="anchored" data-anchor-id="studentized-residuals"><span class="header-section-number">13.1.4</span> Studentized Residuals</h3>
<p>Die letzte Art von Residuen sind die sogenannten Studentized Residuals <span class="math inline">\(e_{Ti}\)</span>, die mittels der folgenden Formel berechnet werden.</p>
<p><span class="math display">\[\begin{equation}
e_{Ti} = \frac{e_i}{\hat{\sigma}_{(-i)}\sqrt{1-h_i}}
\label{eq-slm-model-rstudent}
\end{equation}\]</span></p>
<p>Die Formel <span class="math inline">\(\eqref{eq-slm-model-rstudent}\)</span> ist sehr ähnlich zu derer für die standardisierten Residuen, der einzige Unterschied ist der Term <span class="math inline">\(\hat{\sigma}_{(-i)}\)</span>. Dieser bezeichnet die Residualvarianz wenn dass Modell ohne den Datenpunkt <span class="math inline">\(i\)</span> gefittet wird. D.h. wie stark verändert sich die Schätzung der Varianz wenn ein Datenpunkt weggelassen wird. Normalerweise sollte eine einzelner Punkt keinen übermäßigen Einfluss auf die geschätzte Varianz haben, daher können die Studentized Residuals dazu verwendet werden problematische Datenpunkte zu identifizieren. Wenn die tatsächlichen Residuen einer Normalverteilung folgen, dann kann gezeigt werden, dass die Studentized Residuals einer <span class="math inline">\(t\)</span>-Verteilung mit <span class="math inline">\(N-k-2\)</span> Freiheitsgeraden folgen. Daher könnte sogar ein formaler statistischer Test durchgeführt werden. In <code>R</code> können die Studentized Residuals <span class="math inline">\(e_{Ti}\)</span> mittels der Funktion <code>rstudent()</code> berechnet werden und werden entsprechend den anderen Residuen in dem üblichen Graphen gegen die vorhergesagten Werte <span class="math inline">\(\hat{y}_i\)</span> abgetragen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-restudent-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-restudent-1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.15: Graph der Studentized Residuals <span class="math inline">\(S_{Ti}\)</span> gegen die vorhergesagten Werte <span class="math inline">\(\hat{y}_i\)</span> vor das <code>adl</code>-Modell</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="übersicht-über-die-residuenarten" class="level3" data-number="13.1.5">
<h3 data-number="13.1.5" class="anchored" data-anchor-id="übersicht-über-die-residuenarten"><span class="header-section-number">13.1.5</span> Übersicht über die Residuenarten</h3>
<p>In <a href="#tbl-slm-model-resids">Tabelle&nbsp;<span>13.3</span></a> sind noch einmal die drei Arten von Residuen aufgelistet.</p>
<div id="tbl-slm-model-resids" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;13.3: Übersicht über verschiedene Arten von Residuen</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Typ</th>
<th>Berechnung</th>
<th>Ziel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Einfache Residuen</td>
<td><span class="math inline">\(e_i = y_i - \hat{y}_i\)</span></td>
<td>Verteilungsannahme</td>
</tr>
<tr class="even">
<td>Standardisierte Residuen</td>
<td><span class="math inline">\(e_{Si} = \frac{e_i}{\hat{\sigma}\sqrt{1-h_i}}\)</span></td>
<td>Verteilungsannahme</td>
</tr>
<tr class="odd">
<td>Studentized Residuen</td>
<td><span class="math inline">\(e_{Ti} = \frac{e_i}{\hat{\sigma}_{(-i)}\sqrt{1-h_i}}\)</span></td>
<td>Einfluss auf Modell</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="ausgabe-von-summary-continued" class="level3" data-number="13.1.6">
<h3 data-number="13.1.6" class="anchored" data-anchor-id="ausgabe-von-summary-continued"><span class="header-section-number">13.1.6</span> Ausgabe von <code>summary()</code> (continued)</h3>
<p>Nach dieser Betrachtung der Residuen, die nach jedem Modellfit inspiziert werden sollten um zu überprüfen ob die Modellannahmen angemessen sind schauen wir uns noch einmal kurz die Ausgabe von <code>summary()</code> an.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = adcs ~ adas, data = adl)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.2177  -3.8033  -0.4663   2.7950  20.9634 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  26.5445     4.3052   6.166 3.05e-07 ***
adas         -0.2638     0.1015  -2.599   0.0131 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.516 on 39 degrees of freedom
Multiple R-squared:  0.1477,    Adjusted R-squared:  0.1258 
F-statistic: 6.757 on 1 and 39 DF,  p-value: 0.01312</code></pre>
</div>
</div>
<p>Nach der Wiedergabe des gefitten Modells erfolgt direkt eine Zusammenfassung der Residuen über Minimum und Maximum, Q1 und Q3 und den Median. Jetzt sollte daher auch besser nachvollziehbar sein, warum es sinnvoll ist diese Statistiken über die Residuen direkt anzugeben. Die beiden Extremwerte geben einen ersten Überblick auf mögliche Ausreißer, während die erste Quartile Q1 und die dritte Quartile Q3 möglich Asymmetrien in der Verteilung der Residuen anzeigen. Laut der Annahem der Residuen als Normalverteilt mit <span class="math inline">\(\mu = 0\)</span>, sollten diese beiden Werte etwa gleich weit von Null entfernt sein. Dementsprechend sollte der Median nahe an Null dran sein. Was nah ist, kommt dabei immer auf die Einheit der abhängigen Variablen an, wenn der Abstand in Kilometern ist kann ein kleiner Wert schon problematisch sein, während wenn eine Sprungweite in Mikrometern angeben wird eine großer Wert unbedenklich sein kann. Der Schätzerwert für <span class="math inline">\(\sigma\)</span> selbst, wir unten mit <code>Residual standard error</code> angegeben.</p>
<p>Im vorliegenden Fall des Modells für die <code>adl</code>-Daten ist der Median dementsprechend doch etwas weit von Null entfernt und der geschätzte Residualfehler <span class="math inline">\(\hat{\sigma} = 6.52\)</span> ebenfalls relativ groß. <span class="math inline">\(\hat{\sigma}\)</span> kann mittels der Funktion <code>sigma()</code> erhalten werden.</p>
</section>
<section id="zum-nachlesen" class="level3" data-number="13.1.7">
<h3 data-number="13.1.7" class="anchored" data-anchor-id="zum-nachlesen"><span class="header-section-number">13.1.7</span> Zum Nachlesen</h3>
<p>Zum weiteren Vertiefen der Inhalte findet ihr in <span class="citation" data-cites="kutner2005">Kutner u.&nbsp;a. (<a href="references.html#ref-kutner2005" role="doc-biblioref">2005, p.100–114</a>)</span>, <span class="citation" data-cites="pos_residuals">Altman und Krzywinski (<a href="references.html#ref-pos_residuals" role="doc-biblioref">2016b</a>)</span> und <span class="citation" data-cites="fox2011">Fox (<a href="references.html#ref-fox2011" role="doc-biblioref">2011, p.285–296</a>)</span> noch einmal gute Zusammenfassungen.</p>
</section>
</section>
<section id="einflussmetriken" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="einflussmetriken"><span class="header-section-number">13.2</span> Einflussmetriken</h2>
<p>Um das gefittet Modell zu diagnostizieren reicht es allerdings nicht aus, sich nur die Residuen anzuschauen. Ein weiterer wichtiger Punkt ist die Analyse des Einflusses der einzelnen Datenpunkte auf das Modell. Wenn alles gut läuft sollte es keine einzelnen Datenpunkte geben, die einen übermäßig großen Einfluss auf das Modell ausüben. Anders ausgedrückt, die Anwesenheit bzw. Abwesenheit von einzelnen Datenpunkte sollte nicht dazu führen, dass die Aussage des Modells sich stark verändert. Im folgenden schauen wir uns dazu verschiedene Einflussmetriken die den Einfluss der Datenpunkte auf das Modell abschätzen. Die Idee der Einflussmetriken ist dabei die Gleiche wie schon bei den Studentized Residuals. Der Einfluss der Datenpunkte auf den Modellfit wird interpretiert indem ein Modell mit und ein Modell ohne den jeweiligen Datenpunkt gefittet wird. Der Einfluss auf verschiedene Modellparameter wird dann bestimmt und dementsprechend als möglicherweise bedenklich eingestuft. Die Meisten der im folgenden vorgestellten Ansätze verwenden in der einen oder anderen Form die Hebelwerte <span class="math inline">\(h_i\)</span> die wir bereits kennengelernt haben.</p>
<section id="dffits-difference-in-fits" class="level3" data-number="13.2.1">
<h3 data-number="13.2.1" class="anchored" data-anchor-id="dffits-difference-in-fits"><span class="header-section-number">13.2.1</span> DFFITS (difference in fits)</h3>
<p>Das erst Maß, daß wir uns anschauen ist DFFITS (kurz für difference in fits). Das DFFITS-Maß wird getreent für jeden einzelnen Datenpunkt berechnet und der Einfluss des Datenpunkts auf den gefitteten Werte <span class="math inline">\(\hat{y}_i\)</span> für den jeweiligen Datenpunkt berechnet. Formal:</p>
<p><span class="math display">\[\begin{equation}
(DFFITS)_i = \frac{\hat{y}_i - \hat{y}_{i(i)}}{\hat{\sigma}\sqrt{h_i}}
\label{eq-slm-model-dffits}
\end{equation}\]</span></p>
<p>Im Zähler kommen von Formel<span class="math inline">\(\eqref{eq-slm-model-dffits}\)</span> kommen zweimal die vorhergesagte <span class="math inline">\(y\)</span>-Werte vor. <span class="math inline">\(\hat{y}_i\)</span> ist dabei der ganz normale Vorhersagewert der uns mittlerweile schon mehrfach begegnet ist. Der zweite Wert <span class="math inline">\(\hat{y}_{i(i)}\)</span> bezeichnet den vorhergesagten Wert aus dem Modell aus dem der Wert <span class="math inline">\(y_i\)</span> weggelassen wurde. D.h, dass Modell ist mit einem Wert weniger gefittet worden. Daher misst die Differenz <span class="math inline">\(\hat{y}_i - \hat{y}_{i(i)}\)</span> den Unterschied in den Vorhersagewerte zwischen den zwei Modellen bei denen einmal der Wert <span class="math inline">\(y_i\)</span> zum fitten verwendet wurde und einmal wenn <span class="math inline">\(y_i\)</span> weggelassen wurde. Umso größer der Unterschied zwischen diesen beiden Werte umso größer ist der Einfluss des Wertes <span class="math inline">\(y_i\)</span> auf den Modellfit. Im Nenner von Formel<span class="math inline">\(\eqref{eq-slm-model-dffits}\)</span> wird wieder ein ähnlicher Normierungswert wie bei den Studentizied Residuals angewendet. Insgesamt, wird mittels DFFITS daher für jeden Datenpunkt ein Wert ermittelt und umso größer dieser Wert ist umso größer ist der Einfluss des jeweiligen Datenpunktes auf den Modellfit.</p>
<p>Im idealen Fall sollte alle Datenpunkt ungefähr den gleichen Einfluss haben und einzelne Datenpunkte die einen übermäßig großen Einfluss auf das Modell haben sollten noch einmal genauer inspiziert werden.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p>Als Daumenregel, kann für kleine bis mittlere Datensätze ein DFFITS von <span class="math inline">\(\approx 1\)</span> auf Probleme hindeuten, während bei großen Datensätzen <span class="math inline">\(\approx 2\sqrt{k/N}\)</span> als Orientierungshilfe verwendet werden kann (k := Anzahl der Prediktoren, N := Stichprobengröße).</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warnung
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wenn ein Wert außerhalb der Daumenregel liegt, heißt das nicht, dass er automatisch ausgeschlossen werden muss/soll, sondern lediglich inspiziert werden sollte und das Modell mit und ohne diesen Wert interpretiert werden sollte.</p>
</div>
</div>
<p>In <code>R</code> können die DFFITS werden mittels der <code>dffits()</code>-Funktion berechnet werden. Als Parameter erwartet <code>dffits()</code> das gefittete <code>lm()</code>-Objekt. Ähnlich wie bei den Residuen, werden die DFFITS-Werte gegen die vorhergesagten <span class="math inline">\(y_i\)</span>-Werte graphisch abgetragen um die Wert zu inspizieren und Probleme in der Modellspezifikation zu identifizieren.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-dffits" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-dffits-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.16: Graph der DFFITS-Werte gegen <span class="math inline">\(\hat{y}_i\)</span> für das <code>adl</code>-Modell.</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-model-dffits">Abbildung&nbsp;<span>13.16</span></a> sind die DFFITS-Werte gegen die vorhergesagten Werte <span class="math inline">\(\hat{y}_i\)</span> abgetragen und zusätzlich die Daumenregel <span class="math inline">\(\pm1\)</span> eingezeichnet. Hier ist ein Wert nur gerade so außerhalb des vorgeschlagenen Bereichs. Hier könnte daher sich dieser Datenpunkt noch einmal genauer angeschaut werden, ob bei Ausschluß des Wertes es zu einer qualitativ anderen Interpretation der Daten kommt oder ob bespielsweise Übertragungsfehler für diesen Wert vorliegen oder sonstige Gründe.</p>
</section>
<section id="cook-abstand" class="level3" data-number="13.2.2">
<h3 data-number="13.2.2" class="anchored" data-anchor-id="cook-abstand"><span class="header-section-number">13.2.2</span> Cook-Abstand</h3>
<p>Während DFFITS den Einfluss des Datenpunktes <span class="math inline">\(i\)</span> auf den jeweiligen Datenpunkt abschätzt, wird bei dem sogenanten Cook-Abstand der Einfluss des <span class="math inline">\(i\)</span>-ten Datenpunktes auf alle <span class="math inline">\(n\)</span> vorhergesagten Werte <span class="math inline">\(\hat{y}_i\)</span>. Formal:</p>
<p><span class="math display">\[\begin{equation}
D_i = \frac{\sum_{j=1}^N(\hat{y_j} - \hat{y}_{j(i)})}{k\hat{\sigma}^2}
\label{eq-slm-model-cook}
\end{equation}\]</span></p>
<p>Hier bedeutet die Syntax <span class="math inline">\(\hat{y}_{j(i)}\)</span> der vorhergesagte Wert für den Datenpunkt <span class="math inline">\(j\)</span> wenn der <span class="math inline">\(i\)</span>-te Datenpunkt ausgelassen wird. In <code>R</code> können die Cook-Abstände mit Hilfe der Funktion <code>cooks.distance()</code> berechnet werden.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p>Eine Daumenregel um einen <em>möglichen</em> Ausreißer zu identifzieren kann über <span class="math inline">\(D_i &gt; 1\)</span> abgeschätzt werden.</p>
</div>
</div>
<p>In <a href="#fig-slm-model-cook">Abbildung&nbsp;<span>13.17</span></a> ist wiederum der übliche Graph gegen die vorhergesagten Werte <span class="math inline">\(\hat{y}_i\)</span> zu sehen. Anhand der abgebildeten Wert ist keiner der Datenpunkte als problematisch zu identifizieren.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-cook" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-cook-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.17: Cook’s <span class="math inline">\(D_i\)</span> gegen <span class="math inline">\(\hat{y}_i\)</span> für das <code>adl</code>-Modell.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="dfbetas" class="level3" data-number="13.2.3">
<h3 data-number="13.2.3" class="anchored" data-anchor-id="dfbetas"><span class="header-section-number">13.2.3</span> DFBETAS</h3>
<p>Als letztes Maß schauen wir uns noch DFBETAS an. DFBETAS berechnet ein Maß für die Veränderung der <span class="math inline">\(\beta\)</span>-Koeffizienten auf Grund der einzelnen Datenpunkte <span class="math inline">\(i\)</span>. D.h. es wird jetzt nicht nur ein Wert für jeden Wert berechnet, sondern ein Wert für den jeden Datenpunkt und jeden <span class="math inline">\(\beta\)</span>-Koeffizienten. In unseren Fall mit einem y-Achsenabschnitt <span class="math inline">\(\beta_0\)</span> und einem Steigungskoeffizienten <span class="math inline">\(\beta_1\)</span> werden entsprechend <span class="math inline">\(2 \times x\)</span> Werte berechnet. Formal:</p>
<p><span class="math display">\[\begin{equation}
(DFBETAS)_{k(i)} = \frac{\hat{\beta}_k - \hat{\beta}_{k(i)}}{\sqrt{\hat{\sigma}^2c_{kk}}}
\label{eq-slm-model-dfbetas}
\end{equation}\]</span></p>
<p>Wie aus Formel <span class="math inline">\(\eqref{eq-slm-model-dfbetas}\)</span> ersichtlich wird, wird die Veränderungen der Koeffizienten <span class="math inline">\(\beta_i\)</span> bei weglassen des <span class="math inline">\(i\)</span>-ten Datenpunktes abgeschätzt. Den Wert <span class="math inline">\(c_{kk}\)</span> lassen wir unberücksichtigt, da er wiederum nur einen Normierungsfaktor darstellt.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp
</div>
</div>
<div class="callout-body-container callout-body">
<p>Als Daumenregel gilt für kleine bis mittlere Datensätze <span class="math inline">\(\approx 1\)</span>, bzw. für große Datensätze <span class="math inline">\(\approx 2/\sqrt{N}\)</span></p>
</div>
</div>
<p>Wiederum gibt es eine spezielle Funktion in <code>R</code> um die DFBETAS zu berechnen <code>dfbeta()</code>. Dabei ist jedoch zu beachten das eine Matrize mit <span class="math inline">\(k\)</span>-Spalten von <code>dfbeta()</code> zurück gegeben wird. Jede Spalte gibt den Wert für den jeweiligen <span class="math inline">\(\beta\)</span>-Koeffizienten an.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slm-model-dfbeta" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="slm_model_fit_files/figure-html/fig-slm-model-dfbeta-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;13.18: DFBETA-Werte für <span class="math inline">\(\beta_0\)</span> und <span class="math inline">\(\beta_1\)</span> gegen <span class="math inline">\(\hat{y}_i\)</span></figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-slm-model-dfbeta">Abbildung&nbsp;<span>13.18</span></a> sind die DFBETAS für die beiden Koeffizienten <span class="math inline">\(\hat{beta}_0\)</span> und <span class="math inline">\(\hat{beta}_1\)</span> abgetragen. Hier ist zu sehen, dass die Wert für den Steigunsgkoeffizienten <span class="math inline">\(\beta_1\)</span> alle als unproblematisch anzusehen sind, während in Bezug auf <span class="math inline">\(\beta_0\)</span> ein paar wenige Fälle eine weiter Inspektion nach sich ziehen könnten. Allerdings sollte berücksichtigt werden, dass der y-Achsenabschnitt sehr stark durch die Verteilung der Datenpunkte in Bezug auf die <span class="math inline">\(x\)</span>-Werte beeinflusst ist, da der Mittelwert der <span class="math inline">\(x\)</span>-Werte bei <span class="math inline">\(\bar{x} = 41.2\)</span> liegt.</p>
</section>
<section id="übersicht-über-die-einflussmetriken" class="level3" data-number="13.2.4">
<h3 data-number="13.2.4" class="anchored" data-anchor-id="übersicht-über-die-einflussmetriken"><span class="header-section-number">13.2.4</span> Übersicht über die Einflussmetriken</h3>
<p>In <a href="#tbl-slm-model-influence">Tabelle&nbsp;<span>13.4</span></a> sind noch einmal die verschiedenen Methoden tabellarisch dargestellt.</p>
<div id="tbl-slm-model-influence" class="anchored">
<table class="table">
<caption>Tabelle&nbsp;13.4: Übersicht über die verschiedene Einflussmaße zur Bewertung der Modellgüte</caption>
<thead>
<tr class="header">
<th>Typ</th>
<th>Veränderung</th>
<th>Daumenregel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\((DFFITS)_i\)</span></td>
<td>Vorhersagewert i</td>
<td><span class="math inline">\(2\sqrt{k/N}\)</span></td>
</tr>
<tr class="even">
<td>Cook</td>
<td>Durchschnittliche Vorhersagewerte</td>
<td><span class="math inline">\(&gt;1\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\((DFBETAS)_{k(i)}\)</span></td>
<td>Koeffizient i</td>
<td><span class="math inline">\(2\sqrt{N}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(e_{Ti}\)</span></td>
<td>Residuum i</td>
<td>t-Verteilung(n-k-2)</td>
</tr>
</tbody>
</table>
</div>
<p>Nochmal, die Daumenregeln sind wirklich auch nur Daumenregeln und identifzieren nicht automatisch ein Problem im Datensatz.</p>
</section>
<section id="zum-nacharbeiten" class="level3" data-number="13.2.5">
<h3 data-number="13.2.5" class="anchored" data-anchor-id="zum-nacharbeiten"><span class="header-section-number">13.2.5</span> Zum Nacharbeiten</h3>
<p>Noch mal weitere Informationen findet Ihr in <span class="citation" data-cites="pos_diagnostics">Altman und Krzywinski (<a href="references.html#ref-pos_diagnostics" role="doc-biblioref">2016a</a>)</span>, <span class="citation" data-cites="fox2011">Fox (<a href="references.html#ref-fox2011" role="doc-biblioref">2011, p.294–302</a>)</span> und <span class="citation" data-cites="young2019">Young (<a href="references.html#ref-young2019" role="doc-biblioref">2019</a>)</span>.</p>
</section>
</section>
<section id="diagnoseplots-in-r" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="diagnoseplots-in-r"><span class="header-section-number">13.3</span> Diagnoseplots in <code>R</code></h2>
<p>Da die Diagnose eines gefitten Modell in jedem Fall durchgeführt werden soll und es sich dabei also um eine alltägliche Aufgabe handelt, gibt es mit <code>plot(mod)</code> einen short-cut um eine Reihe von Diagnoseplots direkt erstellen zu können.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="slm_model_fit_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Eine weitere Möglichkeit ist das package <code>performance</code> das zahlreiche Funktion enthält rund um die Analyse von Modellfits (siehe beispielweise <code>performance::check_model()</code>).</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-pos_diagnostics" class="csl-entry" role="listitem">
Altman, Naomi, und Martin Krzywinski. 2016a. <span>„Points of significance: Analyzing outliers: influential or nuisance“</span>. <em>Nature Methods</em> 13 (4): 281–82.
</div>
<div id="ref-pos_residuals" class="csl-entry" role="listitem">
———. 2016b. <span>„Points of significance: regression diagnostics“</span>. <em>Nature Methods</em> 13 (5): 385–86.
</div>
<div id="ref-fox2011" class="csl-entry" role="listitem">
Fox, John. 2011. <em>An R companion to applied regression</em>. 2. Aufl. SAGE Publication Inc., Thousand Oaks.
</div>
<div id="ref-kutner2005" class="csl-entry" role="listitem">
Kutner, Michael H, Christopher J Nachtsheim, John Neter, und William Li. 2005. <em>Applied Linear Statistical Models</em>. 5. Aufl. McGraw-Hill Irwin New York.
</div>
<div id="ref-young2019" class="csl-entry" role="listitem">
Young, Alwyn. 2019. <span>„Channeling fisher: Randomization tests and the statistical insignificance of seemingly significant experimental results“</span>. <em>The Quarterly Journal of Economics</em> 134 (2): 557–98.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./slm_inference.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inferenz</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./slm_prediction.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Vorhersage</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>